package directorybridge

import (
	"context"
	"time"

	oasfgenerator "github.com/c360studio/semstreams/processor/oasf-generator"
)

// Backend abstracts the wire-level publish/withdraw operations against a
// directory. The directory-bridge component owns lifecycle, retry, KV
// watching, and heartbeat scheduling; backends own protocol, encoding,
// and authentication.
//
// All methods must be safe for concurrent use — the heartbeat loop and the
// KV watcher goroutine call them concurrently.
//
// Publish must be idempotent. The bridge calls it on every KV change AND
// when re-registering after a Refresh that returns a new RecordID. Backends
// that natively support upsert (HTTP POST /v1/agents in our v1 spec; gRPC
// PushReferrer in agntcy/dir) satisfy this trivially. Backends that don't
// must internally deduplicate by EntityID.
type Backend interface {
	// Publish registers (or re-registers) an agent record with the directory.
	// Returns the backend-assigned RecordID, which the bridge stores so it
	// can later Refresh or Withdraw without re-deriving it.
	Publish(ctx context.Context, req *PublishRequest) (*PublishResult, error)

	// Refresh extends the lifetime of a previously published record. The
	// HTTP backend implements this as a heartbeat POST; future gRPC
	// backends may push a renewed CID-anchored record.
	Refresh(ctx context.Context, req *RefreshRequest) (*PublishResult, error)

	// Withdraw removes a previously published record. Called when the
	// source entity is deleted from ENTITY_STATES, and on component Stop
	// for every active registration.
	Withdraw(ctx context.Context, req *WithdrawRequest) error
}

// PublishRequest is the bridge → backend contract for adding or replacing
// an agent record. Domain-shaped: backends translate to their wire format.
type PublishRequest struct {
	// EntityID is the SemStreams entity ID for the agent. Backends may
	// echo it in protocol-specific metadata so the directory can correlate
	// records back to their source system.
	EntityID string

	// AgentDID is the agent's decentralized identifier, generated by the
	// identity provider before this call. Required.
	AgentDID string

	// Record is the OASF document to publish. The bridge guarantees it is
	// non-nil and has passed oasfgenerator.OASFRecord.Validate.
	Record *oasfgenerator.OASFRecord

	// TTL is the requested lifetime of the registration. The backend may
	// honor it exactly, clamp it to a server-side maximum, or ignore it
	// (CID-anchored backends don't expire on the publisher side).
	TTL time.Duration

	// Metadata is opaque key/value data forwarded by the bridge. Today the
	// bridge sets {"semstreams_entity_id": EntityID, "source": "semstreams"};
	// future callers may add lineage or trace context.
	Metadata map[string]any
}

// PublishResult is what the backend returns after a successful publish or
// refresh.
type PublishResult struct {
	// RecordID is the backend-assigned identifier for this publication.
	//   - HTTP backend: server-issued registration_id
	//   - future gRPC backend: the OASF record CID
	// Persisted by the bridge so subsequent Refresh/Withdraw can address
	// the same record.
	RecordID string

	// ExpiresAt is when the bridge should next refresh. Zero means the
	// backend does not expire records on its own (CID-anchored or
	// long-lived OCI artifact); the bridge skips heartbeat scheduling in
	// that case.
	ExpiresAt time.Time
}

// RefreshRequest is the bridge → backend contract for heartbeating.
type RefreshRequest struct {
	// RecordID is the previously-issued PublishResult.RecordID.
	RecordID string

	// AgentDID is the agent's DID; some backends bind heartbeat auth to it.
	AgentDID string
}

// WithdrawRequest is the bridge → backend contract for removal.
type WithdrawRequest struct {
	// RecordID is the previously-issued PublishResult.RecordID.
	RecordID string

	// AgentDID is the agent's DID; some backends bind withdrawal auth to it.
	AgentDID string
}
