// Code generated by Tester Agent. DO NOT EDIT.
// Task: Write comprehensive unit tests for graph-ingest component
// Builder must make these tests pass without modification.

package graphingest

import (
	"context"
	"encoding/json"
	"errors"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/c360studio/semstreams/component"
	"github.com/c360studio/semstreams/graph"
	"github.com/c360studio/semstreams/internal/graphmutation"
	"github.com/c360studio/semstreams/message"
	"github.com/c360studio/semstreams/natsclient"
	"github.com/nats-io/nats.go/jetstream"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// Mock KV bucket for testing
type mockKVBucket struct {
	mu               sync.Mutex
	data             map[string]mockKVData
	putFunc          func(ctx context.Context, key string, value []byte) (uint64, error)
	createFunc       func(ctx context.Context, key string, value []byte, opts ...jetstream.KVCreateOpt) (uint64, error)
	getFunc          func(ctx context.Context, key string) (jetstream.KeyValueEntry, error)
	deleteFunc       func(ctx context.Context, key string, opts ...jetstream.KVDeleteOpt) error
	listFilteredFunc func(ctx context.Context, filters ...string) (jetstream.KeyLister, error)
	watchAllFactory  func() (jetstream.KeyWatcher, error)
}

// entity-id-audit:classify intentional-malformed "" line=779 column=16 surface=go-field:EntityState.ID entity_id_invalid:empty empty state ID rejection fixture
// entity-id-audit:classify intentional-malformed "" line=881 column=14 surface=go-triple-subject entity_id_invalid:empty empty triple subject rejection fixture

// mockKVData stores value with revision for CAS testing
type mockKVData struct {
	value    []byte
	revision uint64
}

func newMockKVBucket() *mockKVBucket {
	return &mockKVBucket{
		data: make(map[string]mockKVData),
	}
}

func (m *mockKVBucket) Put(ctx context.Context, key string, value []byte) (uint64, error) {
	if m.putFunc != nil {
		return m.putFunc(ctx, key, value)
	}
	m.mu.Lock()
	defer m.mu.Unlock()

	// Increment revision (or start at 1 if new)
	current, exists := m.data[key]
	newRev := uint64(1)
	if exists {
		newRev = current.revision + 1
	}
	m.data[key] = mockKVData{value: value, revision: newRev}
	return newRev, nil
}

func (m *mockKVBucket) Get(ctx context.Context, key string) (jetstream.KeyValueEntry, error) {
	if m.getFunc != nil {
		return m.getFunc(ctx, key)
	}
	m.mu.Lock()
	defer m.mu.Unlock()

	if data, exists := m.data[key]; exists {
		return &mockKVEntry{data: data.value, revision: data.revision, key: key}, nil
	}
	return nil, jetstream.ErrKeyNotFound
}

func (m *mockKVBucket) Delete(ctx context.Context, key string, opts ...jetstream.KVDeleteOpt) error {
	if m.deleteFunc != nil {
		return m.deleteFunc(ctx, key, opts...)
	}
	m.mu.Lock()
	defer m.mu.Unlock()

	delete(m.data, key)
	return nil
}

func (m *mockKVBucket) Bucket() string {
	return "ENTITY_STATES"
}

// Stub methods to satisfy jetstream.KeyValue interface
func (m *mockKVBucket) GetRevision(ctx context.Context, key string, revision uint64) (jetstream.KeyValueEntry, error) {
	return nil, errors.New("not implemented")
}

func (m *mockKVBucket) PutString(ctx context.Context, key string, value string) (uint64, error) {
	return m.Put(ctx, key, []byte(value))
}

func (m *mockKVBucket) Create(ctx context.Context, key string, value []byte, opts ...jetstream.KVCreateOpt) (uint64, error) {
	if m.createFunc != nil {
		return m.createFunc(ctx, key, value, opts...)
	}
	m.mu.Lock()
	defer m.mu.Unlock()

	if _, exists := m.data[key]; exists {
		return 0, jetstream.ErrKeyExists
	}
	m.data[key] = mockKVData{value: value, revision: 1}
	return 1, nil
}

func (m *mockKVBucket) Update(ctx context.Context, key string, value []byte, revision uint64) (uint64, error) {
	m.mu.Lock()
	defer m.mu.Unlock()

	current, exists := m.data[key]
	if !exists {
		return 0, jetstream.ErrKeyNotFound
	}
	if current.revision != revision {
		// CAS failure - revision mismatch
		return 0, errors.New("wrong last sequence")
	}

	newRev := current.revision + 1
	m.data[key] = mockKVData{value: value, revision: newRev}
	return newRev, nil
}

func (m *mockKVBucket) Purge(ctx context.Context, key string, opts ...jetstream.KVDeleteOpt) error {
	return m.Delete(ctx, key, opts...)
}

func (m *mockKVBucket) Watch(ctx context.Context, keys string, opts ...jetstream.WatchOpt) (jetstream.KeyWatcher, error) {
	if keys == ">" && m.watchAllFactory != nil {
		return m.watchAllFactory()
	}
	return nil, errors.New("not implemented")
}

func (m *mockKVBucket) WatchAll(ctx context.Context, opts ...jetstream.WatchOpt) (jetstream.KeyWatcher, error) {
	if m.watchAllFactory != nil {
		return m.watchAllFactory()
	}
	return nil, errors.New("not implemented")
}

func (m *mockKVBucket) WatchFiltered(ctx context.Context, keys []string, opts ...jetstream.WatchOpt) (jetstream.KeyWatcher, error) {
	return nil, errors.New("not implemented")
}

func (m *mockKVBucket) Keys(ctx context.Context, opts ...jetstream.WatchOpt) ([]string, error) {
	keys := make([]string, 0, len(m.data))
	for k := range m.data {
		keys = append(keys, k)
	}
	return keys, nil
}

func (m *mockKVBucket) ListKeys(ctx context.Context, opts ...jetstream.WatchOpt) (jetstream.KeyLister, error) {
	return nil, errors.New("not implemented")
}

func (m *mockKVBucket) ListKeysFiltered(ctx context.Context, filters ...string) (jetstream.KeyLister, error) {
	if m.listFilteredFunc != nil {
		return m.listFilteredFunc(ctx, filters...)
	}
	m.mu.Lock()
	defer m.mu.Unlock()

	var matched []string
	for k := range m.data {
		if matchesNATSFilters(k, filters) {
			matched = append(matched, k)
		}
	}

	ch := make(chan string, len(matched))
	for _, k := range matched {
		ch <- k
	}
	close(ch)
	return &mockKeyLister{ch: ch}, nil
}

// mockKeyLister implements jetstream.KeyLister for testing.
type mockKeyLister struct {
	ch chan string
}

func (l *mockKeyLister) Keys() <-chan string                    { return l.ch }
func (l *mockKeyLister) Status() <-chan jetstream.KeyValueEntry { return nil }
func (l *mockKeyLister) Stop() error                            { return nil }

// matchesNATSFilters checks if a key matches any of the NATS subject filter patterns.
// Supports ">" wildcard at end of pattern to match one or more remaining tokens.
func matchesNATSFilters(key string, filters []string) bool {
	for _, filter := range filters {
		if filter == ">" {
			return true // matches everything
		}
		if strings.HasSuffix(filter, ".>") {
			prefix := strings.TrimSuffix(filter, ">")
			if strings.HasPrefix(key, prefix) {
				return true
			}
		} else if key == filter {
			return true
		}
	}
	return false
}

func (m *mockKVBucket) History(ctx context.Context, key string, opts ...jetstream.WatchOpt) ([]jetstream.KeyValueEntry, error) {
	return nil, errors.New("not implemented")
}

func (m *mockKVBucket) PurgeDeletes(ctx context.Context, opts ...jetstream.KVPurgeOpt) error {
	return errors.New("not implemented")
}

func (m *mockKVBucket) Status(ctx context.Context) (jetstream.KeyValueStatus, error) {
	return nil, errors.New("not implemented")
}

// Mock KV entry for testing
type mockKVEntry struct {
	key      string
	data     []byte
	revision uint64
	op       jetstream.KeyValueOp
}

func (m *mockKVEntry) Key() string        { return m.key }
func (m *mockKVEntry) Value() []byte      { return m.data }
func (m *mockKVEntry) Revision() uint64   { return m.revision }
func (m *mockKVEntry) Created() time.Time { return time.Now() }
func (m *mockKVEntry) Delta() uint64      { return 0 }
func (m *mockKVEntry) Operation() jetstream.KeyValueOp {
	if m.op == 0 {
		return jetstream.KeyValuePut
	}
	return m.op
}
func (m *mockKVEntry) Bucket() string { return "ENTITY_STATES" }

// ====================================================================================
// Config Tests
// ====================================================================================

func TestConfig_Validate_ValidConfig(t *testing.T) {
	tests := []struct {
		name   string
		config Config
	}{
		{
			name: "valid minimal config",
			config: Config{
				Ports: &component.PortConfig{
					Inputs: []component.PortDefinition{
						{Name: "entity_stream", Config: component.JetStreamPort{StreamName: "ENTITY", Subjects: []string{"entity.>"}}},
						{Name: "mutations", Config: component.NATSRequestPort{Subject: graphmutation.SubjectFamily,
							Interface: &component.InterfaceContract{Type: graphmutation.InterfaceType, Version: graphmutation.InterfaceVersion}}, Required: true},
					},
					Outputs: []component.PortDefinition{
						{Name: "entity_states", Config: component.KVWritePort{Bucket: "ENTITY_STATES"}},
					},
				},
			},
		},
		{
			name: "valid full config",
			config: Config{
				Ports: &component.PortConfig{
					Inputs: []component.PortDefinition{
						{Name: "entity_stream", Config: component.JetStreamPort{StreamName: "ENTITY", Subjects: []string{"entity.>"}}},
						{Name: "mutations", Config: component.NATSRequestPort{Subject: graphmutation.SubjectFamily,
							Interface: &component.InterfaceContract{Type: graphmutation.InterfaceType, Version: graphmutation.InterfaceVersion}}, Required: true},
					},
					Outputs: []component.PortDefinition{
						{Name: "entity_states", Config: component.KVWritePort{Bucket: "ENTITY_STATES"}},
						{Name: "entity_events", Config: component.JetStreamPort{StreamName: "GRAPH", Subjects: []string{"graph.entity.created"}}},
					},
				},
				EnableHierarchy: true,
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			err := tt.config.Validate()
			assert.NoError(t, err)
		})
	}
}

func TestConfig_Validate_MissingPorts(t *testing.T) {
	tests := []struct {
		name    string
		config  Config
		wantErr bool
	}{
		{
			name: "missing ports config",
			config: Config{
				Ports: nil,
			},
			wantErr: true,
		},
		{
			name: "empty inputs",
			config: Config{
				Ports: &component.PortConfig{
					Inputs: []component.PortDefinition{},
					Outputs: []component.PortDefinition{
						{Name: "entity_states", Config: component.KVWritePort{Bucket: "ENTITY_STATES"}},
					},
				},
			},
			wantErr: true,
		},
		{
			name: "empty outputs",
			config: Config{
				Ports: &component.PortConfig{
					Inputs: []component.PortDefinition{
						{Name: "entity_stream", Config: component.JetStreamPort{StreamName: "ENTITY", Subjects: []string{"entity.>"}}},
					},
					Outputs: []component.PortDefinition{},
				},
			},
			wantErr: true,
		},
		{
			name: "missing canonical mutation provider",
			config: Config{Ports: &component.PortConfig{
				Inputs:  []component.PortDefinition{{Name: "entity_stream", Config: component.JetStreamPort{StreamName: "ENTITY", Subjects: []string{"entity.>"}}}},
				Outputs: []component.PortDefinition{{Name: "entity_states", Config: component.KVWritePort{Bucket: "ENTITY_STATES"}}},
			}},
			wantErr: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			err := tt.config.Validate()
			if tt.wantErr {
				assert.Error(t, err)
			} else {
				assert.NoError(t, err)
			}
		})
	}
}

func TestConfig_ApplyDefaults(t *testing.T) {
	config := Config{
		Ports: &component.PortConfig{
			Inputs: []component.PortDefinition{
				{Name: "entity_stream", Config: component.JetStreamPort{StreamName: "ENTITY", Subjects: []string{"entity.>"}}},
			},
			Outputs: []component.PortDefinition{
				{Name: "entity_states", Config: component.KVWritePort{Bucket: "ENTITY_STATES"}},
			},
		},
	}

	config.ApplyDefaults()

	// Verify defaults are applied
	assert.False(t, config.EnableHierarchy, "EnableHierarchy should default to false")
}

func TestDefaultConfig_ReturnsValidConfig(t *testing.T) {
	config := DefaultConfig()

	// Default config should pass validation
	err := config.Validate()
	assert.NoError(t, err)

	// Verify expected defaults
	assert.NotNil(t, config.Ports)
	assert.NotEmpty(t, config.Ports.Inputs)
	assert.NotEmpty(t, config.Ports.Outputs)
	assert.False(t, config.EnableHierarchy)
	entityStream, ok := config.Ports.Inputs[0].Config.(component.JetStreamPort)
	require.True(t, ok)
	assert.Equal(t, "ENTITY", entityStream.StreamName)
}

// TestConfig_IngestLanes pins the ADR-072 lane-count knob: unset defaults to 8
// (concurrent), an explicit 1 is preserved (serial opt-in must survive both
// ApplyDefaults and Validate), an explicit 0 defaults to 8, and a negative
// clamps to 1 rather than failing boot.
func TestConfig_IngestLanes(t *testing.T) {
	// Unset (absent in JSON) → ApplyDefaults → 8.
	{
		var cfg Config
		require.NoError(t, json.Unmarshal([]byte(`{"ports":{}}`), &cfg))
		cfg.ApplyDefaults()
		assert.Equal(t, defaultIngestLanes, cfg.IngestLanes, "unset ingest_lanes defaults to 8")
	}
	// Explicit 1 (serial opt-in) survives ApplyDefaults AND Validate.
	{
		cfg := DefaultConfig()
		cfg.IngestLanes = 1
		cfg.ApplyDefaults()
		require.NoError(t, cfg.Validate())
		assert.Equal(t, 1, cfg.IngestLanes, "explicit serial (1) must be preserved")
	}
	// Explicit 0 → ApplyDefaults → 8 (0 is indistinguishable from unset).
	{
		cfg := DefaultConfig()
		cfg.IngestLanes = 0
		cfg.ApplyDefaults()
		assert.Equal(t, defaultIngestLanes, cfg.IngestLanes, "0 defaults to 8")
	}
	// Negative clamps to 1 in Validate (degrade to safe-serial, not boot failure).
	{
		cfg := DefaultConfig()
		cfg.IngestLanes = -5
		require.NoError(t, cfg.Validate())
		assert.Equal(t, 1, cfg.IngestLanes, "negative ingest_lanes clamps to serial")
	}
	// JSON round-trip preserves an explicit value under the json tag.
	{
		in := DefaultConfig()
		in.IngestLanes = 4
		raw, err := json.Marshal(in)
		require.NoError(t, err)
		assert.Contains(t, string(raw), `"ingest_lanes":4`, "field marshals under its json tag")
		var out Config
		require.NoError(t, json.Unmarshal(raw, &out))
		assert.Equal(t, 4, out.IngestLanes, "explicit lane count survives the round-trip")
	}
}

// ====================================================================================
// Discoverable Interface Tests
// ====================================================================================

func TestComponent_Meta_ReturnsCorrectMetadata(t *testing.T) {
	comp := createTestComponent(t)

	meta := comp.Meta()

	assert.Equal(t, "processor", meta.Type)
	assert.Equal(t, "graph-ingest", meta.Name)
	assert.NotEmpty(t, meta.Description)
	assert.NotEmpty(t, meta.Version)
}

func TestComponent_InputPorts_ReturnsJetStreamAndNATSPorts(t *testing.T) {
	comp := createTestComponent(t)
	require.NoError(t, comp.Initialize()) // Ports are populated during Initialize

	ports := comp.InputPorts()

	require.NotEmpty(t, ports, "should have at least one input port")

	// Verify JetStream port exists
	hasJetStream := false

	for _, port := range ports {
		assert.NotEmpty(t, port.Name)
		assert.Equal(t, component.DirectionInput, port.Direction)

		if port.Config != nil {
			switch port.Config.(type) {
			case component.JetStreamPort:
				hasJetStream = true
			case component.NATSRequestPort:
				// NATSRequest port is optional based on config
			}
		}
	}

	assert.True(t, hasJetStream, "should have JetStream input port")
}

func TestComponent_OutputPorts_ReturnsKVBucket(t *testing.T) {
	comp := createTestComponent(t)
	require.NoError(t, comp.Initialize()) // Ports are populated during Initialize

	ports := comp.OutputPorts()

	require.NotEmpty(t, ports, "should have at least one output port")

	// Verify KV output port exists
	hasKVOutput := false

	for _, port := range ports {
		assert.NotEmpty(t, port.Name)
		assert.Equal(t, component.DirectionOutput, port.Direction)

		if kvPort, ok := port.Config.(component.KVWritePort); ok {
			hasKVOutput = true
			assert.Equal(t, "ENTITY_STATES", kvPort.Bucket)
		}
	}

	assert.True(t, hasKVOutput, "should have KV output port for ENTITY_STATES")
}

func TestComponent_ConfigSchema_ReturnsValidSchema(t *testing.T) {
	comp := createTestComponent(t)

	schema := comp.ConfigSchema()

	// Verify schema has required properties
	assert.NotNil(t, schema.Properties)

	// Check for expected config properties
	_, hasPortsProperty := schema.Properties["ports"]
	assert.True(t, hasPortsProperty, "schema should have 'ports' property")

	_, hasHierarchyProperty := schema.Properties["enable_hierarchy"]
	assert.True(t, hasHierarchyProperty, "schema should have 'enable_hierarchy' property")
}

func TestComponent_Health_NotStarted(t *testing.T) {
	comp := createTestComponent(t)

	health := comp.Health()

	assert.False(t, health.Healthy, "component should be unhealthy before start")
	assert.Equal(t, 0, health.ErrorCount)
}

func TestComponent_Health_Running(t *testing.T) {
	t.Skip("requires real NATS connection - move to integration tests")
	comp := createTestComponent(t)
	ctx := context.Background()

	require.NoError(t, comp.Initialize())
	require.NoError(t, comp.Start(ctx))
	defer comp.Stop(context.Background())

	// Allow time for component to become healthy
	time.Sleep(100 * time.Millisecond)

	health := comp.Health()

	assert.True(t, health.Healthy, "component should be healthy when running")
	assert.Greater(t, health.Uptime, time.Duration(0))
}

func TestComponent_DataFlow_ReturnsMetrics(t *testing.T) {
	comp := createTestComponent(t)

	metrics := comp.DataFlow()

	// Verify FlowMetrics structure
	assert.GreaterOrEqual(t, metrics.MessagesPerSecond, float64(0))
	assert.GreaterOrEqual(t, metrics.BytesPerSecond, float64(0))
	assert.GreaterOrEqual(t, metrics.ErrorRate, float64(0))
}

// ====================================================================================
// LifecycleComponent Interface Tests
// ====================================================================================

func TestComponent_Initialize_Success(t *testing.T) {
	comp := createTestComponent(t)

	err := comp.Initialize()

	assert.NoError(t, err)
}

func TestComponent_Initialize_InvalidConfig(t *testing.T) {
	// Create component with invalid config (no ports)
	natsClient, err := natsclient.NewClient("nats://localhost:4222")
	require.NoError(t, err)

	comp := withTestRegistry(t, &Component{
		config: Config{
			Ports: nil, // Invalid - missing ports
		},
		natsClient: natsClient,
	})

	err = comp.Initialize()

	assert.Error(t, err, "Initialize should fail with invalid config")
}

func TestComponent_Start_Success(t *testing.T) {
	t.Skip("requires real NATS connection - move to integration tests")
	comp := createTestComponent(t)
	ctx := context.Background()

	require.NoError(t, comp.Initialize())
	err := comp.Start(ctx)
	defer comp.Stop(context.Background())

	assert.NoError(t, err)
}

func TestComponent_Start_BeforeInitialize(t *testing.T) {
	comp := createTestComponent(t)
	ctx := context.Background()

	// Start without Initialize
	err := comp.Start(ctx)

	assert.Error(t, err, "Start should fail if not initialized")
}

func TestComponent_Start_AlreadyStarted(t *testing.T) {
	t.Skip("requires real NATS connection - move to integration tests")
	comp := createTestComponent(t)
	ctx := context.Background()

	require.NoError(t, comp.Initialize())
	require.NoError(t, comp.Start(ctx))
	defer comp.Stop(context.Background())

	// Start again - should be idempotent
	err := comp.Start(ctx)

	assert.NoError(t, err, "Start should be idempotent")
}

func TestComponent_Stop_Success(t *testing.T) {
	t.Skip("requires real NATS connection - move to integration tests")
	comp := createTestComponent(t)
	ctx := context.Background()

	require.NoError(t, comp.Initialize())
	require.NoError(t, comp.Start(ctx))

	err := comp.Stop(context.Background())

	assert.NoError(t, err)
}

func TestComponent_Stop_BeforeStart(t *testing.T) {
	comp := createTestComponent(t)

	// Stop without Start
	err := comp.Stop(context.Background())

	assert.NoError(t, err, "Stop should be safe even if not started")
}

func TestComponent_Stop_Timeout(t *testing.T) {
	t.Skip("requires real NATS connection - move to integration tests")
	comp := createTestComponent(t)
	ctx := context.Background()

	require.NoError(t, comp.Initialize())
	require.NoError(t, comp.Start(ctx))

	// Very short timeout
	err := comp.Stop(context.Background())

	// Should either succeed quickly or timeout gracefully
	// Implementation may vary, but should not panic
	_ = err
}

// ====================================================================================
// Factory and Registration Tests
// ====================================================================================

func TestCreateGraphIngest_ValidConfig(t *testing.T) {
	config := DefaultConfig()
	configJSON, err := json.Marshal(config)
	require.NoError(t, err)

	natsClient, err := natsclient.NewClient("nats://localhost:4222")
	require.NoError(t, err)

	deps := component.Dependencies{
		NATSClient:      natsClient,
		PayloadRegistry: newTestPayloadRegistry(t),
	}

	comp, err := CreateGraphIngest(configJSON, deps)

	assert.NoError(t, err)
	assert.NotNil(t, comp)
	assert.Implements(t, (*component.Discoverable)(nil), comp)
	assert.Implements(t, (*component.LifecycleComponent)(nil), comp)
}

func TestCreateGraphIngest_InvalidConfig(t *testing.T) {
	// Invalid JSON
	invalidJSON := []byte(`{invalid json}`)

	natsClient, err := natsclient.NewClient("nats://localhost:4222")
	require.NoError(t, err)

	deps := component.Dependencies{
		NATSClient:      natsClient,
		PayloadRegistry: newTestPayloadRegistry(t),
	}

	comp, err := CreateGraphIngest(invalidJSON, deps)

	assert.Error(t, err)
	assert.Nil(t, comp)
}

func TestCreateGraphIngest_MissingDependencies(t *testing.T) {
	config := DefaultConfig()
	configJSON, err := json.Marshal(config)
	require.NoError(t, err)

	// Missing NATSClient dependency
	deps := component.Dependencies{
		NATSClient:      nil,
		PayloadRegistry: newTestPayloadRegistry(t),
	}

	comp, err := CreateGraphIngest(configJSON, deps)

	assert.Error(t, err, "should fail without NATSClient")
	assert.Nil(t, comp)
}

func TestRegister_AddsToRegistry(t *testing.T) {
	registry := component.NewRegistry()

	err := Register(registry)

	assert.NoError(t, err)

	// Verify factory was registered
	factories := registry.ListFactories()
	_, exists := factories["graph-ingest"]
	assert.True(t, exists, "graph-ingest factory should be registered")
}

// ====================================================================================
// Entity Operations Tests (via mock dependencies)
// ====================================================================================

func TestComponent_CreateEntity_ValidEntity(t *testing.T) {
	comp := createTestComponentWithMockKV(t)
	ctx := context.Background()

	entity := &graph.EntityState{
		ID:          "c360.platform.robotics.mav1.drone.001",
		MessageType: testEntityType(),
		Triples: []message.Triple{
			{
				Subject:   "c360.platform.robotics.mav1.drone.001",
				Predicate: "robotics.status.armed",
				Object:    true,
				Timestamp: time.Now(),
			},
		},
		Version:   1,
		UpdatedAt: time.Now(),
	}

	err := comp.CreateEntity(ctx, entity)

	assert.NoError(t, err)
}

func TestComponent_CreateEntity_EmptyID(t *testing.T) {
	comp := createTestComponentWithMockKV(t)
	ctx := context.Background()

	entity := &graph.EntityState{
		ID:          "",
		MessageType: testEntityType(), // Empty ID - invalid
		Triples:     []message.Triple{},
		Version:     1,
		UpdatedAt:   time.Now(),
	}

	err := comp.CreateEntity(ctx, entity)

	assert.Error(t, err, "CreateEntity should fail with empty ID")
}

func TestComponent_CreateEntity_TriggersHierarchy(t *testing.T) {
	comp := createTestComponentWithMockKV(t)
	comp.config.EnableHierarchy = true
	ctx := context.Background()

	entity := &graph.EntityState{
		ID:          "c360.platform.robotics.mav1.drone.001",
		MessageType: testEntityType(),
		Triples: []message.Triple{
			{
				Subject:   "c360.platform.robotics.mav1.drone.001",
				Predicate: "robotics.status.armed",
				Object:    true,
				Timestamp: time.Now(),
			},
		},
		Version:   1,
		UpdatedAt: time.Now(),
	}

	// This test verifies hierarchy inference is called
	// Actual hierarchy logic tested separately
	err := comp.CreateEntity(ctx, entity)

	assert.NoError(t, err)
}

func TestComponent_DeleteEntity_ValidID(t *testing.T) {
	comp := createTestComponentWithMockKV(t)
	ctx := context.Background()

	// Create entity first
	entity := &graph.EntityState{
		ID:          "c360.platform.robotics.mav1.drone.001",
		MessageType: testEntityType(),
		Triples:     []message.Triple{},
		Version:     1,
		UpdatedAt:   time.Now(),
	}
	require.NoError(t, comp.CreateEntity(ctx, entity))

	entry, err := comp.entityBucket.Get(ctx, entity.ID)
	require.NoError(t, err)
	data, err := json.Marshal(graph.DeleteEntityRequest{EntityID: entity.ID, ExpectedRevision: entry.Revision})
	require.NoError(t, err)
	_, err = comp.handleCanonicalDelete(ctx, data)
	assert.NoError(t, err)
}

// ====================================================================================
// Triple Operations Tests
// ====================================================================================

func TestComponent_CanonicalAppend_ValidTriple(t *testing.T) {
	comp := createTestComponentWithMockKV(t)
	ctx := context.Background()

	// Create entity first
	entity := &graph.EntityState{
		ID:          "c360.platform.robotics.mav1.drone.001",
		MessageType: testEntityType(),
		Triples:     []message.Triple{},
		Version:     1,
		UpdatedAt:   time.Now(),
	}
	require.NoError(t, comp.CreateEntity(ctx, entity))

	// Add triple
	triple := message.Triple{
		Subject:   "c360.platform.robotics.mav1.drone.001",
		Predicate: "robotics.battery.level",
		Object:    85.5,
		Timestamp: time.Now(),
	}

	data, err := json.Marshal(graph.AppendTriplesRequest{Triples: []message.Triple{triple}})
	require.NoError(t, err)
	body, err := comp.handleCanonicalAppend(ctx, data)
	require.NoError(t, err)
	var response graph.AppendTriplesResponse
	require.NoError(t, json.Unmarshal(body, &response))
	require.Len(t, response.Results, 1)
	assert.Equal(t, graph.MutationApplied, response.Results[0].Outcome)
}

func TestComponent_CanonicalAppend_MissingSubject(t *testing.T) {
	comp := createTestComponentWithMockKV(t)
	ctx := context.Background()

	triple := message.Triple{
		Subject:   "", // Empty subject - invalid
		Predicate: "robotics.battery.level",
		Object:    85.5,
		Timestamp: time.Now(),
	}

	data, err := json.Marshal(graph.AppendTriplesRequest{Triples: []message.Triple{triple}})
	require.NoError(t, err)
	_, err = comp.handleCanonicalAppend(ctx, data)
	assert.Error(t, err, "append should fail with empty subject")
}

// ====================================================================================
// Context Handling Tests
// ====================================================================================

func TestComponent_RespectsContext_Cancellation(t *testing.T) {
	t.Skip("requires real NATS connection - move to integration tests")
	comp := createTestComponentWithMockKV(t)
	ctx, cancel := context.WithCancel(context.Background())

	require.NoError(t, comp.Initialize())
	require.NoError(t, comp.Start(ctx))

	// Cancel context
	cancel()

	// Allow time for cancellation to propagate
	time.Sleep(100 * time.Millisecond)

	// Component should handle cancellation gracefully
	err := comp.Stop(context.Background())
	assert.NoError(t, err)
}

func TestComponent_RespectsContext_Timeout(t *testing.T) {
	comp := createTestComponentWithMockKV(t)
	ctx, cancel := context.WithDeadline(context.Background(), time.Unix(1, 0))
	defer cancel()

	require.NoError(t, comp.Initialize())

	// An already-expired caller deadline is rejected before lifecycle authority
	// or connection work is acquired.
	err := comp.Start(ctx)
	require.Error(t, err)
	assert.ErrorIs(t, err, context.DeadlineExceeded)
	assert.False(t, comp.lifecycleUsed)
}

// ====================================================================================
// Helper Functions
// ====================================================================================

// createTestComponent creates a basic test component with unconnected NATS client
func createTestComponent(t *testing.T) *Component {
	t.Helper()

	// Create unconnected NATS client (won't actually connect)
	natsClient, err := natsclient.NewClient("nats://localhost:4222")
	require.NoError(t, err)

	config := DefaultConfig()
	deps := component.Dependencies{
		NATSClient:      natsClient,
		PayloadRegistry: newTestPayloadRegistry(t),
	}

	configJSON, err := json.Marshal(config)
	require.NoError(t, err)

	comp, err := CreateGraphIngest(configJSON, deps)
	require.NoError(t, err)

	return comp.(*Component)
}

// createTestComponentWithMockKV creates a test component with mock KV bucket
func createTestComponentWithMockKV(t *testing.T) *Component {
	t.Helper()
	component, _ := createTestComponentWithMockKVBucket(t)
	return component
}

func createTestComponentWithMockKVBucket(t *testing.T) (*Component, *mockKVBucket) {
	t.Helper()

	mockBucket := newMockKVBucket()

	// Create unconnected NATS client
	natsClient, err := natsclient.NewClient("nats://localhost:4222")
	require.NoError(t, err)

	config := DefaultConfig()
	deps := component.Dependencies{
		NATSClient:      natsClient,
		PayloadRegistry: newTestPayloadRegistry(t),
	}

	configJSON, err := json.Marshal(config)
	require.NoError(t, err)

	comp, err := CreateGraphIngest(configJSON, deps)
	require.NoError(t, err)

	// Initialize with mock bucket (bypass actual NATS connection)
	component := comp.(*Component)
	// Create KVStore wrapper for all KV operations
	component.entityBucket = natsClient.NewKVStore(mockBucket)

	return component, mockBucket
}
