// Code generated by Tester Agent. DO NOT EDIT.
// Task: Phase 0 - Bypass coalescing set when debounce=0
// Builder must make these tests pass without modification.

package rule

import (
	"context"
	"sync"
	"sync/atomic"
	"testing"
	"time"

	"github.com/c360studio/semstreams/pkg/cache"
)

// TestCoalescingSet_BatchingBehavior tests batching works correctly when debounce>0
// Given: CoalescingSet with 100ms window
// When: Multiple rapid updates added
// Then: Callback is invoked once with all deduplicated keys after window expires
func TestCoalescingSet_BatchingBehavior(t *testing.T) {
	ctx := context.Background()
	window := 100 * time.Millisecond

	var callbackInvocations int64
	var mu sync.Mutex
	var lastBatch []string

	callback := func(keys []string) {
		atomic.AddInt64(&callbackInvocations, 1)
		mu.Lock()
		lastBatch = keys
		mu.Unlock()
	}

	cs := cache.NewCoalescingSet(ctx, window, callback)
	defer cs.Close()

	// Add multiple keys rapidly (faster than window)
	cs.Add("entity1")
	cs.Add("entity2")
	cs.Add("entity1") // Duplicate - should be deduplicated
	cs.Add("entity3")

	// Pending count should reflect deduplicated set
	pending := cs.PendingCount()
	if pending != 3 {
		t.Errorf("Expected 3 pending entities (deduplicated), got %d", pending)
	}

	// Wait for window to expire
	time.Sleep(150 * time.Millisecond)

	// Callback should have been invoked exactly once
	invocations := atomic.LoadInt64(&callbackInvocations)
	if invocations != 1 {
		t.Errorf("Expected callback to be invoked once, got %d invocations", invocations)
	}

	// Check batch contents
	mu.Lock()
	batch := lastBatch
	mu.Unlock()

	if len(batch) != 3 {
		t.Errorf("Expected batch size 3, got %d", len(batch))
	}

	// Verify deduplication worked
	seen := make(map[string]bool)
	for _, key := range batch {
		if seen[key] {
			t.Errorf("Duplicate key %q in batch - deduplication failed", key)
		}
		seen[key] = true
	}
}

// TestCoalescingSet_MultipleBatches tests multiple debounce windows
// Given: CoalescingSet with short window
// When: Updates arrive in separate time windows
// Then: Each window triggers separate batch callback
func TestCoalescingSet_MultipleBatches(t *testing.T) {
	ctx := context.Background()
	window := 50 * time.Millisecond

	var callbackInvocations int64
	callback := func(keys []string) {
		atomic.AddInt64(&callbackInvocations, 1)
	}

	cs := cache.NewCoalescingSet(ctx, window, callback)
	defer cs.Close()

	// First batch
	cs.Add("entity1")
	time.Sleep(70 * time.Millisecond) // Wait for first window to expire

	// Second batch
	cs.Add("entity2")
	time.Sleep(70 * time.Millisecond) // Wait for second window to expire

	invocations := atomic.LoadInt64(&callbackInvocations)
	if invocations != 2 {
		t.Errorf("Expected 2 callback invocations (2 windows), got %d", invocations)
	}
}

// TestCoalescingSet_Remove tests deletion cancels pending evaluation
// Given: CoalescingSet with pending entity
// When: Entity is removed before window expires
// Then: Entity is not included in batch callback
func TestCoalescingSet_Remove(t *testing.T) {
	ctx := context.Background()
	window := 100 * time.Millisecond

	var mu sync.Mutex
	var lastBatch []string

	callback := func(keys []string) {
		mu.Lock()
		lastBatch = keys
		mu.Unlock()
	}

	cs := cache.NewCoalescingSet(ctx, window, callback)
	defer cs.Close()

	// Add entities
	cs.Add("entity1")
	cs.Add("entity2")
	cs.Add("entity3")

	// Remove entity2 before window expires
	time.Sleep(30 * time.Millisecond)
	cs.Remove("entity2")

	// Wait for window to expire
	time.Sleep(100 * time.Millisecond)

	// Check batch - should only have entity1 and entity3
	mu.Lock()
	batch := lastBatch
	mu.Unlock()

	if len(batch) != 2 {
		t.Errorf("Expected batch size 2 after removal, got %d", len(batch))
	}

	for _, key := range batch {
		if key == "entity2" {
			t.Errorf("entity2 should not be in batch after removal")
		}
	}
}

// TestCoalescingSet_EmptyBatchNoCallback tests callback is not invoked for empty batches
// Given: CoalescingSet with no pending entities
// When: Window expires
// Then: Callback is not invoked (optimization)
func TestCoalescingSet_EmptyBatchNoCallback(t *testing.T) {
	ctx := context.Background()
	window := 50 * time.Millisecond

	var callbackInvocations int64
	callback := func(keys []string) {
		atomic.AddInt64(&callbackInvocations, 1)
	}

	cs := cache.NewCoalescingSet(ctx, window, callback)
	defer cs.Close()

	// Don't add any entities

	// Wait for multiple windows to expire
	time.Sleep(200 * time.Millisecond)

	// Callback should never be invoked for empty batches
	invocations := atomic.LoadInt64(&callbackInvocations)
	if invocations != 0 {
		t.Errorf("Expected 0 callback invocations for empty batches, got %d", invocations)
	}
}

// TestCoalescingSet_Close tests clean shutdown
// Given: Running CoalescingSet
// When: Close() is called
// Then: Background goroutine stops, ticker stops, no panic
func TestCoalescingSet_Close(t *testing.T) {
	ctx := context.Background()
	window := 100 * time.Millisecond

	callbackInvoked := false
	callback := func(keys []string) {
		callbackInvoked = true
	}

	cs := cache.NewCoalescingSet(ctx, window, callback)

	// Add some entities
	cs.Add("entity1")

	// Close immediately
	err := cs.Close()
	if err != nil {
		t.Errorf("Close() should not error, got: %v", err)
	}

	// Multiple Close() calls should be safe (idempotent)
	err = cs.Close()
	if err != nil {
		t.Errorf("Second Close() should not error, got: %v", err)
	}

	// Brief sleep to verify no callback after close
	time.Sleep(150 * time.Millisecond)

	// Callback may or may not have been invoked depending on timing
	// But Close() should complete without hanging
	_ = callbackInvoked // Suppress unused variable - timing-dependent
}
