// Package milestoneprobe provides the agentic E2E milestone settlement probe.
//
// It exists to make the three #1155 stage-D shapes observable from outside the
// process: a crash between a handler's durable effect and the delivery's Ack, a
// panicking handler that quarantines its lane, and a handler that stays
// transient until the lane's finite MaxDeliver is exhausted. Each shape needs a
// handler that misbehaves deliberately, which no production handler may do.
//
// It is test-only in two independent ways, and both are load-bearing:
//
//  1. The registration hook that reaches this package lives behind the
//     `e2e_process_barrier` build tag (cmd/semstreams/milestone_probe_e2e.go),
//     so an ordinary cmd/semstreams build does not import it at all.
//  2. Even inside that tagged image the handler is registered only when the
//     EnvVar environment variable is set, which only docker/compose/agentic.yml
//     does.
//
// The evidence is an ordinary JetStream stream the scenario creates and reads:
// one APPEND-ONLY attempt record per handler invocation, and one effect record
// per terminal identity, published with Nats-Msg-Id = SourceMessageID so a
// replay collapses onto the stored effect instead of committing a second one.
// That split is the whole proof — attempts count re-invocations, effects count
// consequences, and only a handler that keys on the terminal's own identity
// keeps the second number at one while the first grows.
package milestoneprobe

import (
	"context"
	"crypto/rand"
	"crypto/sha256"
	"encoding/base32"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"log/slog"
	"os"
	"strings"
	"sync/atomic"
	"time"

	"github.com/nats-io/nats.go/jetstream"

	"github.com/c360studio/semstreams/agentic/agentrun"
	"github.com/c360studio/semstreams/natsclient"
	"github.com/c360studio/semstreams/pkg/errs"
)

const (
	// EnvVar arms the probe. It is read once, at registration, by Register.
	// docker/compose/agentic.yml sets it on the agentic tier's SemStreams
	// service; nothing else in the tree does, and no production binary
	// contains the code that reads it.
	EnvVar = "SEMSTREAMS_E2E_MILESTONE_PROBE"

	// EvidenceStream retains this probe's attempt and effect records across an
	// app replacement. Production code never reads it. The scenario creates it
	// before arming any probe terminal and deletes it when the proof ends.
	EvidenceStream = "E2E_MILESTONE_PROBE"

	// SubjectPrefix is the root of the retained evidence protocol.
	SubjectPrefix = "e2e.milestone_probe."

	// AttemptSubjectPrefix identifies one handler invocation. Append-only.
	AttemptSubjectPrefix = SubjectPrefix + "attempt."

	// EffectSubjectPrefix identifies one committed durable consequence. Keyed
	// on the terminal's SourceMessageID, so a replay stores nothing new.
	EffectSubjectPrefix = SubjectPrefix + "effect."

	// RolePrefix marks a terminal as this probe's traffic. The probe demuxes
	// on LoopTerminalEvent.Role rather than on a subject or a new wire field:
	// Role already rides both terminal payloads, so the probe needs no
	// framework change to be addressable and no ordinary terminal can name it.
	RolePrefix = "e2e-milestone-probe:"

	// BehaviorExitBeforeAck commits the durable effect and then ends the
	// process, on the FIRST attempt for a terminal identity only. It is the
	// W1 crash window: the effect is durable, the delivery is not acknowledged.
	BehaviorExitBeforeAck = "exit-before-ack"

	// BehaviorPanicOnce panics on the first attempt for a terminal identity.
	// The subscriber's per-handler recover turns it into a Fatal outcome, so
	// the delivery quarantines: no Ack, Nak or Term, and that lane drains.
	BehaviorPanicOnce = "panic-once"

	// BehaviorTransient returns a transient error on every attempt, so the
	// delivery exhausts the lane's finite MaxDeliver and the framework's
	// MAX_DELIVERIES advisory observer counts it.
	BehaviorTransient = "transient"
)

// attemptSequence disambiguates two invocations inside one process. It is only
// the local half of an attempt's message ID; the durable half is the process
// instance, which is regenerated by every replacement.
var attemptSequence atomic.Uint64

// Role returns the LoopTerminalEvent.Role a scenario stamps on a terminal to
// hand it to this probe with the given behavior.
func Role(behavior string) string { return RolePrefix + behavior }

// BehaviorFromRole reports the probe behavior a terminal's role names, and
// whether the role addresses this probe at all. Ordinary agentic traffic —
// "general", "researcher", an empty role — is not this probe's business and
// returns false, which is how the handler stays a no-op for every terminal the
// tier produces for other reasons.
func BehaviorFromRole(role string) (string, bool) {
	behavior, addressed := strings.CutPrefix(role, RolePrefix)
	if !addressed || behavior == "" {
		return "", false
	}
	return behavior, true
}

// AttemptSubject returns the append-only attempt subject for a terminal identity.
func AttemptSubject(sourceMessageID string) string {
	return AttemptSubjectPrefix + subjectToken(sourceMessageID)
}

// EffectSubject returns the keyed effect subject for a terminal identity.
func EffectSubject(sourceMessageID string) string {
	return EffectSubjectPrefix + subjectToken(sourceMessageID)
}

// subjectToken digests an identity into a subject-safe token. The exact
// identity is carried in the record body, never in the subject, because a
// SourceMessageID is framework-minted and its grammar is not this probe's to
// assume.
func subjectToken(sourceMessageID string) string {
	sum := sha256.Sum256([]byte(sourceMessageID))
	return strings.ToLower(base32.StdEncoding.WithPadding(base32.NoPadding).EncodeToString(sum[:]))
}

// Attempt is one actual handler invocation.
type Attempt struct {
	SourceMessageID string    `json:"source_message_id"`
	LoopID          string    `json:"loop_id"`
	Behavior        string    `json:"behavior"`
	ProcessInstance string    `json:"process_instance"`
	ProcessID       int       `json:"process_id"`
	ObservedAt      time.Time `json:"observed_at"`
}

// Validate rejects malformed evidence and a record for a different terminal.
func (a Attempt) Validate(sourceMessageID string) error {
	switch {
	case sourceMessageID == "":
		return fmt.Errorf("expected source message id is empty")
	case a.SourceMessageID != sourceMessageID:
		return fmt.Errorf("attempt source message id %q does not match %q", a.SourceMessageID, sourceMessageID)
	case a.LoopID == "":
		return fmt.Errorf("attempt loop id is empty")
	case a.Behavior == "":
		return fmt.Errorf("attempt behavior is empty")
	case a.ProcessInstance == "":
		return fmt.Errorf("attempt process instance is empty")
	case a.ProcessID <= 0:
		return fmt.Errorf("attempt process id must be positive")
	case a.ObservedAt.IsZero():
		return fmt.Errorf("attempt observed time is zero")
	default:
		return nil
	}
}

// Effect is the durable consequence a handler owes one terminal identity.
type Effect struct {
	SourceMessageID string    `json:"source_message_id"`
	LoopID          string    `json:"loop_id"`
	ProcessInstance string    `json:"process_instance"`
	CommittedAt     time.Time `json:"committed_at"`
}

// Validate rejects malformed evidence and a record for a different terminal.
func (e Effect) Validate(sourceMessageID string) error {
	switch {
	case sourceMessageID == "":
		return fmt.Errorf("expected source message id is empty")
	case e.SourceMessageID != sourceMessageID:
		return fmt.Errorf("effect source message id %q does not match %q", e.SourceMessageID, sourceMessageID)
	case e.LoopID == "":
		return fmt.Errorf("effect loop id is empty")
	case e.ProcessInstance == "":
		return fmt.Errorf("effect process instance is empty")
	case e.CommittedAt.IsZero():
		return fmt.Errorf("effect committed time is zero")
	default:
		return nil
	}
}

// Register installs the probe on the milestone subscriber, but only when EnvVar
// is set. An unset variable is the ordinary case and is not an error: the
// tagged image boots identically to an untagged one until the agentic tier asks
// for the probe.
//
// It must be called before the subscriber starts, which is what
// agentrun.MilestoneSubscriber.AddHandler already requires.
func Register(subscriber *agentrun.MilestoneSubscriber, client *natsclient.Client, logger *slog.Logger) error {
	if os.Getenv(EnvVar) == "" {
		return nil
	}
	if subscriber == nil {
		return fmt.Errorf("register milestone probe: nil milestone subscriber")
	}
	if client == nil {
		return fmt.Errorf("register milestone probe: nil NATS client")
	}
	instance, err := newProcessInstance()
	if err != nil {
		return fmt.Errorf("register milestone probe: %w", err)
	}
	if logger == nil {
		logger = slog.Default()
	}
	subscriber.AddHandler(&handler{
		client:          client,
		processInstance: instance,
		logger:          logger,
		exit:            os.Exit,
	})
	logger.Warn("milestoneprobe: E2E milestone settlement probe armed",
		slog.String("env", EnvVar),
		slog.String("process_instance", instance))
	return nil
}

type handler struct {
	client          *natsclient.Client
	processInstance string
	logger          *slog.Logger
	// exit ends the process. It is a field so a unit test can observe the
	// decision without ending the test binary.
	exit func(int)
}

func newProcessInstance() (string, error) {
	var nonce [16]byte
	if _, err := rand.Read(nonce[:]); err != nil {
		return "", fmt.Errorf("generate process instance: %w", err)
	}
	return hex.EncodeToString(nonce[:]), nil
}

// OnLoopTerminal implements agentrun.MilestoneHandler.
//
// Ordinary terminals return nil with no IO at all: the probe has nothing to do
// for them, which is exactly the "or it has nothing to do for it" half of the
// handler-done contract.
func (h *handler) OnLoopTerminal(ctx context.Context, ev agentrun.LoopTerminalEvent, _ *agentrun.AgentRun) error {
	behavior, addressed := BehaviorFromRole(ev.Role)
	if !addressed {
		return nil
	}
	attempts, err := h.recordAttempt(ctx, ev, behavior)
	if err != nil {
		return errs.WrapTransient(err, "milestoneprobe", "OnLoopTerminal", "record attempt")
	}
	switch behavior {
	case BehaviorExitBeforeAck:
		if err := h.commitEffect(ctx, ev); err != nil {
			return errs.WrapTransient(err, "milestoneprobe", "OnLoopTerminal", "commit effect")
		}
		if attempts == 1 {
			h.logger.Error("milestoneprobe: ending the process after the durable effect and before the Ack",
				slog.String("source_message_id", ev.SourceMessageID),
				slog.String("loop_id", ev.LoopID),
				slog.String("process_instance", h.processInstance))
			h.exit(1)
		}
		return nil
	case BehaviorPanicOnce:
		if attempts == 1 {
			panic("milestoneprobe: deliberate first-attempt panic for " + ev.SourceMessageID)
		}
		if err := h.commitEffect(ctx, ev); err != nil {
			return errs.WrapTransient(err, "milestoneprobe", "OnLoopTerminal", "commit effect")
		}
		return nil
	case BehaviorTransient:
		return errs.WrapTransient(
			fmt.Errorf("milestoneprobe: deliberate transient outcome for %s (attempt %d)", ev.SourceMessageID, attempts),
			"milestoneprobe", "OnLoopTerminal", "exhaust the lane")
	default:
		// A role that addresses the probe but names no behavior it implements
		// is a harness defect, and a deterministic one: it refuses loudly
		// rather than acknowledging a milestone nobody proved anything about.
		return errs.WrapInvalid(fmt.Errorf("milestoneprobe: unknown behavior %q", behavior),
			"milestoneprobe", "OnLoopTerminal", "classify behavior")
	}
}

// recordAttempt appends this invocation to the terminal's attempt subject and
// returns how many invocations that identity has now had, across every process
// that ever ran it. The count is read from the durable evidence rather than
// from process-local memory on purpose: a replacement process starts with an
// empty memory, and a first-attempt behavior that consulted one would fire
// again after every restart and never converge.
func (h *handler) recordAttempt(
	ctx context.Context, ev agentrun.LoopTerminalEvent, behavior string,
) (uint64, error) {
	attempt := Attempt{
		SourceMessageID: ev.SourceMessageID,
		LoopID:          ev.LoopID,
		Behavior:        behavior,
		ProcessInstance: h.processInstance,
		ProcessID:       os.Getpid(),
		ObservedAt:      time.Now().UTC(),
	}
	wire, err := json.Marshal(attempt)
	if err != nil {
		return 0, fmt.Errorf("marshal milestone probe attempt: %w", err)
	}
	messageID := fmt.Sprintf("%s/%s/%d", ev.SourceMessageID, h.processInstance, attemptSequence.Add(1))
	if err := h.client.PublishToStreamWithMsgID(ctx, AttemptSubject(ev.SourceMessageID), wire, messageID); err != nil {
		return 0, fmt.Errorf("publish milestone probe attempt: %w", err)
	}
	return h.countSubject(ctx, AttemptSubject(ev.SourceMessageID))
}

// commitEffect commits the handler's durable consequence for this terminal
// identity. The Nats-Msg-Id IS the SourceMessageID, which is what makes a
// replay a no-op: every attempt of one stored delivery presents the same
// identity, so the server collapses the re-publish onto the stored effect.
func (h *handler) commitEffect(ctx context.Context, ev agentrun.LoopTerminalEvent) error {
	effect := Effect{
		SourceMessageID: ev.SourceMessageID,
		LoopID:          ev.LoopID,
		ProcessInstance: h.processInstance,
		CommittedAt:     time.Now().UTC(),
	}
	wire, err := json.Marshal(effect)
	if err != nil {
		return fmt.Errorf("marshal milestone probe effect: %w", err)
	}
	if err := h.client.PublishToStreamWithMsgID(
		ctx, EffectSubject(ev.SourceMessageID), wire, ev.SourceMessageID,
	); err != nil {
		return fmt.Errorf("publish milestone probe effect: %w", err)
	}
	return nil
}

func (h *handler) countSubject(ctx context.Context, subject string) (uint64, error) {
	js, err := h.client.JetStream()
	if err != nil {
		return 0, fmt.Errorf("open JetStream for milestone probe evidence: %w", err)
	}
	stream, err := js.Stream(ctx, EvidenceStream)
	if err != nil {
		return 0, fmt.Errorf("open %s: %w", EvidenceStream, err)
	}
	info, err := stream.Info(ctx, jetstream.WithSubjectFilter(subject))
	if err != nil {
		return 0, fmt.Errorf("read %s state for %s: %w", EvidenceStream, subject, err)
	}
	return info.State.Subjects[subject], nil
}
