package agentic

import (
	"fmt"

	"github.com/c360studio/semstreams/message"
)

// CategoryAgentLesson is the message category for the agent-lesson-record
// entity origin contract (ADR-080). It names the ENTITY type born when the
// ops agent's emit_lesson tool distils a reusable lesson into the graph —
// distinct from any event payload. Mirrors CategoryOpsDiagnosis /
// CategoryLoopExecution / CategoryModelEndpoint.
//
// Lessons unify with the rest of agent memory under the agent.* entity-ID
// domain; diagnosis stays ops.* (it is an observability artifact, not
// memory). See ADR-080 decision 1.
const CategoryAgentLesson = "agent_lesson"

// AgentLessonMessageType returns the message.Type for the agent-lesson-record
// entity origin contract — key "agentic.agent_lesson.v1".
//
// Registry decision (mirrors OpsDiagnosisMessageType / LoopExecutionMessageType,
// ADR-056 typed-origin): MUTATION-ONLY. Stamped on
// CreateEntityRequest.Entity.MessageType when EmitLessonExecutor
// births a lesson entity; NEVER published as a BaseMessage payload, NOT
// registered in the payload registry, never decoded. Each emit_lesson call
// mints a content-derived agent.lesson.record.{uuid5} entity that MUST be
// created with this envelope; append is must-exist and rejects an absent lesson
// entity.
func AgentLessonMessageType() message.Type {
	return message.Type{
		Domain:   Domain,
		Category: CategoryAgentLesson,
		Version:  SchemaVersion,
	}
}

// AgentLessonEntityID returns the canonical entity ID for an agent lesson
// record. The id argument is the content-derived unique identifier
// (a UUIDv5 without dots, generated by the emit_lesson tool from the lesson's
// category + scope + summary + evidence — see emit_lesson.go).
//
// Format: {org}.{platform}.agent.lesson.record.{id}
//
// Example: AgentLessonEntityID("acme", "ops", "2c5acb9b-8283-5b34-a4d1-4b1c9f8502ca")
// Returns: "acme.ops.agent.lesson.record.2c5acb9b-8283-5b34-a4d1-4b1c9f8502ca"
//
// This is a 6-part entity ID (org.platform / agent / lesson / record / id);
// the domain+system axes (agent.lesson) align the entity's identity with its
// predicate family (agent.lesson.*), exactly as ops.diagnosis.finding aligns
// with ops.diagnosis.*.
//
// Panics if any input part is empty or contains a dot, as these represent
// programming errors — the caller is responsible for supplying well-formed
// identifiers. The id must be a UUID or equivalent unique token with no dots.
func AgentLessonEntityID(org, platform, id string) string {
	if err := validatePart("org", org); err != nil {
		panic(fmt.Sprintf("AgentLessonEntityID: %s", err))
	}
	if err := validatePart("platform", platform); err != nil {
		panic(fmt.Sprintf("AgentLessonEntityID: %s", err))
	}
	if err := validatePart("id", id); err != nil {
		panic(fmt.Sprintf("AgentLessonEntityID: %s", err))
	}

	entityID := fmt.Sprintf("%s.%s.agent.lesson.record.%s", org, platform, id)

	if !message.IsValidEntityID(entityID) {
		panic(fmt.Sprintf("AgentLessonEntityID: constructed id %q failed IsValidEntityID — check input values", entityID))
	}

	return entityID
}

// AgentLessonRecordPrefix returns the 5-part entity-ID prefix shared by every
// lesson record for an org/platform: "{org}.{platform}.agent.lesson.record".
//
// It is the query prefix a reader passes to graph.ingest.query.prefix to list
// all lesson entities (the brief-assembly LessonReader uses it). Keeping the
// "agent.lesson.record" segment string here — beside AgentLessonEntityID —
// prevents it drifting from the entity-ID format. Panics on empty/dotted parts,
// as those are programming errors.
func AgentLessonRecordPrefix(org, platform string) string {
	if err := validatePart("org", org); err != nil {
		panic(fmt.Sprintf("AgentLessonRecordPrefix: %s", err))
	}
	if err := validatePart("platform", platform); err != nil {
		panic(fmt.Sprintf("AgentLessonRecordPrefix: %s", err))
	}
	return fmt.Sprintf("%s.%s.agent.lesson.record", org, platform)
}
