package agentic

import (
	"fmt"

	"github.com/c360studio/semstreams/message"
)

// CategoryOpsDiagnosis is the message category for the ops-diagnosis-finding
// entity origin contract. It names the ENTITY type born when the ops agent's
// emit_diagnosis tool records a finding in the graph — distinct from any event
// payload. Mirrors CategoryLoopExecution / CategoryModelEndpoint.
const CategoryOpsDiagnosis = "ops_diagnosis"

// OpsDiagnosisMessageType returns the message.Type for the ops-diagnosis-finding
// entity origin contract — key "agentic.ops_diagnosis.v1".
//
// Registry decision (mirrors LoopExecutionMessageType, ADR-056 typed-origin):
// MUTATION-ONLY. Stamped on CreateEntityWithTriplesRequest.Entity.MessageType
// when EmitDiagnosisExecutor births a finding entity; NEVER published as a
// BaseMessage payload, NOT registered in the payload registry, never decoded.
// Each emit_diagnosis call mints a fresh ops.diagnosis.finding.{uuid} entity
// that MUST be CREATED with this envelope, not auto-vivified by triple.add —
// graph-ingest enforces must-exist and would reject the finding's triples
// otherwise (gh#390).
func OpsDiagnosisMessageType() message.Type {
	return message.Type{
		Domain:   Domain,
		Category: CategoryOpsDiagnosis,
		Version:  SchemaVersion,
	}
}

// OpsDiagnosisEntityID returns the canonical entity ID for an ops diagnosis
// finding. The id argument is a unique per-finding identifier (e.g., a UUID
// without dots generated by the emit_diagnosis tool).
//
// Format: {org}.{platform}.ops.diagnosis.finding.{id}
//
// Example: OpsDiagnosisEntityID("acme", "ops", "550e8400-e29b-41d4-a716-446655440000")
// Returns: "acme.ops.ops.diagnosis.finding.550e8400-e29b-41d4-a716-446655440000"
//
// Panics if any input part is empty or contains a dot, as these represent
// programming errors — the caller is responsible for supplying well-formed
// identifiers. The id must be a UUID or equivalent unique token with no dots.
func OpsDiagnosisEntityID(org, platform, id string) string {
	if err := validatePart("org", org); err != nil {
		panic(fmt.Sprintf("OpsDiagnosisEntityID: %s", err))
	}
	if err := validatePart("platform", platform); err != nil {
		panic(fmt.Sprintf("OpsDiagnosisEntityID: %s", err))
	}
	if err := validatePart("id", id); err != nil {
		panic(fmt.Sprintf("OpsDiagnosisEntityID: %s", err))
	}

	entityID := fmt.Sprintf("%s.%s.ops.diagnosis.finding.%s", org, platform, id)

	if !message.IsValidEntityID(entityID) {
		panic(fmt.Sprintf("OpsDiagnosisEntityID: constructed id %q failed IsValidEntityID — check input values", entityID))
	}

	return entityID
}
