package agentic

import (
	"fmt"

	"github.com/c360studio/semstreams/message"
)

// OpsDiagnosisEntityID returns the canonical entity ID for an ops diagnosis
// finding. The id argument is a unique per-finding identifier (e.g., a UUID
// without dots generated by the emit_diagnosis tool).
//
// Format: {org}.{platform}.ops.diagnosis.finding.{id}
//
// Example: OpsDiagnosisEntityID("acme", "ops", "550e8400-e29b-41d4-a716-446655440000")
// Returns: "acme.ops.ops.diagnosis.finding.550e8400-e29b-41d4-a716-446655440000"
//
// Panics if any input part is empty or contains a dot, as these represent
// programming errors — the caller is responsible for supplying well-formed
// identifiers. The id must be a UUID or equivalent unique token with no dots.
func OpsDiagnosisEntityID(org, platform, id string) string {
	if err := validatePart("org", org); err != nil {
		panic(fmt.Sprintf("OpsDiagnosisEntityID: %s", err))
	}
	if err := validatePart("platform", platform); err != nil {
		panic(fmt.Sprintf("OpsDiagnosisEntityID: %s", err))
	}
	if err := validatePart("id", id); err != nil {
		panic(fmt.Sprintf("OpsDiagnosisEntityID: %s", err))
	}

	entityID := fmt.Sprintf("%s.%s.ops.diagnosis.finding.%s", org, platform, id)

	if !message.IsValidEntityID(entityID) {
		panic(fmt.Sprintf("OpsDiagnosisEntityID: constructed id %q failed IsValidEntityID — check input values", entityID))
	}

	return entityID
}
