// Code generated by Tester Agent. DO NOT EDIT.
// Task: agentic-tools processor unit tests (greenfield)
// Builder must make these tests pass without modification.

package agentictools_test

import (
	"context"
	"encoding/json"
	"testing"
	"time"

	"github.com/c360studio/semstreams/agentic"
	"github.com/c360studio/semstreams/component"
	"github.com/c360studio/semstreams/internal/graphmutation"
	agentictools "github.com/c360studio/semstreams/processor/agentic-tools"
)

func TestComponent_Meta(t *testing.T) {
	comp := createTestComponent(t)

	meta := comp.Meta()

	if meta.Name != "agentic-tools" {
		t.Errorf("Meta().Name = %s, want agentic-tools", meta.Name)
	}
	if meta.Type != "processor" {
		t.Errorf("Meta().Type = %s, want processor", meta.Type)
	}
	if meta.Description == "" {
		t.Error("Meta().Description should not be empty")
	}
	if meta.Version == "" {
		t.Error("Meta().Version should not be empty")
	}
}

func TestComponent_InputPorts(t *testing.T) {
	comp := createTestComponent(t)

	ports := comp.InputPorts()

	// Two communication inputs plus the two exact KV read dependencies.
	if len(ports) != 4 {
		t.Fatalf("InputPorts() count = %d, want 4", len(ports))
	}

	byName := map[string]component.Port{}
	for _, p := range ports {
		byName[p.Name] = p
	}

	exec, ok := byName["tool.execute"]
	if !ok {
		t.Fatalf("expected input port tool.execute, got %v", byName)
	}
	if exec.Direction != component.DirectionInput {
		t.Errorf("tool.execute direction = %v, want DirectionInput", exec.Direction)
	}
	if !exec.Required {
		t.Error("tool.execute should be required")
	}
	jsConfig, ok := exec.Config.(component.JetStreamPort)
	if !ok {
		t.Fatalf("tool.execute config should be JetStreamPort, got %T", exec.Config)
	}
	if len(jsConfig.Subjects) != 1 || jsConfig.Subjects[0] != "tool.execute.>" {
		t.Errorf("tool.execute subjects = %v, want [tool.execute.>]", jsConfig.Subjects)
	}
	if jsConfig.StreamName != "AGENT" {
		t.Errorf("tool.execute stream = %s, want AGENT", jsConfig.StreamName)
	}

	toolList, ok := byName["tool.list"]
	if !ok {
		t.Fatalf("expected input port tool.list for discovery request/reply, got %v", byName)
	}
	toolListFacts, err := toolList.Facts()
	if err != nil {
		t.Fatalf("tool.list facts: %v", err)
	}
	if toolList.Direction != component.DirectionInput ||
		toolListFacts.Kind() != component.PortKindNATSRequest ||
		toolListFacts.InteractionPattern() != component.PatternRequest {
		t.Errorf("tool.list resolved contract = direction %q kind %q interaction %q, want input/%q/%q",
			toolList.Direction, toolListFacts.Kind(), toolListFacts.InteractionPattern(),
			component.PortKindNATSRequest, component.PatternRequest)
	}
	if subjects := toolListFacts.NATSSubjects(); len(subjects) != 1 || subjects[0] != "discovery.tool.list" {
		t.Errorf("tool.list subjects = %v, want [discovery.tool.list]", subjects)
	}
	for name, bucket := range map[string]string{"entity_states": "ENTITY_STATES", "agent_loops": "AGENT_LOOPS"} {
		port, ok := byName[name]
		if !ok {
			t.Errorf("expected KV read input %s", name)
			continue
		}
		read, ok := port.Config.(component.KVReadPort)
		if !ok || read.Bucket != bucket {
			t.Errorf("%s config = %#v, want KVReadPort bucket %s", name, port.Config, bucket)
		}
	}
}

func TestComponent_OutputPorts(t *testing.T) {
	comp := createTestComponent(t)

	ports := comp.OutputPorts()

	if len(ports) != 2 {
		t.Fatalf("OutputPorts() count = %d, want 2", len(ports))
	}
	byName := make(map[string]component.Port, len(ports))
	for _, port := range ports {
		byName[port.Name] = port
	}
	port := byName["tool.result"]
	if port.Name != "tool.result" {
		t.Errorf("OutputPort name = %s, want tool.result", port.Name)
	}
	if port.Direction != component.DirectionOutput {
		t.Errorf("OutputPort direction = %v, want DirectionOutput", port.Direction)
	}

	// Verify JetStream config (component uses JetStream for durable messaging)
	jsConfig, ok := port.Config.(component.JetStreamPort)
	if !ok {
		t.Fatalf("OutputPort config should be JetStreamPort, got %T", port.Config)
	}
	if len(jsConfig.Subjects) != 1 || jsConfig.Subjects[0] != "tool.result.*" {
		t.Errorf("OutputPort subjects = %v, want [tool.result.*]", jsConfig.Subjects)
	}
	if jsConfig.StreamName != "AGENT" {
		t.Errorf("OutputPort stream = %s, want AGENT", jsConfig.StreamName)
	}
	mutation := byName["graph_mutations"]
	request, ok := mutation.Config.(component.NATSRequestPort)
	if !ok {
		t.Fatalf("graph_mutations config = %T, want NATSRequestPort", mutation.Config)
	}
	if !mutation.Required || request.Subject != graphmutation.SubjectFamily || request.Interface == nil ||
		request.Interface.Type != graphmutation.InterfaceType || request.Interface.Version != graphmutation.InterfaceVersion {
		t.Fatalf("graph_mutations contract drift: %#v", mutation)
	}
}

func TestComponent_ConfigSchema(t *testing.T) {
	comp := createTestComponent(t)

	schema := comp.ConfigSchema()

	// ConfigSchema has Properties and Required fields (no Type field)
	if len(schema.Properties) == 0 {
		t.Error("ConfigSchema().Properties should not be empty")
	}

	// Verify timeout property exists
	timeoutProp, ok := schema.Properties["timeout"]
	if !ok {
		t.Fatal("ConfigSchema() should have 'timeout' property")
	}
	if timeoutProp.Type != "string" {
		t.Errorf("timeout property type = %s, want string", timeoutProp.Type)
	}

	// Verify allowed_tools property exists
	allowedToolsProp, ok := schema.Properties["allowed_tools"]
	if !ok {
		t.Fatal("ConfigSchema() should have 'allowed_tools' property")
	}
	if allowedToolsProp.Type != "array" {
		t.Errorf("allowed_tools property type = %s, want array", allowedToolsProp.Type)
	}
}

func TestComponent_Health_NotStarted(t *testing.T) {
	comp := createTestComponent(t)

	health := comp.Health()

	if health.Healthy {
		t.Error("Health() should be unhealthy before Start()")
	}
}

func TestNewComponent_ValidConfig(t *testing.T) {
	config := agentictools.Config{
		Ports: &component.PortConfig{
			Inputs: []component.PortDefinition{
				{Name: "tool.execute", Config: component.JetStreamPort{StreamName: "AGENT", Subjects: []string{"custom.tool.execute.>"}}, Required: true},
			},
			Outputs: []component.PortDefinition{
				{Name: "tool.result", Config: component.JetStreamPort{StreamName: "AGENT", Subjects: []string{"custom.tool.result.*"}}, Required: true},
			},
		},
		Timeout:      "60s",
		AllowedTools: []string{"graph_query", "file_read"},
	}

	rawConfig, err := json.Marshal(config)
	if err != nil {
		t.Fatalf("Marshal config failed: %v", err)
	}

	deps := component.Dependencies{
		NATSClient: nil, // Unit test doesn't need real NATS
	}

	comp, err := agentictools.NewComponent(rawConfig, deps)
	if err != nil {
		t.Fatalf("NewComponent() failed: %v", err)
	}
	if comp == nil {
		t.Fatal("NewComponent() returned nil component")
	}
}

func TestNewComponent_MissingNATSClient(t *testing.T) {
	config := agentictools.DefaultConfig()
	config.AllowedTools = []string{"graph_query"}

	rawConfig, err := json.Marshal(config)
	if err != nil {
		t.Fatalf("Marshal config failed: %v", err)
	}

	deps := component.Dependencies{
		NATSClient: nil,
	}

	// Component creation should succeed even without NATS client
	// (error happens on Start, not creation)
	comp, err := agentictools.NewComponent(rawConfig, deps)
	if err != nil {
		t.Fatalf("NewComponent() should succeed without NATS client, got error: %v", err)
	}
	if comp == nil {
		t.Fatal("NewComponent() returned nil component")
	}
}

func TestNewComponent_InvalidConfigJSON(t *testing.T) {
	rawConfig := []byte(`{invalid json}`)

	deps := component.Dependencies{
		NATSClient: nil,
	}

	comp, err := agentictools.NewComponent(rawConfig, deps)
	if err == nil {
		t.Fatal("NewComponent() should fail with invalid JSON")
	}
	if comp != nil {
		t.Error("NewComponent() should return nil on error")
	}
}

func TestNewComponent_InvalidTimeout(t *testing.T) {
	config := agentictools.DefaultConfig()
	config.Timeout = "invalid"

	rawConfig, err := json.Marshal(config)
	if err != nil {
		t.Fatalf("Marshal config failed: %v", err)
	}

	deps := component.Dependencies{
		NATSClient: nil,
	}

	comp, err := agentictools.NewComponent(rawConfig, deps)
	if err == nil {
		t.Fatal("NewComponent() should fail with invalid timeout")
	}
	if comp != nil {
		t.Error("NewComponent() should return nil on error")
	}
}

func TestComponent_RegisterToolExecutor(t *testing.T) {
	comp := createTestComponent(t)

	// Component should have RegisterToolExecutor method
	registrar, ok := comp.(interface {
		RegisterToolExecutor(executor agentictools.ToolExecutor) error
	})
	if !ok {
		t.Fatal("Component should implement RegisterToolExecutor method")
	}

	// Register a tool executor
	executor := &mockToolExecutor{
		name: "test_tool",
		listToolsFunc: func() []agentic.ToolDefinition {
			return []agentic.ToolDefinition{
				{
					Name:        "test_tool",
					Description: "Test tool",
					Parameters: map[string]any{
						"type": "object",
					},
				},
			}
		},
	}

	err := registrar.RegisterToolExecutor(executor)
	if err != nil {
		t.Fatalf("RegisterToolExecutor() failed: %v", err)
	}
}

func TestComponent_RegisterToolExecutor_Multiple(t *testing.T) {
	comp := createTestComponent(t)

	registrar, ok := comp.(interface {
		RegisterToolExecutor(executor agentictools.ToolExecutor) error
	})
	if !ok {
		t.Fatal("Component should implement RegisterToolExecutor method")
	}

	// Register multiple tool executors
	tools := []string{"graph_query", "file_read", "file_write"}
	for _, toolName := range tools {
		executor := &mockToolExecutor{
			name: toolName,
			listToolsFunc: func() []agentic.ToolDefinition {
				return []agentic.ToolDefinition{
					{
						Name:        toolName,
						Description: "Test tool: " + toolName,
						Parameters: map[string]any{
							"type": "object",
						},
					},
				}
			},
		}

		if err := registrar.RegisterToolExecutor(executor); err != nil {
			t.Fatalf("RegisterToolExecutor(%s) failed: %v", toolName, err)
		}
	}
}

func TestComponent_RegisterToolExecutor_Duplicate(t *testing.T) {
	comp := createTestComponent(t)

	registrar, ok := comp.(interface {
		RegisterToolExecutor(executor agentictools.ToolExecutor) error
	})
	if !ok {
		t.Fatal("Component should implement RegisterToolExecutor method")
	}

	executor := &mockToolExecutor{
		name: "test_tool",
		listToolsFunc: func() []agentic.ToolDefinition {
			return []agentic.ToolDefinition{
				{
					Name:        "test_tool",
					Description: "Test tool",
					Parameters: map[string]any{
						"type": "object",
					},
				},
			}
		},
	}

	// First registration should succeed
	if err := registrar.RegisterToolExecutor(executor); err != nil {
		t.Fatalf("First RegisterToolExecutor() should succeed, got error: %v", err)
	}

	// Second registration with same tool name should fail
	if err := registrar.RegisterToolExecutor(executor); err == nil {
		t.Fatal("RegisterToolExecutor() with duplicate tool should return error")
	}
}

func TestComponent_ListRegisteredTools(t *testing.T) {
	comp := createTestComponent(t)

	// Component should have ListTools method
	lister, ok := comp.(interface {
		ListTools() []agentictools.ToolDefinition
	})
	if !ok {
		t.Fatal("Component should implement ListTools method")
	}

	registrar, ok := comp.(interface {
		RegisterToolExecutor(executor agentictools.ToolExecutor) error
	})
	if !ok {
		t.Fatal("Component should implement RegisterToolExecutor method")
	}

	// Initially no tools
	tools := lister.ListTools()
	if len(tools) != 0 {
		t.Errorf("ListTools() on new component should return empty list, got %d tools", len(tools))
	}

	// Register some tools
	toolNames := []string{"graph_query", "file_read"}
	for _, name := range toolNames {
		executor := &mockToolExecutor{
			name: name,
			listToolsFunc: func() []agentic.ToolDefinition {
				return []agentic.ToolDefinition{
					{
						Name:        name,
						Description: "Tool: " + name,
						Parameters: map[string]any{
							"type": "object",
						},
					},
				}
			},
		}
		if err := registrar.RegisterToolExecutor(executor); err != nil {
			t.Fatalf("RegisterToolExecutor(%s) failed: %v", name, err)
		}
	}

	// List should now include registered tools
	tools = lister.ListTools()
	if len(tools) != len(toolNames) {
		t.Errorf("ListTools() count = %d, want %d", len(tools), len(toolNames))
	}

	// Verify internal tools have correct provider and availability
	for _, tool := range tools {
		if tool.Provider != "internal" {
			t.Errorf("Internal tool %s should have Provider='internal', got %s", tool.Name, tool.Provider)
		}
		if !tool.Available {
			t.Errorf("Internal tool %s should have Available=true", tool.Name)
		}
	}
}

func TestComponent_ToolExecutionWithAllowedList(t *testing.T) {
	config := agentictools.DefaultConfig()
	config.AllowedTools = []string{"graph_query", "file_read"}

	rawConfig, err := json.Marshal(config)
	if err != nil {
		t.Fatalf("Marshal config failed: %v", err)
	}

	deps := component.Dependencies{
		NATSClient: nil,
	}

	comp, err := agentictools.NewComponent(rawConfig, deps)
	if err != nil {
		t.Fatalf("NewComponent() failed: %v", err)
	}

	registrar, ok := comp.(interface {
		RegisterToolExecutor(executor agentictools.ToolExecutor) error
	})
	if !ok {
		t.Fatal("Component should implement RegisterToolExecutor method")
	}

	executor, ok := comp.(interface {
		Execute(ctx context.Context, call agentic.ToolCall) (agentic.ToolResult, error)
	})
	if !ok {
		t.Fatal("Component should implement Execute method")
	}

	// Register allowed tool
	allowedExecutor := &mockToolExecutor{
		name:          "graph_query",
		returnContent: "allowed result",
	}
	if err := registrar.RegisterToolExecutor(allowedExecutor); err != nil {
		t.Fatalf("RegisterToolExecutor() failed: %v", err)
	}

	// Register disallowed tool
	disallowedExecutor := &mockToolExecutor{
		name:          "file_delete",
		returnContent: "should not execute",
	}
	if err := registrar.RegisterToolExecutor(disallowedExecutor); err != nil {
		t.Fatalf("RegisterToolExecutor() failed: %v", err)
	}

	ctx := context.Background()

	// Execute allowed tool - should succeed
	allowedCall := agentic.ToolCall{
		ID:   "call-1",
		Name: "graph_query",
	}
	result, err := executor.Execute(ctx, allowedCall)
	if err != nil {
		t.Errorf("Execute() with allowed tool should succeed, got error: %v", err)
	}
	if result.Content != "allowed result" {
		t.Errorf("Result.Content = %s, want 'allowed result'", result.Content)
	}

	// Execute disallowed tool - should fail
	disallowedCall := agentic.ToolCall{
		ID:   "call-2",
		Name: "file_delete",
	}
	result, err = executor.Execute(ctx, disallowedCall)
	if err == nil {
		t.Error("Execute() with disallowed tool should return error")
	}
	if result.Error == "" {
		t.Error("Result.Error should not be empty for disallowed tool")
	}
	if result.ErrorKind != agentic.ToolErrorNotFound {
		t.Errorf("Result.ErrorKind = %q, want %q for disallowed tool", result.ErrorKind, agentic.ToolErrorNotFound)
	}
}

func TestComponent_EmptyAllowedList_AllowsAll(t *testing.T) {
	config := agentictools.DefaultConfig()
	config.AllowedTools = nil // nil or empty should allow all tools

	rawConfig, err := json.Marshal(config)
	if err != nil {
		t.Fatalf("Marshal config failed: %v", err)
	}

	deps := component.Dependencies{
		NATSClient: nil,
	}

	comp, err := agentictools.NewComponent(rawConfig, deps)
	if err != nil {
		t.Fatalf("NewComponent() failed: %v", err)
	}

	registrar, ok := comp.(interface {
		RegisterToolExecutor(executor agentictools.ToolExecutor) error
	})
	if !ok {
		t.Fatal("Component should implement RegisterToolExecutor method")
	}

	executor, ok := comp.(interface {
		Execute(ctx context.Context, call agentic.ToolCall) (agentic.ToolResult, error)
	})
	if !ok {
		t.Fatal("Component should implement Execute method")
	}

	// Register any tool
	anyExecutor := &mockToolExecutor{
		name:          "any_tool",
		returnContent: "result",
	}
	if err := registrar.RegisterToolExecutor(anyExecutor); err != nil {
		t.Fatalf("RegisterToolExecutor() failed: %v", err)
	}

	ctx := context.Background()
	call := agentic.ToolCall{
		ID:   "call-1",
		Name: "any_tool",
	}

	// Should succeed with nil/empty allowed list (allows all)
	result, err := executor.Execute(ctx, call)
	if err != nil {
		t.Errorf("Execute() with empty allowed list should succeed, got error: %v", err)
	}
	if result.Content != "result" {
		t.Errorf("Result.Content = %s, want 'result'", result.Content)
	}
}

// TestComponent_Execute_ParentCancellationClassifiedAsTimeout verifies that
// when the caller cancels the parent context mid-flight, the tool result is
// tagged Timeout (cancellation is treated as a timeout for classification
// purposes — the ops agent wants to know "didn't finish in time" either way).
func TestComponent_Execute_ParentCancellationClassifiedAsTimeout(t *testing.T) {
	config := agentictools.DefaultConfig()
	config.Timeout = "10s" // Long enough that the inner timeout won't fire.

	rawConfig, err := json.Marshal(config)
	if err != nil {
		t.Fatalf("Marshal config failed: %v", err)
	}

	comp, err := agentictools.NewComponent(rawConfig, component.Dependencies{NATSClient: nil})
	if err != nil {
		t.Fatalf("NewComponent() failed: %v", err)
	}

	registrar := comp.(interface {
		RegisterToolExecutor(executor agentictools.ToolExecutor) error
	})
	executor := comp.(interface {
		Execute(ctx context.Context, call agentic.ToolCall) (agentic.ToolResult, error)
	})

	slow := &mockToolExecutor{name: "slow_tool", delay: 2 * time.Second}
	if err := registrar.RegisterToolExecutor(slow); err != nil {
		t.Fatalf("RegisterToolExecutor() failed: %v", err)
	}

	ctx, cancel := context.WithCancel(context.Background())
	go func() {
		time.Sleep(50 * time.Millisecond)
		cancel()
	}()

	result, err := executor.Execute(ctx, agentic.ToolCall{
		ID:   "call-cancel",
		Name: "slow_tool",
	})
	if err == nil {
		t.Fatal("expected a cancellation error, got nil")
	}
	if result.ErrorKind != agentic.ToolErrorTimeout {
		t.Errorf("Result.ErrorKind = %q, want %q", result.ErrorKind, agentic.ToolErrorTimeout)
	}
}

// TestComponent_Execute_TimeoutClassifiedAsTimeout verifies that when the
// configured per-call timeout fires, the returned ToolResult is tagged with
// ErrorKind == ToolErrorTimeout so downstream graph writers emit the correct
// agent.step.error_category predicate.
func TestComponent_Execute_TimeoutClassifiedAsTimeout(t *testing.T) {
	config := agentictools.DefaultConfig()
	config.Timeout = "50ms"

	rawConfig, err := json.Marshal(config)
	if err != nil {
		t.Fatalf("Marshal config failed: %v", err)
	}

	comp, err := agentictools.NewComponent(rawConfig, component.Dependencies{NATSClient: nil})
	if err != nil {
		t.Fatalf("NewComponent() failed: %v", err)
	}

	registrar := comp.(interface {
		RegisterToolExecutor(executor agentictools.ToolExecutor) error
	})
	executor := comp.(interface {
		Execute(ctx context.Context, call agentic.ToolCall) (agentic.ToolResult, error)
	})

	// Mock tool that blocks longer than the configured timeout.
	slow := &mockToolExecutor{name: "slow_tool", delay: 500 * time.Millisecond}
	if err := registrar.RegisterToolExecutor(slow); err != nil {
		t.Fatalf("RegisterToolExecutor() failed: %v", err)
	}

	result, err := executor.Execute(context.Background(), agentic.ToolCall{
		ID:   "call-timeout",
		Name: "slow_tool",
	})
	if err == nil {
		t.Fatal("expected a timeout error, got nil")
	}
	if result.ErrorKind != agentic.ToolErrorTimeout {
		t.Errorf("Result.ErrorKind = %q, want %q", result.ErrorKind, agentic.ToolErrorTimeout)
	}
}

// createTestComponent creates a minimal component for testing
func createTestComponent(t *testing.T) component.Discoverable {
	config := agentictools.DefaultConfig()

	rawConfig, err := json.Marshal(config)
	if err != nil {
		t.Fatalf("Marshal config failed: %v", err)
	}

	deps := component.Dependencies{
		NATSClient: nil,
	}

	comp, err := agentictools.NewComponent(rawConfig, deps)
	if err != nil {
		t.Fatalf("NewComponent() failed: %v", err)
	}

	return comp
}
