// Code generated by Tester Agent. DO NOT EDIT.
// Task: agentic-tools processor unit tests (greenfield)
// Builder must make these tests pass without modification.

package agentictools_test

import (
	"encoding/json"
	"testing"

	"github.com/c360studio/semstreams/component"
	agentictools "github.com/c360studio/semstreams/processor/agentic-tools"
)

func TestConfig_JSONSerialization(t *testing.T) {
	tests := []struct {
		name   string
		config agentictools.Config
	}{
		{
			name: "minimal config",
			config: agentictools.Config{
				Timeout: "60s",
			},
		},
		{
			name: "config with allowed tools",
			config: agentictools.Config{
				Timeout:      "90s",
				AllowedTools: []string{"graph_query", "file_read", "file_write"},
			},
		},
		{
			name: "config with empty allowed tools",
			config: agentictools.Config{
				Timeout:      "30s",
				AllowedTools: []string{},
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			// Marshal
			data, err := json.Marshal(tt.config)
			if err != nil {
				t.Fatalf("Marshal() error = %v", err)
			}

			// Unmarshal
			var decoded agentictools.Config
			if err := json.Unmarshal(data, &decoded); err != nil {
				t.Fatalf("Unmarshal() error = %v", err)
			}

			// Verify round-trip
			if decoded.Timeout != tt.config.Timeout {
				t.Errorf("Timeout = %v, want %v", decoded.Timeout, tt.config.Timeout)
			}

			if len(decoded.AllowedTools) != len(tt.config.AllowedTools) {
				t.Errorf("AllowedTools length = %d, want %d", len(decoded.AllowedTools), len(tt.config.AllowedTools))
			}
		})
	}
}

func TestConfig_Validate(t *testing.T) {
	tests := []struct {
		name    string
		config  agentictools.Config
		wantErr bool
		errMsg  string
	}{
		{
			name: "valid minimal config",
			config: agentictools.Config{
				Timeout: "60s",
			},
			wantErr: false,
		},
		{
			name: "valid with allowed tools",
			config: agentictools.Config{
				Timeout:      "90s",
				AllowedTools: []string{"graph_query", "file_read"},
			},
			wantErr: false,
		},
		{
			name: "empty timeout",
			config: agentictools.Config{
				Timeout: "",
			},
			wantErr: true,
			errMsg:  "timeout",
		},
		{
			name: "invalid timeout format",
			config: agentictools.Config{
				Timeout: "not-a-duration",
			},
			wantErr: true,
			errMsg:  "timeout",
		},
		{
			name: "negative timeout",
			config: agentictools.Config{
				Timeout: "-5s",
			},
			wantErr: true,
			errMsg:  "timeout",
		},
		{
			name: "zero timeout",
			config: agentictools.Config{
				Timeout: "0s",
			},
			wantErr: true,
			errMsg:  "timeout",
		},
		{
			name: "valid edge case timeout (1ms)",
			config: agentictools.Config{
				Timeout: "1ms",
			},
			wantErr: false,
		},
		{
			name: "valid long timeout",
			config: agentictools.Config{
				Timeout: "10m",
			},
			wantErr: false,
		},
		{
			name: "allowed tools can be nil",
			config: agentictools.Config{
				Timeout:      "60s",
				AllowedTools: nil,
			},
			wantErr: false,
		},
		{
			name: "allowed tools can be empty",
			config: agentictools.Config{
				Timeout:      "60s",
				AllowedTools: []string{},
			},
			wantErr: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			err := tt.config.Validate()
			if (err != nil) != tt.wantErr {
				t.Errorf("Validate() error = %v, wantErr %v", err, tt.wantErr)
				return
			}
			if tt.wantErr && err != nil && tt.errMsg != "" {
				if !containsIgnoreCase(err.Error(), tt.errMsg) {
					t.Errorf("Validate() error = %v, expected to contain %q", err, tt.errMsg)
				}
			}
		})
	}
}

func TestDefaultConfig(t *testing.T) {
	cfg := agentictools.DefaultConfig()

	// Verify default timeout
	if cfg.Timeout != "60s" {
		t.Errorf("DefaultConfig() timeout = %s, want 60s", cfg.Timeout)
	}

	// Verify ports are configured
	if cfg.Ports == nil {
		t.Fatal("DefaultConfig() ports should not be nil")
	}

	// Two communication inputs plus ENTITY_STATES and AGENT_LOOPS exact reads.
	if len(cfg.Ports.Inputs) != 4 {
		t.Errorf("DefaultConfig() input ports count = %d, want 4", len(cfg.Ports.Inputs))
	}
	if len(cfg.Ports.Outputs) != 2 {
		t.Errorf("DefaultConfig() output ports count = %d, want 2", len(cfg.Ports.Outputs))
	}

	ins := map[string]string{}
	for _, p := range cfg.Ports.Inputs {
		resolved, err := p.Resolve(component.DirectionInput)
		if err != nil {
			t.Fatalf("resolve input %s: %v", p.Name, err)
		}
		facts, err := resolved.Facts()
		if err != nil {
			t.Fatalf("facts input %s: %v", p.Name, err)
		}
		if subjects := facts.NATSSubjects(); len(subjects) == 1 {
			ins[p.Name] = subjects[0]
		}
		if p.Name == "tool.list" {
			if resolved.Direction != component.DirectionInput {
				t.Errorf("tool.list direction = %q, want input", resolved.Direction)
			}
			if facts.Kind() != component.PortKindNATSRequest {
				t.Errorf("tool.list kind = %q, want %q", facts.Kind(), component.PortKindNATSRequest)
			}
			if facts.InteractionPattern() != component.PatternRequest {
				t.Errorf("tool.list interaction = %q, want %q", facts.InteractionPattern(), component.PatternRequest)
			}
			if _, ok := p.Config.(component.NATSRequestPort); !ok {
				t.Errorf("tool.list config = %T, want NATSRequestPort", p.Config)
			}
		}
	}
	if ins["tool.execute"] != "tool.execute.>" {
		t.Errorf("tool.execute input subject = %q, want tool.execute.>", ins["tool.execute"])
	}
	if ins["tool.list"] != "discovery.tool.list" {
		t.Errorf("tool.list input subject = %q, want discovery.tool.list", ins["tool.list"])
	}
	for name, bucket := range map[string]string{"entity_states": "ENTITY_STATES", "agent_loops": "AGENT_LOOPS"} {
		for _, port := range cfg.Ports.Inputs {
			if port.Name != name {
				continue
			}
			read, ok := port.Config.(component.KVReadPort)
			if !ok || read.Bucket != bucket {
				t.Errorf("%s config = %#v, want KVReadPort bucket %s", name, port.Config, bucket)
			}
		}
	}

	outputs := map[string]string{}
	for _, port := range cfg.Ports.Outputs {
		resolved, err := port.Resolve(component.DirectionOutput)
		if err != nil {
			t.Fatalf("resolve output %s: %v", port.Name, err)
		}
		facts, err := resolved.Facts()
		if err != nil {
			t.Fatalf("facts output %s: %v", port.Name, err)
		}
		outputs[port.Name] = facts.NATSSubjects()[0]
	}
	if outputs["tool.result"] != "tool.result.*" {
		t.Errorf("tool.result output subject = %q, want tool.result.*", outputs["tool.result"])
	}
	if outputs["graph_mutations"] != "graph.mutation.>" {
		t.Errorf("graph_mutations output subject = %q, want graph.mutation.>", outputs["graph_mutations"])
	}
	for _, port := range cfg.Ports.Outputs {
		request, ok := port.Config.(component.NATSRequestPort)
		if port.Name == "graph_mutations" &&
			(!ok || request.Interface == nil || request.Interface.Type != "semstreams.graph.mutation" || !port.Required) {
			t.Errorf("graph_mutations output is not the required typed request port: %#v", port)
		}
	}

	// Verify allowed tools is initialized (can be nil or empty, both valid)
	// No assertion needed, just ensure no panic

	// Verify default config is valid
	if err := cfg.Validate(); err != nil {
		t.Errorf("DefaultConfig() should be valid, got error: %v", err)
	}
}

func TestConfig_TimeoutParsing(t *testing.T) {
	tests := []struct {
		name      string
		timeout   string
		wantValid bool
	}{
		{"seconds", "30s", true},
		{"minutes", "5m", true},
		{"hours", "1h", true},
		{"milliseconds", "500ms", true},
		{"microseconds", "100us", true},
		{"combined", "1h30m", true},
		{"invalid format", "30", false},
		{"invalid unit", "30x", false},
		{"empty", "", false},
		{"whitespace", "  ", false},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			config := agentictools.Config{
				Timeout: tt.timeout,
			}

			err := config.Validate()
			isValid := err == nil

			if isValid != tt.wantValid {
				t.Errorf("Validate() with timeout=%q: valid=%v, want %v", tt.timeout, isValid, tt.wantValid)
			}
		})
	}
}

// Helper functions

func containsIgnoreCase(s, substr string) bool {
	s = toLower(s)
	substr = toLower(substr)
	return contains(s, substr)
}

func toLower(s string) string {
	result := make([]byte, len(s))
	for i := 0; i < len(s); i++ {
		c := s[i]
		if c >= 'A' && c <= 'Z' {
			c += 'a' - 'A'
		}
		result[i] = c
	}
	return string(result)
}

func contains(s, substr string) bool {
	if len(substr) == 0 {
		return true
	}
	if len(s) < len(substr) {
		return false
	}
	for i := 0; i <= len(s)-len(substr); i++ {
		if s[i:i+len(substr)] == substr {
			return true
		}
	}
	return false
}
