// Code generated by Tester Agent. DO NOT EDIT.
// Task: agentic-tools processor unit tests (greenfield)
// Builder must make these tests pass without modification.

package agentictools_test

import (
	"context"
	"errors"
	"testing"
	"time"

	"github.com/c360studio/semstreams/agentic"
	agentictools "github.com/c360studio/semstreams/processor/agentic-tools"
)

// Mock tool executor for testing
type mockToolExecutor struct {
	name          string
	shouldError   bool
	delay         time.Duration
	returnContent string
	listToolsFunc func() []agentic.ToolDefinition
}

func (m *mockToolExecutor) Execute(ctx context.Context, call agentic.ToolCall) (agentic.ToolResult, error) {
	if m.delay > 0 {
		select {
		case <-time.After(m.delay):
		case <-ctx.Done():
			return agentic.ToolResult{
				CallID: call.ID,
				Error:  "context cancelled",
			}, ctx.Err()
		}
	}

	if m.shouldError {
		return agentic.ToolResult{
			CallID: call.ID,
			Error:  "mock error",
		}, errors.New("mock error")
	}

	content := m.returnContent
	if content == "" {
		content = "mock result"
	}

	return agentic.ToolResult{
		CallID:  call.ID,
		Content: content,
	}, nil
}

func (m *mockToolExecutor) ListTools() []agentic.ToolDefinition {
	if m.listToolsFunc != nil {
		return m.listToolsFunc()
	}
	return []agentic.ToolDefinition{
		{
			Name:        m.name,
			Description: "Mock tool",
			Parameters: map[string]any{
				"type": "object",
			},
		},
	}
}

func TestExecutorRegistry_RegisterTool(t *testing.T) {
	tests := []struct {
		name     string
		toolName string
		executor agentictools.ToolExecutor
		wantErr  bool
	}{
		{
			name:     "register valid tool",
			toolName: "graph_query",
			executor: &mockToolExecutor{name: "graph_query"},
			wantErr:  false,
		},
		{
			name:     "register another valid tool",
			toolName: "file_read",
			executor: &mockToolExecutor{name: "file_read"},
			wantErr:  false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			registry := agentictools.NewExecutorRegistry()

			err := registry.RegisterTool(tt.toolName, tt.executor)
			if (err != nil) != tt.wantErr {
				t.Errorf("RegisterTool() error = %v, wantErr %v", err, tt.wantErr)
			}
		})
	}
}

func TestExecutorRegistry_RegisterTool_Duplicate(t *testing.T) {
	registry := agentictools.NewExecutorRegistry()

	executor := &mockToolExecutor{name: "graph_query"}

	// First registration should succeed
	err := registry.RegisterTool("graph_query", executor)
	if err != nil {
		t.Fatalf("First RegisterTool() should succeed, got error: %v", err)
	}

	// Second registration with same name should fail
	err = registry.RegisterTool("graph_query", executor)
	if err == nil {
		t.Fatal("RegisterTool() with duplicate name should return error")
	}

	if !containsIgnoreCase(err.Error(), "already") && !containsIgnoreCase(err.Error(), "duplicate") {
		t.Errorf("Error should mention duplicate/already registered, got: %v", err)
	}
}

func TestExecutorRegistry_GetTool(t *testing.T) {
	registry := agentictools.NewExecutorRegistry()

	executor := &mockToolExecutor{name: "graph_query"}
	err := registry.RegisterTool("graph_query", executor)
	if err != nil {
		t.Fatalf("RegisterTool() failed: %v", err)
	}

	tests := []struct {
		name     string
		toolName string
		wantNil  bool
	}{
		{
			name:     "get registered tool",
			toolName: "graph_query",
			wantNil:  false,
		},
		{
			name:     "get unregistered tool",
			toolName: "unknown_tool",
			wantNil:  true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := registry.GetTool(tt.toolName)
			if (result == nil) != tt.wantNil {
				t.Errorf("GetTool() = %v, wantNil %v", result, tt.wantNil)
			}
		})
	}
}

func TestExecutorRegistry_ListTools(t *testing.T) {
	registry := agentictools.NewExecutorRegistry()

	// Register multiple tools
	tools := []struct {
		name string
		desc string
	}{
		{"graph_query", "Query the knowledge graph"},
		{"file_read", "Read a file"},
		{"file_write", "Write a file"},
	}

	for _, tool := range tools {
		executor := &mockToolExecutor{
			name: tool.name,
			listToolsFunc: func() []agentic.ToolDefinition {
				return []agentic.ToolDefinition{
					{
						Name:        tool.name,
						Description: tool.desc,
						Parameters: map[string]any{
							"type": "object",
						},
					},
				}
			},
		}
		if err := registry.RegisterTool(tool.name, executor); err != nil {
			t.Fatalf("RegisterTool(%s) failed: %v", tool.name, err)
		}
	}

	// List all tools
	allTools := registry.ListTools()

	if len(allTools) != len(tools) {
		t.Errorf("ListTools() count = %d, want %d", len(allTools), len(tools))
	}

	// Verify all tools are present
	toolMap := make(map[string]agentic.ToolDefinition)
	for _, tool := range allTools {
		toolMap[tool.Name] = tool
	}

	for _, expected := range tools {
		tool, ok := toolMap[expected.name]
		if !ok {
			t.Errorf("ListTools() missing tool %q", expected.name)
			continue
		}
		if tool.Description != expected.desc {
			t.Errorf("Tool %q description = %q, want %q", expected.name, tool.Description, expected.desc)
		}
	}
}

// TestExecutorRegistry_ListTools_DedupesAcrossEntries reproduces the
// duplicate-advertise bug surfaced by semspec against beta.34: a multi-tool
// executor registered under each of its tool names via RegisterTool-in-loop
// caused ListTools() to emit N×N entries (one full ListTools() set per
// registered key). Anthropic's API rejects duplicate tool names with 400.
//
// The fix: ListTools() dedups by Name. Five entries pointing at one
// executor whose ListTools() returns five definitions should yield five
// unique definitions, not 25.
func TestExecutorRegistry_ListTools_DedupesAcrossEntries(t *testing.T) {
	registry := agentictools.NewExecutorRegistry()

	multiToolDefs := []agentic.ToolDefinition{
		{Name: "create_rule", Description: "create"},
		{Name: "update_rule", Description: "update"},
		{Name: "delete_rule", Description: "delete"},
		{Name: "list_rules", Description: "list"},
		{Name: "get_rule", Description: "get"},
	}
	executor := &mockToolExecutor{
		listToolsFunc: func() []agentic.ToolDefinition { return multiToolDefs },
	}

	// Pattern A: register the same executor under each of its tool names
	// (the broken-but-still-shipping shape from beta.33's register_rules.go).
	for _, def := range multiToolDefs {
		if err := registry.RegisterTool(def.Name, executor); err != nil {
			t.Fatalf("RegisterTool(%s) failed: %v", def.Name, err)
		}
	}

	got := registry.ListTools()
	if len(got) != len(multiToolDefs) {
		t.Fatalf("ListTools() returned %d defs, want %d (one per unique tool name) — duplicates would explode this to %d",
			len(got), len(multiToolDefs), len(multiToolDefs)*len(multiToolDefs))
	}

	seen := map[string]bool{}
	for _, def := range got {
		if seen[def.Name] {
			t.Errorf("ListTools() returned duplicate %q", def.Name)
		}
		seen[def.Name] = true
	}
}

// TestExecutorRegistry_RegisterExecutor_AllNamesDispatch reproduces the
// dispatch-gap bug surfaced by semspec against beta.34: a multi-tool
// executor registered under one canonical name (Pattern B from
// register_graph_query.go) advertised all five tool defs but the registry
// only knew the canonical name. The other four tools 400-not-found at
// dispatch despite being advertised.
//
// The fix: RegisterExecutor maps each ListTools() entry's Name to the
// executor, so dispatch resolves any of the five names.
func TestExecutorRegistry_RegisterExecutor_AllNamesDispatch(t *testing.T) {
	registry := agentictools.NewExecutorRegistry()

	multiToolDefs := []agentic.ToolDefinition{
		{Name: "query_entity", Description: "single"},
		{Name: "query_entities", Description: "batch"},
		{Name: "query_relationships", Description: "rels"},
		{Name: "query_neighbors", Description: "hops"},
		{Name: "query_by_type", Description: "by-type"},
	}
	executor := &mockToolExecutor{
		listToolsFunc: func() []agentic.ToolDefinition { return multiToolDefs },
		returnContent: "ok",
	}

	if err := registry.RegisterExecutor(executor); err != nil {
		t.Fatalf("RegisterExecutor() failed: %v", err)
	}

	// Every advertised name must dispatch — no ErrToolNotFound.
	for _, def := range multiToolDefs {
		ctx := context.Background()
		result, err := registry.Execute(ctx, agentic.ToolCall{
			ID:   "call-1",
			Name: def.Name,
		})
		if err != nil {
			t.Errorf("Execute(%s) returned err = %v, want nil", def.Name, err)
		}
		if result.Error != "" {
			t.Errorf("Execute(%s) result.Error = %q, want empty", def.Name, result.Error)
		}
	}

	// And ListTools() emits exactly the five advertised defs (set equality,
	// not just count — guards against a regression where dispatch works but
	// ListTools silently drops or renames a tool).
	got := registry.ListTools()
	if len(got) != len(multiToolDefs) {
		t.Errorf("ListTools() count = %d, want %d", len(got), len(multiToolDefs))
	}
	gotNames := map[string]bool{}
	for _, def := range got {
		gotNames[def.Name] = true
	}
	for _, expected := range multiToolDefs {
		if !gotNames[expected.Name] {
			t.Errorf("ListTools() missing %q", expected.Name)
		}
	}
}

func TestExecutorRegistry_RegisterExecutor_ValidationFailures(t *testing.T) {
	t.Run("nil executor", func(t *testing.T) {
		registry := agentictools.NewExecutorRegistry()
		if err := registry.RegisterExecutor(nil); err == nil {
			t.Error("RegisterExecutor(nil) returned nil, want error")
		}
	})

	t.Run("empty ListTools", func(t *testing.T) {
		registry := agentictools.NewExecutorRegistry()
		executor := &mockToolExecutor{
			listToolsFunc: func() []agentic.ToolDefinition { return nil },
		}
		if err := registry.RegisterExecutor(executor); err == nil {
			t.Error("RegisterExecutor(empty) returned nil, want error")
		}
	})

	t.Run("empty tool Name in defs", func(t *testing.T) {
		registry := agentictools.NewExecutorRegistry()
		executor := &mockToolExecutor{
			listToolsFunc: func() []agentic.ToolDefinition {
				return []agentic.ToolDefinition{{Name: ""}}
			},
		}
		if err := registry.RegisterExecutor(executor); err == nil {
			t.Error("RegisterExecutor with empty-name def returned nil, want error")
		}
	})

	t.Run("name collision at index 1 rolls back atomically", func(t *testing.T) {
		registry := agentictools.NewExecutorRegistry()
		// Pre-occupy "tool_b" so the second registration's second name collides.
		preExisting := &mockToolExecutor{name: "tool_b", returnContent: "pre"}
		if err := registry.RegisterTool("tool_b", preExisting); err != nil {
			t.Fatalf("seed RegisterTool: %v", err)
		}

		newExecutor := &mockToolExecutor{
			listToolsFunc: func() []agentic.ToolDefinition {
				return []agentic.ToolDefinition{
					{Name: "tool_a"},
					{Name: "tool_b"}, // collides
					{Name: "tool_c"},
				}
			},
		}
		if err := registry.RegisterExecutor(newExecutor); err == nil {
			t.Fatal("RegisterExecutor with colliding name returned nil, want error")
		}

		// Atomicity: tool_a and tool_c MUST NOT have been committed.
		// Only the pre-existing tool_b survives.
		if registry.GetTool("tool_a") != nil {
			t.Error("partial commit: tool_a was registered despite later collision")
		}
		if registry.GetTool("tool_c") != nil {
			t.Error("partial commit: tool_c was registered despite earlier collision in defs")
		}
	})

	t.Run("name collision at index 0 commits nothing", func(t *testing.T) {
		// Distinct from the index-1 test: proves the early-validation exit
		// doesn't accidentally commit later names (tool_a). Today the
		// two-pass structure makes this trivially true; the assertion exists
		// so a future refactor that interleaves validate + commit fails here.
		registry := agentictools.NewExecutorRegistry()
		preExisting := &mockToolExecutor{name: "tool_b", returnContent: "pre"}
		if err := registry.RegisterTool("tool_b", preExisting); err != nil {
			t.Fatalf("seed RegisterTool: %v", err)
		}

		newExecutor := &mockToolExecutor{
			listToolsFunc: func() []agentic.ToolDefinition {
				return []agentic.ToolDefinition{
					{Name: "tool_b"}, // collides immediately
					{Name: "tool_a"},
				}
			},
		}
		if err := registry.RegisterExecutor(newExecutor); err == nil {
			t.Fatal("RegisterExecutor with index-0 collision returned nil, want error")
		}
		if registry.GetTool("tool_a") != nil {
			t.Error("partial commit: tool_a was registered despite first-name collision")
		}
	})
}

func TestExecutorRegistry_Execute_KnownTool(t *testing.T) {
	registry := agentictools.NewExecutorRegistry()

	executor := &mockToolExecutor{
		name:          "graph_query",
		returnContent: "query result",
	}
	err := registry.RegisterTool("graph_query", executor)
	if err != nil {
		t.Fatalf("RegisterTool() failed: %v", err)
	}

	ctx := context.Background()
	call := agentic.ToolCall{
		ID:   "call-123",
		Name: "graph_query",
		Arguments: map[string]any{
			"query": "SELECT * FROM entities",
		},
	}

	result, err := registry.Execute(ctx, call)
	if err != nil {
		t.Fatalf("Execute() error = %v", err)
	}

	if result.CallID != call.ID {
		t.Errorf("Result.CallID = %s, want %s", result.CallID, call.ID)
	}
	if result.Content != "query result" {
		t.Errorf("Result.Content = %s, want 'query result'", result.Content)
	}
	if result.Error != "" {
		t.Errorf("Result.Error should be empty, got %s", result.Error)
	}
}

func TestExecutorRegistry_Execute_UnknownTool(t *testing.T) {
	registry := agentictools.NewExecutorRegistry()

	ctx := context.Background()
	call := agentic.ToolCall{
		ID:   "call-123",
		Name: "unknown_tool",
		Arguments: map[string]any{
			"query": "test",
		},
	}

	result, err := registry.Execute(ctx, call)

	// Should return error result, not panic
	if err == nil {
		t.Error("Execute() with unknown tool should return error")
	}

	// Result should indicate the error
	if result.CallID != call.ID {
		t.Errorf("Result.CallID = %s, want %s", result.CallID, call.ID)
	}
	if result.Error == "" {
		t.Error("Result.Error should not be empty for unknown tool")
	}
	if !containsIgnoreCase(result.Error, "unknown") && !containsIgnoreCase(result.Error, "not found") {
		t.Errorf("Result.Error = %s, should mention unknown/not found", result.Error)
	}
}

func TestExecutorRegistry_Execute_ExecutorReturnsError(t *testing.T) {
	registry := agentictools.NewExecutorRegistry()

	executor := &mockToolExecutor{
		name:        "graph_query",
		shouldError: true,
	}
	err := registry.RegisterTool("graph_query", executor)
	if err != nil {
		t.Fatalf("RegisterTool() failed: %v", err)
	}

	ctx := context.Background()
	call := agentic.ToolCall{
		ID:   "call-123",
		Name: "graph_query",
		Arguments: map[string]any{
			"query": "invalid",
		},
	}

	result, err := registry.Execute(ctx, call)

	// Execute should return error
	if err == nil {
		t.Error("Execute() should return error when executor fails")
	}

	// Result should contain error
	if result.Error == "" {
		t.Error("Result.Error should not be empty when executor fails")
	}
	if result.CallID != call.ID {
		t.Errorf("Result.CallID = %s, want %s", result.CallID, call.ID)
	}
}

func TestExecutorRegistry_Execute_ContextTimeout(t *testing.T) {
	registry := agentictools.NewExecutorRegistry()

	executor := &mockToolExecutor{
		name:  "slow_tool",
		delay: 100 * time.Millisecond, // Slow execution
	}
	err := registry.RegisterTool("slow_tool", executor)
	if err != nil {
		t.Fatalf("RegisterTool() failed: %v", err)
	}

	// Context with very short timeout
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Millisecond)
	defer cancel()

	call := agentic.ToolCall{
		ID:   "call-123",
		Name: "slow_tool",
		Arguments: map[string]any{
			"query": "test",
		},
	}

	result, err := registry.Execute(ctx, call)

	// Should return timeout error
	if err == nil {
		t.Error("Execute() should return error on context timeout")
	}

	// Result should indicate timeout/cancellation
	if result.Error == "" {
		t.Error("Result.Error should not be empty on timeout")
	}
	if result.CallID != call.ID {
		t.Errorf("Result.CallID = %s, want %s", result.CallID, call.ID)
	}
}

func TestExecutorRegistry_Execute_ContextCancellation(t *testing.T) {
	registry := agentictools.NewExecutorRegistry()

	executor := &mockToolExecutor{
		name:  "slow_tool",
		delay: 200 * time.Millisecond,
	}
	err := registry.RegisterTool("slow_tool", executor)
	if err != nil {
		t.Fatalf("RegisterTool() failed: %v", err)
	}

	ctx, cancel := context.WithCancel(context.Background())

	// Cancel context immediately
	cancel()

	call := agentic.ToolCall{
		ID:   "call-123",
		Name: "slow_tool",
		Arguments: map[string]any{
			"query": "test",
		},
	}

	result, err := registry.Execute(ctx, call)

	// Should return cancellation error
	if err == nil {
		t.Error("Execute() should return error on context cancellation")
	}

	// Result should indicate cancellation
	if result.Error == "" {
		t.Error("Result.Error should not be empty on cancellation")
	}
	if result.CallID != call.ID {
		t.Errorf("Result.CallID = %s, want %s", result.CallID, call.ID)
	}
}

func TestExecutorRegistry_EmptyRegistry(t *testing.T) {
	registry := agentictools.NewExecutorRegistry()

	// ListTools on empty registry
	tools := registry.ListTools()
	if tools == nil {
		t.Error("ListTools() should return empty slice, not nil")
	}
	if len(tools) != 0 {
		t.Errorf("ListTools() on empty registry should return empty slice, got %d tools", len(tools))
	}

	// GetTool on empty registry
	tool := registry.GetTool("any_tool")
	if tool != nil {
		t.Error("GetTool() on empty registry should return nil")
	}

	// Execute on empty registry
	ctx := context.Background()
	call := agentic.ToolCall{
		ID:   "call-123",
		Name: "any_tool",
	}
	result, err := registry.Execute(ctx, call)
	if err == nil {
		t.Error("Execute() on empty registry should return error")
	}
	if result.Error == "" {
		t.Error("Result.Error should not be empty when tool not found")
	}
	if result.ErrorKind != agentic.ToolErrorNotFound {
		t.Errorf("Result.ErrorKind = %q, want %q on tool-not-found", result.ErrorKind, agentic.ToolErrorNotFound)
	}
}

func TestExecutorRegistry_ConcurrentRegistration(t *testing.T) {
	registry := agentictools.NewExecutorRegistry()

	// Register tools concurrently
	done := make(chan bool)
	for i := 0; i < 10; i++ {
		go func(n int) {
			toolName := "tool_" + string(rune('0'+n))
			executor := &mockToolExecutor{name: toolName}
			_ = registry.RegisterTool(toolName, executor)
			done <- true
		}(i)
	}

	// Wait for all registrations
	for i := 0; i < 10; i++ {
		<-done
	}

	// All tools should be registered (race detector will catch issues)
	tools := registry.ListTools()
	if len(tools) == 0 {
		t.Error("ListTools() should return registered tools")
	}
}

func TestExecutorRegistry_ConcurrentExecution(t *testing.T) {
	registry := agentictools.NewExecutorRegistry()

	executor := &mockToolExecutor{
		name:          "graph_query",
		returnContent: "result",
	}
	if err := registry.RegisterTool("graph_query", executor); err != nil {
		t.Fatalf("RegisterTool() failed: %v", err)
	}

	// Execute same tool concurrently
	done := make(chan bool)
	for i := 0; i < 10; i++ {
		go func(n int) {
			ctx := context.Background()
			call := agentic.ToolCall{
				ID:   "call-" + string(rune('0'+n)),
				Name: "graph_query",
			}
			_, _ = registry.Execute(ctx, call)
			done <- true
		}(i)
	}

	// Wait for all executions
	for i := 0; i < 10; i++ {
		<-done
	}

	// Race detector will catch any concurrency issues
}

func TestExecutorRegistry_Execute_PropagatesTraceFields(t *testing.T) {
	registry := agentictools.NewExecutorRegistry()

	executor := &mockToolExecutor{
		name:          "graph_query",
		returnContent: "result",
	}
	if err := registry.RegisterTool("graph_query", executor); err != nil {
		t.Fatalf("RegisterTool() failed: %v", err)
	}

	ctx := context.Background()
	call := agentic.ToolCall{
		ID:      "call-123",
		Name:    "graph_query",
		LoopID:  "loop-456",
		TraceID: "trace-789",
	}

	result, err := registry.Execute(ctx, call)
	if err != nil {
		t.Fatalf("Execute() error = %v", err)
	}

	// Verify trace fields are propagated from call to result
	if result.LoopID != call.LoopID {
		t.Errorf("Result.LoopID = %q, want %q", result.LoopID, call.LoopID)
	}
	if result.TraceID != call.TraceID {
		t.Errorf("Result.TraceID = %q, want %q", result.TraceID, call.TraceID)
	}
}

func TestExecutorRegistry_Execute_PropagatesTraceFieldsOnError(t *testing.T) {
	registry := agentictools.NewExecutorRegistry()

	// Test with unknown tool (error case)
	ctx := context.Background()
	call := agentic.ToolCall{
		ID:      "call-123",
		Name:    "unknown_tool",
		LoopID:  "loop-456",
		TraceID: "trace-789",
	}

	result, _ := registry.Execute(ctx, call)

	// Verify trace fields are propagated even on error
	if result.LoopID != call.LoopID {
		t.Errorf("Result.LoopID = %q, want %q", result.LoopID, call.LoopID)
	}
	if result.TraceID != call.TraceID {
		t.Errorf("Result.TraceID = %q, want %q", result.TraceID, call.TraceID)
	}
}
