// Code generated by Tester Agent. DO NOT EDIT.
// Task: Write comprehensive unit tests for graph-gateway component
// Builder must make these tests pass without modification.

package graphgateway

import (
	"context"
	"encoding/json"
	"net"
	"net/http"
	"net/http/httptest"
	"testing"
	"time"

	"github.com/c360studio/semstreams/component"
	"github.com/c360studio/semstreams/internal/lifecyclejoin"
	"github.com/c360studio/semstreams/natsclient"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// ====================================================================================
// Config Tests
// ====================================================================================

func TestConfig_Validate_ValidConfig(t *testing.T) {
	tests := []struct {
		name   string
		config Config
	}{
		{
			name: "valid minimal config",
			config: Config{
				Ports:       validTestPortConfig(),
				GraphQLPath: "/graphql",
				MCPPath:     "/mcp",
				BindAddress: "localhost:8080",
			},
		},
		{
			name: "valid full config with playground",
			config: Config{
				Ports:            validTestPortConfig(),
				GraphQLPath:      "/graphql",
				MCPPath:          "/mcp",
				BindAddress:      "localhost:8080",
				EnablePlayground: true,
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			err := tt.config.Validate()
			assert.NoError(t, err)
		})
	}
}

func TestConfig_Validate_MissingPorts(t *testing.T) {
	tests := []struct {
		name    string
		config  Config
		wantErr bool
	}{
		{
			name: "missing ports config",
			config: Config{
				Ports:       nil,
				GraphQLPath: "/graphql",
				MCPPath:     "/mcp",
				BindAddress: "localhost:8080",
			},
			wantErr: true,
		},
		{
			name: "legacy input",
			config: Config{
				Ports: func() *component.PortConfig {
					ports := validTestPortConfig()
					ports.Inputs = []component.PortDefinition{{Name: "http", Config: component.NetworkPort{Protocol: "http", Host: "localhost", Port: 8080}}}
					return ports
				}(),
				GraphQLPath: "/graphql",
				MCPPath:     "/mcp",
				BindAddress: "localhost:8080",
			},
			wantErr: true,
		},
		{
			name: "empty outputs",
			config: Config{
				Ports:       &component.PortConfig{},
				GraphQLPath: "/graphql",
				MCPPath:     "/mcp",
				BindAddress: "localhost:8080",
			},
			wantErr: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			err := tt.config.Validate()
			if tt.wantErr {
				assert.Error(t, err)
			} else {
				assert.NoError(t, err)
			}
		})
	}
}

func TestConfig_Validate_InvalidPaths(t *testing.T) {
	tests := []struct {
		name    string
		config  Config
		wantErr bool
	}{
		{
			name: "empty GraphQL path",
			config: Config{
				Ports:       validTestPortConfig(),
				GraphQLPath: "", // Empty - invalid
				MCPPath:     "/mcp",
				BindAddress: "localhost:8080",
			},
			wantErr: true,
		},
		{
			name: "empty MCP path",
			config: Config{
				Ports:       validTestPortConfig(),
				GraphQLPath: "/graphql",
				MCPPath:     "", // Empty - invalid
				BindAddress: "localhost:8080",
			},
			wantErr: true,
		},
		{
			name: "empty bind address with standalone server",
			config: Config{
				Ports:            validTestPortConfig(),
				GraphQLPath:      "/graphql",
				MCPPath:          "/mcp",
				StandaloneServer: true,
				BindAddress:      "",
			},
			wantErr: true,
		},
		{
			name: "empty bind address without standalone server",
			config: Config{
				Ports:       validTestPortConfig(),
				GraphQLPath: "/graphql",
				MCPPath:     "/mcp",
				BindAddress: "",
			},
			wantErr: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			err := tt.config.Validate()
			if tt.wantErr {
				assert.Error(t, err)
			} else {
				assert.NoError(t, err)
			}
		})
	}
}

func TestConfig_ApplyDefaults(t *testing.T) {
	config := Config{
		Ports: validTestPortConfig(),
	}

	config.ApplyDefaults()

	// Verify defaults are applied
	assert.Equal(t, "/graphql", config.GraphQLPath, "GraphQLPath should default to /graphql")
	assert.Equal(t, "/mcp", config.MCPPath, "MCPPath should default to /mcp")
	assert.Equal(t, "localhost:8080", config.BindAddress, "BindAddress should default to localhost:8080")
	assert.False(t, config.EnablePlayground, "EnablePlayground should default to false")
	// QueryTimeout 60s gives synthesis (15s) + classification (5s) + headroom
	// for semantic search + enrichment + serialization on commodity-CPU LLM
	// runtimes. Beta.51 bumped the e2e config to 60s; beta.52 brings the
	// in-binary default in line so deployments without explicit config don't
	// 504 on long-tail globalSearch queries.
	assert.Equal(t, 60*time.Second, config.QueryTimeout, "QueryTimeout should default to 60s — keeps gateway above LLM-backed query budget without explicit config")
}

func TestDefaultConfig_ReturnsValidConfig(t *testing.T) {
	config := DefaultConfig()

	// Default config should pass validation
	err := config.Validate()
	assert.NoError(t, err)

	// Verify expected defaults
	assert.NotNil(t, config.Ports)
	assert.Empty(t, config.Ports.Inputs)
	assert.Len(t, config.Ports.Outputs, 3)
	assert.Equal(t, "/graphql", config.GraphQLPath)
	assert.Equal(t, "/mcp", config.MCPPath)
	assert.Equal(t, "localhost:8080", config.BindAddress)
	assert.False(t, config.EnablePlayground)
	assert.Equal(t, 60*time.Second, config.QueryTimeout)
}

// ====================================================================================
// Discoverable Interface Tests (6 methods)
// ====================================================================================

func TestComponent_Meta_ReturnsCorrectMetadata(t *testing.T) {
	comp := createTestComponent(t)

	meta := comp.Meta()

	assert.Equal(t, "gateway", meta.Type, "component type should be 'gateway' not 'processor'")
	assert.Equal(t, "graph-gateway", meta.Name)
	assert.NotEmpty(t, meta.Description)
	assert.NotEmpty(t, meta.Version)
}

func TestComponent_InputPorts_ReturnsNoCompositionPort(t *testing.T) {
	comp := createTestComponent(t)
	require.NoError(t, comp.Initialize()) // Ports are populated during Initialize

	ports := comp.InputPorts()

	assert.Empty(t, ports, "shared-mux gateway owns no composition input")
}

func TestComponent_OutputPorts_ReturnsNATSRequestPort(t *testing.T) {
	comp := createTestComponent(t)
	require.NoError(t, comp.Initialize()) // Ports are populated during Initialize

	ports := comp.OutputPorts()

	require.NotEmpty(t, ports, "should have at least one output port")

	// Verify the gateway exposes all three query request families.
	subjects := make(map[string]bool)
	for _, port := range ports {
		assert.NotEmpty(t, port.Name)
		assert.Equal(t, component.DirectionOutput, port.Direction)

		if natsPort, ok := port.Config.(component.NATSRequestPort); ok {
			subjects[natsPort.Subject] = true
		}
	}

	assert.True(t, subjects["graph.query.*"], "should have graph.query.* output port")
	assert.True(t, subjects["graph.index.query.*"], "should have graph.index.query.* output port")
	assert.True(t, subjects["agentic.query.*"], "should have agentic.query.* output port")
	assert.NotContains(t, subjects, "graph.mutation.*", "graph-gateway is not a mutation requester")
}

func TestComponent_ConfigSchema_ReturnsValidSchema(t *testing.T) {
	comp := createTestComponent(t)

	schema := comp.ConfigSchema()

	// Verify schema has required properties
	assert.NotNil(t, schema.Properties)

	// Check for expected config properties
	_, hasPortsProperty := schema.Properties["ports"]
	assert.True(t, hasPortsProperty, "schema should have 'ports' property")

	_, hasGraphQLPathProperty := schema.Properties["graphql_path"]
	assert.True(t, hasGraphQLPathProperty, "schema should have 'graphql_path' property")

	_, hasMCPPathProperty := schema.Properties["mcp_path"]
	assert.True(t, hasMCPPathProperty, "schema should have 'mcp_path' property")

	_, hasBindAddressProperty := schema.Properties["bind_address"]
	assert.True(t, hasBindAddressProperty, "schema should have 'bind_address' property")

	_, hasEnablePlaygroundProperty := schema.Properties["enable_playground"]
	assert.True(t, hasEnablePlaygroundProperty, "schema should have 'enable_playground' property")
}

func TestComponent_Health_NotStarted(t *testing.T) {
	comp := createTestComponent(t)

	health := comp.Health()

	assert.False(t, health.Healthy, "component should be unhealthy before start")
	assert.Equal(t, 0, health.ErrorCount)
}

func TestComponent_Health_Running(t *testing.T) {
	t.Skip("requires real HTTP server - move to integration tests")
	comp := createTestComponent(t)
	ctx := context.Background()

	require.NoError(t, comp.Initialize())
	require.NoError(t, comp.Start(ctx))
	defer comp.Stop(context.Background())

	// Allow time for component to become healthy
	time.Sleep(100 * time.Millisecond)

	health := comp.Health()

	assert.True(t, health.Healthy, "component should be healthy when running")
	assert.Greater(t, health.Uptime, time.Duration(0))
}

func TestComponent_DataFlow_ReturnsMetrics(t *testing.T) {
	comp := createTestComponent(t)

	metrics := comp.DataFlow()

	// Verify FlowMetrics structure
	assert.GreaterOrEqual(t, metrics.MessagesPerSecond, float64(0))
	assert.GreaterOrEqual(t, metrics.BytesPerSecond, float64(0))
	assert.GreaterOrEqual(t, metrics.ErrorRate, float64(0))
	assert.NotZero(t, metrics.LastActivity)
}

// ====================================================================================
// LifecycleComponent Interface Tests (3 methods)
// ====================================================================================

func TestComponent_Initialize_Success(t *testing.T) {
	comp := createTestComponent(t)

	err := comp.Initialize()

	assert.NoError(t, err)

	// Verify ports are initialized
	assert.Empty(t, comp.InputPorts())
	assert.NotEmpty(t, comp.OutputPorts())
}

func TestComponent_Initialize_InvalidConfig(t *testing.T) {
	// Create component with invalid config (no ports)
	natsClient, err := natsclient.NewClient("nats://localhost:4222")
	require.NoError(t, err)

	comp := &Component{
		config: Config{
			Ports: nil, // Invalid - missing ports
		},
		natsClient: natsClient,
	}

	err = comp.Initialize()

	assert.Error(t, err, "Initialize should fail with invalid config")
}

func TestComponent_Initialize_Idempotent(t *testing.T) {
	comp := createTestComponent(t)

	// Initialize twice
	err1 := comp.Initialize()
	err2 := comp.Initialize()

	assert.NoError(t, err1)
	assert.NoError(t, err2, "Initialize should be idempotent")
}

func TestComponent_Start_Success(t *testing.T) {
	t.Skip("requires real HTTP server - move to integration tests")
	comp := createTestComponent(t)
	ctx := context.Background()

	require.NoError(t, comp.Initialize())
	err := comp.Start(ctx)
	defer comp.Stop(context.Background())

	assert.NoError(t, err)
}

func TestComponent_Start_BeforeInitialize(t *testing.T) {
	comp := createTestComponent(t)
	ctx := context.Background()

	// Start without Initialize
	err := comp.Start(ctx)

	assert.Error(t, err, "Start should fail if not initialized")
}

func TestComponent_Start_AlreadyStarted(t *testing.T) {
	t.Skip("requires real HTTP server - move to integration tests")
	comp := createTestComponent(t)
	ctx := context.Background()

	require.NoError(t, comp.Initialize())
	require.NoError(t, comp.Start(ctx))
	defer comp.Stop(context.Background())

	// Start again - should be idempotent or return appropriate error
	err := comp.Start(ctx)

	// Implementation can choose to be idempotent or return error
	// Either is acceptable as long as it's safe
	_ = err
}

func TestComponent_Stop_Success(t *testing.T) {
	t.Skip("requires real HTTP server - move to integration tests")
	comp := createTestComponent(t)
	ctx := context.Background()

	require.NoError(t, comp.Initialize())
	require.NoError(t, comp.Start(ctx))

	err := comp.Stop(context.Background())

	assert.NoError(t, err)
}

func TestComponent_Stop_BeforeStart(t *testing.T) {
	comp := createTestComponent(t)

	// Stop without Start
	err := comp.Stop(context.Background())

	assert.NoError(t, err, "Stop should be safe even if not started")
}

func TestComponent_Stop_Timeout(t *testing.T) {
	t.Skip("requires real HTTP server - move to integration tests")
	comp := createTestComponent(t)
	ctx := context.Background()

	require.NoError(t, comp.Initialize())
	require.NoError(t, comp.Start(ctx))

	// Very short timeout
	err := comp.Stop(context.Background())

	// Should either succeed quickly or timeout gracefully
	// Implementation may vary, but should not panic
	_ = err
}

// ====================================================================================
// Gateway Interface Tests
// ====================================================================================

func TestComponent_RegisterHTTPHandlers_RegistersGraphQL(t *testing.T) {
	comp := createTestComponent(t)
	require.NoError(t, comp.Initialize())

	mux := http.NewServeMux()
	prefix := "/api/"

	comp.RegisterHTTPHandlers(prefix, mux)

	// Verify GraphQL handler is registered
	req := httptest.NewRequest("POST", "/api/graphql", nil)
	w := httptest.NewRecorder()

	mux.ServeHTTP(w, req)

	// Handler should be registered (may return error, but not 404)
	assert.NotEqual(t, http.StatusNotFound, w.Code, "GraphQL handler should be registered")
}

func TestComponent_RegisterHTTPHandlers_RegistersMCP(t *testing.T) {
	comp := createTestComponent(t)
	require.NoError(t, comp.Initialize())

	mux := http.NewServeMux()
	prefix := "/api/"

	comp.RegisterHTTPHandlers(prefix, mux)

	// Verify MCP handler is registered
	req := httptest.NewRequest("GET", "/api/mcp", nil)
	w := httptest.NewRecorder()

	mux.ServeHTTP(w, req)

	// Handler should be registered (may return error, but not 404)
	assert.NotEqual(t, http.StatusNotFound, w.Code, "MCP handler should be registered")
}

func TestComponent_RegisterHTTPHandlers_RegistersPlayground(t *testing.T) {
	// Create component with playground enabled
	natsClient, err := natsclient.NewClient("nats://localhost:4222")
	require.NoError(t, err)

	config := DefaultConfig()
	config.EnablePlayground = true

	deps := component.Dependencies{
		NATSClient: natsClient,
	}

	configJSON, err := json.Marshal(config)
	require.NoError(t, err)

	comp, err := CreateGraphGateway(configJSON, deps)
	require.NoError(t, err)
	component := comp.(*Component)
	require.NoError(t, component.Initialize())

	mux := http.NewServeMux()
	prefix := "/api/"

	component.RegisterHTTPHandlers(prefix, mux)

	// Verify playground handler is registered at root
	req := httptest.NewRequest("GET", "/api/", nil)
	w := httptest.NewRecorder()

	mux.ServeHTTP(w, req)

	// Playground should be registered (may return HTML or redirect, but not 404)
	assert.NotEqual(t, http.StatusNotFound, w.Code, "Playground handler should be registered when enabled")
}

func TestStandaloneServerBaseContextCancelsBeforeShutdownJoin(t *testing.T) {
	comp := createTestComponent(t)
	comp.config.StandaloneServer = true
	comp.config.BindAddress = "127.0.0.1:0"
	require.NoError(t, comp.Initialize())
	require.NoError(t, comp.Start(context.Background()))
	require.NotNil(t, comp.httpServer.BaseContext)

	handlerCtx := comp.httpServer.BaseContext(nil)
	require.NoError(t, comp.Stop(context.Background()))
	select {
	case <-handlerCtx.Done():
	default:
		t.Fatal("standalone handler context was not canceled before Stop returned")
	}
}

func TestStandaloneServerShutdownKeepsHandlerAuthorityLiveUntilHandlerReturns(t *testing.T) {
	runtimeCtx, cancel := context.WithCancel(t.Context())
	handlerCtx := make(chan context.Context, 1)
	releaseHandler := make(chan struct{})
	shutdownStarted := make(chan struct{})
	mux := http.NewServeMux()
	mux.HandleFunc("/block", func(w http.ResponseWriter, r *http.Request) {
		handlerCtx <- r.Context()
		<-releaseHandler
		w.WriteHeader(http.StatusNoContent)
	})
	server := &http.Server{
		Handler:     mux,
		BaseContext: func(net.Listener) context.Context { return runtimeCtx },
	}
	server.RegisterOnShutdown(func() { close(shutdownStarted) })
	listener, err := net.Listen("tcp", "127.0.0.1:0")
	require.NoError(t, err)
	serveDone := make(chan struct{})
	go func() {
		defer close(serveDone)
		_ = server.Serve(listener)
	}()
	requestDone := make(chan error, 1)
	go func() {
		response, requestErr := http.Get("http://" + listener.Addr().String() + "/block")
		if response != nil {
			_ = response.Body.Close()
		}
		requestDone <- requestErr
	}()
	requestCtx := <-handlerCtx

	comp := createTestComponent(t)
	comp.running = true
	comp.httpServer = server
	comp.generation = lifecyclejoin.NewGeneration(cancel, func() { <-serveDone })
	stopDone := make(chan error, 1)
	go func() { stopDone <- comp.Stop(t.Context()) }()
	<-shutdownStarted
	select {
	case <-requestCtx.Done():
		t.Fatal("graph gateway handler authority canceled before listener Shutdown drained it")
	default:
	}
	close(releaseHandler)
	require.NoError(t, <-stopDone)
	require.NoError(t, <-requestDone)
	require.ErrorIs(t, requestCtx.Err(), context.Canceled)
}

func TestComponent_RegisterHTTPHandlers_NoPlaygroundByDefault(t *testing.T) {
	comp := createTestComponent(t)
	require.NoError(t, comp.Initialize())

	mux := http.NewServeMux()
	prefix := "/api/"

	comp.RegisterHTTPHandlers(prefix, mux)

	// Verify playground is NOT registered by default
	req := httptest.NewRequest("GET", "/api/", nil)
	w := httptest.NewRecorder()

	mux.ServeHTTP(w, req)

	// Without playground enabled, root should not be registered
	assert.Equal(t, http.StatusNotFound, w.Code, "Playground should not be registered by default")
}

func TestComponent_RegisterHTTPHandlers_HandlesPrefix(t *testing.T) {
	comp := createTestComponent(t)
	require.NoError(t, comp.Initialize())

	tests := []struct {
		name   string
		prefix string
	}{
		{"with trailing slash", "/api/"},
		{"without trailing slash", "/api"},
		{"root prefix", "/"},
		{"nested prefix", "/v1/graph/"},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			mux := http.NewServeMux()
			comp.RegisterHTTPHandlers(tt.prefix, mux)

			// Should not panic and handlers should be registered
			// Actual path construction tested in integration tests
		})
	}
}

// ====================================================================================
// Factory and Registration Tests
// ====================================================================================

func TestCreateGraphGateway_ValidConfig(t *testing.T) {
	config := DefaultConfig()
	configJSON, err := json.Marshal(config)
	require.NoError(t, err)

	natsClient, err := natsclient.NewClient("nats://localhost:4222")
	require.NoError(t, err)

	deps := component.Dependencies{
		NATSClient: natsClient,
	}

	comp, err := CreateGraphGateway(configJSON, deps)

	assert.NoError(t, err)
	assert.NotNil(t, comp)
	assert.Implements(t, (*component.Discoverable)(nil), comp)
	assert.Implements(t, (*component.LifecycleComponent)(nil), comp)

	// Also implements Gateway interface
	_, implementsGateway := comp.(interface {
		RegisterHTTPHandlers(prefix string, mux *http.ServeMux)
	})
	assert.True(t, implementsGateway, "component should implement Gateway interface")
}

func TestCreateGraphGateway_EmptyConfig(t *testing.T) {
	// An explicit empty object is a configured component with no port contract.
	emptyJSON := []byte(`{}`)

	natsClient, err := natsclient.NewClient("nats://localhost:4222")
	require.NoError(t, err)

	deps := component.Dependencies{
		NATSClient: natsClient,
	}

	comp, err := CreateGraphGateway(emptyJSON, deps)

	assert.Error(t, err)
	assert.Nil(t, comp)
}

func TestCreateGraphGateway_InvalidConfig(t *testing.T) {
	// Invalid JSON
	invalidJSON := []byte(`{invalid json}`)

	natsClient, err := natsclient.NewClient("nats://localhost:4222")
	require.NoError(t, err)

	deps := component.Dependencies{
		NATSClient: natsClient,
	}

	comp, err := CreateGraphGateway(invalidJSON, deps)

	assert.Error(t, err)
	assert.Nil(t, comp)
}

func TestCreateGraphGateway_MissingDependencies(t *testing.T) {
	config := DefaultConfig()
	configJSON, err := json.Marshal(config)
	require.NoError(t, err)

	// Missing NATSClient dependency
	deps := component.Dependencies{
		NATSClient: nil,
	}

	comp, err := CreateGraphGateway(configJSON, deps)

	assert.Error(t, err, "should fail without NATSClient")
	assert.Nil(t, comp)
}

func TestCreateGraphGateway_PartialConfig(t *testing.T) {
	// The breaking port contract is not auto-filled around unrelated declarations.
	partialJSON := []byte(`{
		"ports": {
			"inputs": [
				{"name": "http", "config": {"kind": "network", "protocol": "http", "host": "localhost", "port": 8080}}
			],
			"outputs": [
				{"name": "audit", "config": {"kind": "nats", "subject": "audit.events"}}
			]
		},
		"graphql_path": "/custom-graphql"
	}`)

	natsClient, err := natsclient.NewClient("nats://localhost:4222")
	require.NoError(t, err)

	deps := component.Dependencies{
		NATSClient: natsClient,
	}

	comp, err := CreateGraphGateway(partialJSON, deps)

	assert.Error(t, err)
	assert.Nil(t, comp)
}

func TestRegister_AddsToRegistry(t *testing.T) {
	registry := component.NewRegistry()

	err := Register(registry)

	assert.NoError(t, err)

	// Verify factory was registered
	factories := registry.ListFactories()
	_, exists := factories["graph-gateway"]
	assert.True(t, exists, "graph-gateway factory should be registered")
}

// ====================================================================================
// Context Handling Tests
// ====================================================================================

func TestComponent_RespectsContext_Cancellation(t *testing.T) {
	t.Skip("requires real HTTP server - move to integration tests")
	comp := createTestComponent(t)
	ctx, cancel := context.WithCancel(context.Background())

	require.NoError(t, comp.Initialize())
	require.NoError(t, comp.Start(ctx))

	// Cancel context
	cancel()

	// Allow time for cancellation to propagate
	time.Sleep(100 * time.Millisecond)

	// Component should handle cancellation gracefully
	err := comp.Stop(context.Background())
	assert.NoError(t, err)
}

func TestComponent_RespectsContext_Timeout(t *testing.T) {
	comp := createTestComponent(t)
	ctx, cancel := context.WithTimeout(context.Background(), 100*time.Millisecond)
	defer cancel()

	require.NoError(t, comp.Initialize())

	// Start with timeout context
	err := comp.Start(ctx)

	// Should either succeed or handle timeout gracefully
	if err != nil {
		// If error, it should be context-related
		assert.Contains(t, err.Error(), "context")
	}
}

// ====================================================================================
// Concurrent Operations Tests
// ====================================================================================

func TestComponent_ConcurrentHealthChecks_ThreadSafe(t *testing.T) {
	comp := createTestComponent(t)

	// Run concurrent health checks
	const numGoroutines = 50

	done := make(chan bool)
	for i := 0; i < numGoroutines; i++ {
		go func() {
			for j := 0; j < 100; j++ {
				_ = comp.Health()
				_ = comp.DataFlow()
			}
			done <- true
		}()
	}

	// Wait for all goroutines
	for i := 0; i < numGoroutines; i++ {
		<-done
	}

	// No assertions needed - test passes if no data race detected
}

func TestComponent_ConcurrentInitialize_ThreadSafe(t *testing.T) {
	comp := createTestComponent(t)

	// Run concurrent initializations
	const numGoroutines = 10

	done := make(chan bool)
	for i := 0; i < numGoroutines; i++ {
		go func() {
			_ = comp.Initialize()
			done <- true
		}()
	}

	// Wait for all goroutines
	for i := 0; i < numGoroutines; i++ {
		<-done
	}

	// Initialize should be idempotent and thread-safe
	// No assertions needed - test passes if no data race detected
}

// ====================================================================================
// Error Handling Tests
// ====================================================================================

func TestComponent_InitializeError_InvalidPorts(t *testing.T) {
	natsClient, err := natsclient.NewClient("nats://localhost:4222")
	require.NoError(t, err)

	comp := &Component{
		config: Config{
			Ports: &component.PortConfig{
				Inputs:  []component.PortDefinition{}, // Empty - invalid
				Outputs: []component.PortDefinition{},
			},
			GraphQLPath: "/graphql",
			MCPPath:     "/mcp",
			BindAddress: "localhost:8080",
		},
		natsClient: natsClient,
	}

	err = comp.Initialize()

	assert.Error(t, err, "Initialize should fail with empty ports")
}

func TestComponent_Metrics_AccumulateCorrectly(t *testing.T) {
	comp := createTestComponent(t)
	require.NoError(t, comp.Initialize())

	initialMetrics := comp.DataFlow()

	// Simulate some activity by updating internal state
	// (In real component, this would happen during HTTP request handling)
	// For unit test, we're just verifying the metric structure exists

	updatedMetrics := comp.DataFlow()

	assert.GreaterOrEqual(t, updatedMetrics.MessagesPerSecond, float64(0))
	assert.GreaterOrEqual(t, updatedMetrics.BytesPerSecond, float64(0))
	assert.GreaterOrEqual(t, updatedMetrics.ErrorRate, float64(0))

	// Metrics should not go negative
	assert.GreaterOrEqual(t, updatedMetrics.MessagesPerSecond, initialMetrics.MessagesPerSecond)
}

// ====================================================================================
// Helper Functions
// ====================================================================================

// createTestComponent creates a basic test component with unconnected NATS client
func createTestComponent(t *testing.T) *Component {
	t.Helper()

	// Create unconnected NATS client (won't actually connect)
	natsClient, err := natsclient.NewClient("nats://localhost:4222")
	require.NoError(t, err)

	config := DefaultConfig()
	deps := component.Dependencies{
		NATSClient: natsClient,
	}

	configJSON, err := json.Marshal(config)
	require.NoError(t, err)

	comp, err := CreateGraphGateway(configJSON, deps)
	require.NoError(t, err)

	return comp.(*Component)
}

func validTestPortConfig() *component.PortConfig {
	return &component.PortConfig{
		Outputs: canonicalQueryOutputs("graph.query.*", "graph.index.query.*", "agentic.query.*"),
	}
}
