// Code generated by Tester Agent. DO NOT EDIT.
// Task: Write tests for graph-gateway NATS query routing (Phase 2, Step 5)
// Builder must make these tests pass without modification.

package graphgateway

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"io"
	"log/slog"
	"net/http"
	"net/http/httptest"
	"testing"
	"time"

	"github.com/nats-io/nats.go"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/c360studio/semstreams/component"
	"github.com/c360studio/semstreams/graph"
	"github.com/c360studio/semstreams/natsclient"
	semerrs "github.com/c360studio/semstreams/pkg/errs"
	semtypes "github.com/c360studio/semstreams/pkg/types"
)

// ====================================================================================
// Mock NATS Client for Request/Reply Testing
// ====================================================================================

// mockNATSRequester simulates NATS request/reply for testing
type mockNATSRequester struct {
	requestFunc func(ctx context.Context, subject string, data []byte, timeout time.Duration) ([]byte, error)
	respHeader  nats.Header // when set, the simulated reply carries these headers (e.g. X-Status error)
	connected   bool
	status      natsclient.ConnectionStatus
}

func newMockNATSRequester() *mockNATSRequester {
	return &mockNATSRequester{
		connected: true,
		status:    natsclient.StatusConnected,
	}
}

func (m *mockNATSRequester) Request(ctx context.Context, subject string, data []byte, timeout time.Duration) ([]byte, error) {
	if m.requestFunc != nil {
		return m.requestFunc(ctx, subject, data, timeout)
	}
	return nil, errors.New("no mock response configured")
}

// RequestClassified routes through Request and ClassifyReply against the
// response bytes + headers. ADR-060: a handler error is signalled by the
// X-Status header (set respHeader to simulate it); ClassifyReply reconstructs a
// *errs.ClassifiedError from the {message} envelope body. No headers = success.
func (m *mockNATSRequester) RequestClassified(ctx context.Context, subject string, data []byte, timeout time.Duration) ([]byte, error) {
	body, err := m.Request(ctx, subject, data, timeout)
	if err != nil {
		return nil, err
	}
	header := m.respHeader
	if header == nil {
		header = nats.Header{}
	}
	msg := &nats.Msg{Data: body, Header: header}
	return natsclient.ClassifyReply(msg)
}

func (m *mockNATSRequester) Status() natsclient.ConnectionStatus {
	return m.status
}

// ====================================================================================
// GraphQL to NATS Subject Mapping Tests
// ====================================================================================

func TestGateway_MapGraphQLToNATSSubject_PathSearch(t *testing.T) {
	comp := createTestGateway(t)

	tests := []struct {
		name            string
		query           string
		variables       map[string]interface{}
		expectedSubject string
	}{
		{
			name:            "pathSearch query",
			query:           `query { pathSearch(startEntity: "acme.ops.test.graph.entity.001", maxDepth: 3) { entities } }`,
			variables:       nil,
			expectedSubject: "graph.query.pathSearch",
		},
		{
			name:            "pathSearch with variables",
			query:           `query PathSearch($start: String!, $depth: Int!) { pathSearch(startEntity: $start, maxDepth: $depth) { entities } }`,
			variables:       map[string]interface{}{"start": "acme.ops.test.graph.entity.001", "depth": 3},
			expectedSubject: "graph.query.pathSearch",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			subject := comp.mapGraphQLQueryToNATSSubject(tt.query)
			assert.Equal(t, tt.expectedSubject, subject)
		})
	}
}

func TestGateway_MapGraphQLToNATSSubject_Entity(t *testing.T) {
	comp := createTestGateway(t)

	tests := []struct {
		name            string
		query           string
		expectedSubject string
	}{
		{
			name:            "entity query by ID",
			query:           `query { entity(id: "acme.ops.test.graph.entity.001") { id triples } }`,
			expectedSubject: "graph.query.entity",
		},
		{
			name:            "entity query with alias",
			query:           `query GetEntity { entity(id: "acme.ops.test.graph.entity.001") { id } }`,
			expectedSubject: "graph.query.entity",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			subject := comp.mapGraphQLQueryToNATSSubject(tt.query)
			assert.Equal(t, tt.expectedSubject, subject)
		})
	}
}

func TestGateway_MapGraphQLToNATSSubject_Relationships(t *testing.T) {
	comp := createTestGateway(t)

	tests := []struct {
		name            string
		query           string
		expectedSubject string
	}{
		{
			name:            "relationships query",
			query:           `query { relationships(entityId: "acme.ops.test.graph.entity.001") { from to predicate } }`,
			expectedSubject: "graph.query.relationships",
		},
		{
			name:            "outgoing relationships",
			query:           `query { outgoing: relationships(entityId: "acme.ops.test.graph.entity.001") { to } }`,
			expectedSubject: "graph.query.relationships",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			subject := comp.mapGraphQLQueryToNATSSubject(tt.query)
			assert.Equal(t, tt.expectedSubject, subject)
		})
	}
}

func TestGateway_MapGraphQLToNATSSubject_Trajectory(t *testing.T) {
	comp := createTestGateway(t)

	tests := []struct {
		name            string
		query           string
		expectedSubject string
	}{
		{
			name:            "trajectory query",
			query:           `{ trajectory(loopId: "loop-123") { loopId steps { stepType } outcome } }`,
			expectedSubject: "agentic.query.trajectory",
		},
		{
			name:            "trajectory query with operation name",
			query:           `query GetTrajectory($id: String!) { trajectory(loopId: $id) { loopId outcome duration } }`,
			expectedSubject: "agentic.query.trajectory",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			subject := comp.mapGraphQLQueryToNATSSubject(tt.query)
			assert.Equal(t, tt.expectedSubject, subject)
		})
	}
}

func TestGateway_MapGraphQLToNATSSubject_Unknown(t *testing.T) {
	comp := createTestGateway(t)

	tests := []struct {
		name            string
		query           string
		expectedSubject string
	}{
		{
			name:            "unrecognized query",
			query:           `query { unknownOperation { data } }`,
			expectedSubject: "graph.query.unknown",
		},
		{
			name:            "empty query",
			query:           "",
			expectedSubject: "graph.query.unknown",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			subject := comp.mapGraphQLQueryToNATSSubject(tt.query)
			assert.Equal(t, tt.expectedSubject, subject)
		})
	}
}

// TestGateway_MapGraphQLToNATSSubject_GraphSummary covers the composite
// discovery resolver added 2026-05-12. The mapping uses a "graphsummary"
// substring match positioned BEFORE the generic "entity" / "predicates"
// fallbacks so the dedicated subject wins.
func TestGateway_MapGraphQLToNATSSubject_GraphSummary(t *testing.T) {
	comp := createTestGateway(t)

	tests := []struct {
		name            string
		query           string
		expectedSubject string
	}{
		{
			name:            "graphSummary no-args",
			query:           `query { graphSummary { total_entities entity_types { type count } } }`,
			expectedSubject: "graph.query.summary",
		},
		{
			name:            "graphSummary with include_predicates arg",
			query:           `query { graphSummary(include_predicates: false) { total_entities } }`,
			expectedSubject: "graph.query.summary",
		},
		{
			name:            "graphSummary lowercase variant",
			query:           `{ graphsummary { total_entities } }`,
			expectedSubject: "graph.query.summary",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			subject := comp.mapGraphQLQueryToNATSSubject(tt.query)
			assert.Equal(t, tt.expectedSubject, subject)
		})
	}
}

// TestGateway_SubjectToGraphQLField_GraphSummary confirms the inverse
// mapping — when graph-query responds to graph.query.summary, the
// gateway wraps the payload under the "graphSummary" GraphQL field.
func TestGateway_SubjectToGraphQLField_GraphSummary(t *testing.T) {
	comp := createTestGateway(t)
	assert.Equal(t, "graphSummary", comp.subjectToGraphQLField("graph.query.summary"))
}

// TestGateway_TransformVariables_GraphSummary verifies the three V1
// fields land in the NATS payload (and unrelated variables are dropped
// per the extractVars convention).
func TestGateway_TransformVariables_GraphSummary(t *testing.T) {
	comp := createTestGateway(t)
	vars := map[string]any{
		"include_predicates":  false,
		"entity_sample_limit": 500,
		"examples_per_type":   3,
		"unrelated":           "ignored",
	}
	payload := comp.transformVariablesToNATSPayload(vars, "graph.query.summary")
	assert.Equal(t, false, payload["include_predicates"])
	assert.Equal(t, 500, payload["entity_sample_limit"])
	assert.Equal(t, 3, payload["examples_per_type"])
	_, hasUnrelated := payload["unrelated"]
	assert.False(t, hasUnrelated, "extractVars should drop variables not in the allowlist")
}

// TestGateway_MapGraphQLToNATSSubject_SearchGraph covers the searchGraph
// keyword routing. Important corner: "searchgraph" must match BEFORE
// "globalsearch" so the dedicated subject wins when an agent's query
// references both terms.
func TestGateway_MapGraphQLToNATSSubject_SearchGraph(t *testing.T) {
	comp := createTestGateway(t)
	tests := []struct {
		name            string
		query           string
		expectedSubject string
	}{
		{
			name:            "searchGraph simple call",
			query:           `query { searchGraph(query: "auth flow") { count entity_digests { id } } }`,
			expectedSubject: "graph.query.searchGraph",
		},
		{
			name:            "searchGraph alongside word globalsearch in comment",
			query:           `# also try globalsearch later` + "\n" + `{ searchGraph(query: "x") { count } }`,
			expectedSubject: "graph.query.searchGraph",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			subject := comp.mapGraphQLQueryToNATSSubject(tt.query)
			assert.Equal(t, tt.expectedSubject, subject)
		})
	}
}

// TestGateway_SubjectToGraphQLField_SearchGraph confirms the response
// wraps under the GraphQL "searchGraph" field.
func TestGateway_SubjectToGraphQLField_SearchGraph(t *testing.T) {
	comp := createTestGateway(t)
	assert.Equal(t, "searchGraph", comp.subjectToGraphQLField("graph.query.searchGraph"))
}

// TestGateway_TransformVariables_SearchGraph confirms searchGraph
// reuses the globalSearch variable transformer so the arg surface
// stays in sync — the server-side handler is a composite over
// globalSearch and expects identical request shape.
func TestGateway_TransformVariables_SearchGraph(t *testing.T) {
	comp := createTestGateway(t)
	vars := map[string]any{
		"query":          "auth flow",
		"level":          float64(2),
		"maxCommunities": float64(5),
	}
	payload := comp.transformVariablesToNATSPayload(vars, "graph.query.searchGraph")
	assert.Equal(t, "auth flow", payload["query"])
	// Should match transformGlobalSearchVars output for the same input —
	// any divergence indicates the searchGraph case stopped delegating.
	expected := comp.transformVariablesToNATSPayload(vars, "graph.query.globalSearch")
	assert.Equal(t, expected, payload)
}

// ====================================================================================
// Request Forwarding Tests
// ====================================================================================

func TestGateway_ForwardQueryToNATS_Success(t *testing.T) {
	mock := newMockNATSRequester()

	// Mock successful response from graph-query coordinator
	expectedResponse := []byte(`{"entities":[{"id":"acme.ops.test.graph.entity.001"}]}`)
	mock.requestFunc = func(ctx context.Context, subject string, data []byte, timeout time.Duration) ([]byte, error) {
		assert.Equal(t, "graph.query.pathSearch", subject, "should route to graph.query.pathSearch")
		return expectedResponse, nil
	}

	comp := createTestGatewayWithMock(t, mock)
	require.NoError(t, comp.Initialize())
	require.NoError(t, comp.Start(context.Background()))
	defer comp.Stop(5 * time.Second)

	// Create HTTP request
	gqlRequest := map[string]interface{}{
		"query":     `query { pathSearch(startEntity: "acme.ops.test.graph.entity.001", maxDepth: 3) { entities } }`,
		"variables": nil,
	}
	body, err := json.Marshal(gqlRequest)
	require.NoError(t, err)

	req := httptest.NewRequest(http.MethodPost, "/graphql", bytes.NewReader(body))
	req.Header.Set("Content-Type", "application/json")
	w := httptest.NewRecorder()

	// Execute request
	comp.handleGraphQL(w, req)

	// Verify response
	assert.Equal(t, http.StatusOK, w.Code)
	assert.Equal(t, "application/json", w.Header().Get("Content-Type"))

	var response map[string]interface{}
	err = json.Unmarshal(w.Body.Bytes(), &response)
	require.NoError(t, err)

	// Response should be wrapped in GraphQL format
	data, ok := response["data"]
	assert.True(t, ok, "response should have 'data' field")
	assert.NotNil(t, data)
}

func TestGateway_ForwardQueryToNATS_WithVariables(t *testing.T) {
	mock := newMockNATSRequester()

	mock.requestFunc = func(ctx context.Context, subject string, data []byte, timeout time.Duration) ([]byte, error) {
		// Verify variables are included in payload
		var payload map[string]interface{}
		err := json.Unmarshal(data, &payload)
		require.NoError(t, err)

		assert.Equal(t, "acme.ops.test.graph.entity.001", payload["start_entity"])
		assert.Equal(t, float64(5), payload["max_depth"])

		return []byte(`{"entities":[]}`), nil
	}

	comp := createTestGatewayWithMock(t, mock)
	require.NoError(t, comp.Initialize())
	require.NoError(t, comp.Start(context.Background()))
	defer comp.Stop(5 * time.Second)

	gqlRequest := map[string]interface{}{
		"query": `query PathSearch($start: String!, $depth: Int!) { pathSearch(startEntity: $start, maxDepth: $depth) { entities } }`,
		"variables": map[string]interface{}{
			"start": "acme.ops.test.graph.entity.001",
			"depth": 5,
		},
	}
	body, err := json.Marshal(gqlRequest)
	require.NoError(t, err)

	req := httptest.NewRequest(http.MethodPost, "/graphql", bytes.NewReader(body))
	req.Header.Set("Content-Type", "application/json")
	w := httptest.NewRecorder()

	comp.handleGraphQL(w, req)

	assert.Equal(t, http.StatusOK, w.Code)
}

func TestGateway_ForwardQueryToNATS_MultipleQueryTypes(t *testing.T) {
	tests := []struct {
		name            string
		query           string
		expectedSubject string
	}{
		{
			name:            "entity query",
			query:           `query { entity(id: "acme.ops.test.graph.entity.001") { id } }`,
			expectedSubject: "graph.query.entity",
		},
		{
			name:            "relationships query",
			query:           `query { relationships(entityId: "acme.ops.test.graph.entity.001") { from to } }`,
			expectedSubject: "graph.query.relationships",
		},
		{
			name:            "pathSearch query",
			query:           `query { pathSearch(startEntity: "acme.ops.test.graph.entity.001", maxDepth: 3) { entities } }`,
			expectedSubject: "graph.query.pathSearch",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			mock := newMockNATSRequester()

			mock.requestFunc = func(ctx context.Context, subject string, data []byte, timeout time.Duration) ([]byte, error) {
				assert.Equal(t, tt.expectedSubject, subject, "should route to correct NATS subject")
				return []byte(`{"result":"ok"}`), nil
			}

			comp := createTestGatewayWithMock(t, mock)
			require.NoError(t, comp.Initialize())
			require.NoError(t, comp.Start(context.Background()))
			defer comp.Stop(5 * time.Second)

			gqlRequest := map[string]interface{}{
				"query":     tt.query,
				"variables": nil,
			}
			body, err := json.Marshal(gqlRequest)
			require.NoError(t, err)

			req := httptest.NewRequest(http.MethodPost, "/graphql", bytes.NewReader(body))
			req.Header.Set("Content-Type", "application/json")
			w := httptest.NewRecorder()

			comp.handleGraphQL(w, req)

			assert.Equal(t, http.StatusOK, w.Code)
		})
	}
}

// ====================================================================================
// Error Handling Tests
// ====================================================================================

func TestGateway_QueryErrorHandling_NATSTimeout(t *testing.T) {
	mock := newMockNATSRequester()

	// Simulate NATS timeout
	mock.requestFunc = func(ctx context.Context, subject string, data []byte, timeout time.Duration) ([]byte, error) {
		return nil, context.DeadlineExceeded
	}

	comp := createTestGatewayWithMock(t, mock)
	require.NoError(t, comp.Initialize())
	require.NoError(t, comp.Start(context.Background()))
	defer comp.Stop(5 * time.Second)

	gqlRequest := map[string]interface{}{
		"query": `query { entity(id: "acme.ops.test.graph.entity.001") { id } }`,
	}
	body, err := json.Marshal(gqlRequest)
	require.NoError(t, err)

	req := httptest.NewRequest(http.MethodPost, "/graphql", bytes.NewReader(body))
	req.Header.Set("Content-Type", "application/json")
	w := httptest.NewRecorder()

	comp.handleGraphQL(w, req)

	// Should return 504 Gateway Timeout
	assert.Equal(t, http.StatusGatewayTimeout, w.Code)

	var response map[string]interface{}
	err = json.Unmarshal(w.Body.Bytes(), &response)
	require.NoError(t, err)

	errors, ok := response["errors"]
	assert.True(t, ok, "response should have 'errors' field for timeout")
	assert.NotNil(t, errors)
}

func TestGateway_QueryErrorHandling_InvalidRequest(t *testing.T) {
	comp := createTestGateway(t)
	require.NoError(t, comp.Initialize())
	require.NoError(t, comp.Start(context.Background()))
	defer comp.Stop(5 * time.Second)

	tests := []struct {
		name        string
		requestBody string
		expectedErr bool
	}{
		{
			name:        "invalid JSON",
			requestBody: `{invalid json}`,
			expectedErr: true,
		},
		{
			name:        "missing query field",
			requestBody: `{"variables":{}}`,
			expectedErr: true,
		},
		{
			name:        "empty body",
			requestBody: ``,
			expectedErr: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			req := httptest.NewRequest(http.MethodPost, "/graphql", bytes.NewReader([]byte(tt.requestBody)))
			req.Header.Set("Content-Type", "application/json")
			w := httptest.NewRecorder()

			comp.handleGraphQL(w, req)

			assert.Equal(t, http.StatusBadRequest, w.Code, "should return 400 for invalid request")

			var response map[string]interface{}
			err := json.Unmarshal(w.Body.Bytes(), &response)
			require.NoError(t, err)

			errors, ok := response["errors"]
			assert.True(t, ok, "response should have 'errors' field")
			assert.NotNil(t, errors)
		})
	}
}

func TestGateway_QueryErrorHandling_ComponentUnavailable(t *testing.T) {
	mock := newMockNATSRequester()

	// Simulate component unavailable
	mock.requestFunc = func(ctx context.Context, subject string, data []byte, timeout time.Duration) ([]byte, error) {
		return nil, errors.New("no responders available")
	}

	comp := createTestGatewayWithMock(t, mock)
	require.NoError(t, comp.Initialize())
	require.NoError(t, comp.Start(context.Background()))
	defer comp.Stop(5 * time.Second)

	gqlRequest := map[string]interface{}{
		"query": `query { entity(id: "acme.ops.test.graph.entity.001") { id } }`,
	}
	body, err := json.Marshal(gqlRequest)
	require.NoError(t, err)

	req := httptest.NewRequest(http.MethodPost, "/graphql", bytes.NewReader(body))
	req.Header.Set("Content-Type", "application/json")
	w := httptest.NewRecorder()

	comp.handleGraphQL(w, req)

	// Should return 500 Internal Server Error for component unavailable
	assert.Equal(t, http.StatusInternalServerError, w.Code)

	var response map[string]interface{}
	err = json.Unmarshal(w.Body.Bytes(), &response)
	require.NoError(t, err)

	errors, ok := response["errors"]
	assert.True(t, ok, "response should have 'errors' field")
	assert.NotNil(t, errors)
}

// TestGateway_QueryErrorHandling_ClassifiedHandlerError pins the contract:
// when the upstream NATS handler returns a classified error (ADR-060
// header-stamped X-Status + {message} envelope), the gateway maps it to HTTP
// 200 with a GraphQL errors envelope, and the envelope message is the handler's
// CLEAN inner text — NOT the natsclient.ClassifyReply attribution wrap.
//
// The mock stamps the ADR-060 error-reply wire shape (X-Status / X-Error-Class
// headers + {message} envelope body); ClassifyReply reconstructs the classified
// error and the gateway maps it into the GraphQL errors envelope.
func TestGateway_QueryErrorHandling_ClassifiedHandlerError(t *testing.T) {
	mock := newMockNATSRequester()

	// Handler error shape graph-ingest's query handler emits on a missing entity.
	mock.respHeader = nats.Header{
		natsclient.HeaderStatus:     []string{natsclient.HeaderStatusError},
		natsclient.HeaderErrorClass: []string{natsclient.ErrorClassInvalid},
		natsclient.HeaderErrorCode:  []string{graph.ErrorCodeEntityNotFound},
	}
	mock.requestFunc = func(ctx context.Context, subject string, data []byte, timeout time.Duration) ([]byte, error) {
		return []byte(`{"message":"not found: acme.ops.test.graph.entity.001"}`), nil
	}

	comp := createTestGatewayWithMock(t, mock)
	require.NoError(t, comp.Initialize())
	require.NoError(t, comp.Start(context.Background()))
	defer comp.Stop(5 * time.Second)

	gqlRequest := map[string]interface{}{
		"query": `query { entity(id: "acme.ops.test.graph.entity.001") { id } }`,
	}
	body, err := json.Marshal(gqlRequest)
	require.NoError(t, err)

	req := httptest.NewRequest(http.MethodPost, "/graphql", bytes.NewReader(body))
	req.Header.Set("Content-Type", "application/json")
	w := httptest.NewRecorder()

	comp.handleGraphQL(w, req)

	// GraphQL convention: handler errors → 200 with errors envelope.
	assert.Equal(t, http.StatusOK, w.Code)

	var response map[string]interface{}
	err = json.Unmarshal(w.Body.Bytes(), &response)
	require.NoError(t, err)

	errs, ok := response["errors"].([]interface{})
	require.True(t, ok, "response must have errors array; got %v", response)
	require.NotEmpty(t, errs, "errors array must be non-empty")

	// The error message must surface the handler's CLEAN inner
	// message — not the natsclient.ClassifyReply attribution wrap.
	firstErr := errs[0].(map[string]interface{})
	message, ok := firstErr["message"].(string)
	require.True(t, ok, "first error must have message field; got %v", firstErr)
	assert.Contains(t, message, "not found: acme.ops.test.graph.entity.001",
		"GraphQL error message must surface the handler text")
	assert.NotContains(t, message, "natsclient",
		"GraphQL error message must NOT leak natsclient attribution; got %q", message)
	assert.NotContains(t, message, "ClassifyReply",
		"GraphQL error message must NOT leak ClassifyReply attribution; got %q", message)
}

func TestGateway_QueryErrorHandling_GraphQLError(t *testing.T) {
	mock := newMockNATSRequester()

	// Return GraphQL-formatted error from coordinator
	errorResponse := []byte(`{"errors":[{"message":"entity not found","extensions":{"code":"NOT_FOUND"}}]}`)
	mock.requestFunc = func(ctx context.Context, subject string, data []byte, timeout time.Duration) ([]byte, error) {
		return errorResponse, nil
	}

	comp := createTestGatewayWithMock(t, mock)
	require.NoError(t, comp.Initialize())
	require.NoError(t, comp.Start(context.Background()))
	defer comp.Stop(5 * time.Second)

	gqlRequest := map[string]interface{}{
		"query": `query { entity(id: "nonexistent") { id } }`,
	}
	body, err := json.Marshal(gqlRequest)
	require.NoError(t, err)

	req := httptest.NewRequest(http.MethodPost, "/graphql", bytes.NewReader(body))
	req.Header.Set("Content-Type", "application/json")
	w := httptest.NewRecorder()

	comp.handleGraphQL(w, req)

	// Should return 200 OK with GraphQL errors (GraphQL convention)
	assert.Equal(t, http.StatusOK, w.Code)

	var response map[string]interface{}
	err = json.Unmarshal(w.Body.Bytes(), &response)
	require.NoError(t, err)

	// Should forward GraphQL errors from coordinator
	errors, ok := response["errors"]
	assert.True(t, ok, "response should preserve GraphQL errors")
	assert.NotNil(t, errors)
}

// ====================================================================================
// Context Propagation Tests
// ====================================================================================

func TestGateway_ContextTimeout_CancelsNATSRequest(t *testing.T) {
	mock := newMockNATSRequester()

	contextCancelled := false
	mock.requestFunc = func(ctx context.Context, subject string, data []byte, timeout time.Duration) ([]byte, error) {
		// Check if context is cancelled
		select {
		case <-ctx.Done():
			contextCancelled = true
			return nil, ctx.Err()
		case <-time.After(100 * time.Millisecond):
			return []byte(`{"result":"ok"}`), nil
		}
	}

	comp := createTestGatewayWithMock(t, mock)
	require.NoError(t, comp.Initialize())
	require.NoError(t, comp.Start(context.Background()))
	defer comp.Stop(5 * time.Second)

	gqlRequest := map[string]interface{}{
		"query": `query { entity(id: "acme.ops.test.graph.entity.001") { id } }`,
	}
	body, err := json.Marshal(gqlRequest)
	require.NoError(t, err)

	// Create request with timeout context
	req := httptest.NewRequest(http.MethodPost, "/graphql", bytes.NewReader(body))
	req.Header.Set("Content-Type", "application/json")

	// Cancel context immediately
	ctx, cancel := context.WithCancel(req.Context())
	cancel()
	req = req.WithContext(ctx)

	w := httptest.NewRecorder()

	comp.handleGraphQL(w, req)

	// Verify context was propagated and cancelled
	assert.True(t, contextCancelled, "NATS request should receive cancelled context")
	assert.Equal(t, http.StatusGatewayTimeout, w.Code, "should return timeout status")
}

func TestGateway_ContextPropagation_HTTPTimeout(t *testing.T) {
	mock := newMockNATSRequester()

	requestReceived := false
	mock.requestFunc = func(ctx context.Context, subject string, data []byte, timeout time.Duration) ([]byte, error) {
		requestReceived = true

		// Verify context has deadline
		_, hasDeadline := ctx.Deadline()
		assert.True(t, hasDeadline, "context should have deadline from HTTP request")

		return []byte(`{"result":"ok"}`), nil
	}

	comp := createTestGatewayWithMock(t, mock)
	require.NoError(t, comp.Initialize())
	require.NoError(t, comp.Start(context.Background()))
	defer comp.Stop(5 * time.Second)

	gqlRequest := map[string]interface{}{
		"query": `query { entity(id: "acme.ops.test.graph.entity.001") { id } }`,
	}
	body, err := json.Marshal(gqlRequest)
	require.NoError(t, err)

	req := httptest.NewRequest(http.MethodPost, "/graphql", bytes.NewReader(body))
	req.Header.Set("Content-Type", "application/json")

	// Add timeout to request context
	ctx, cancel := context.WithTimeout(req.Context(), 5*time.Second)
	defer cancel()
	req = req.WithContext(ctx)

	w := httptest.NewRecorder()

	comp.handleGraphQL(w, req)

	assert.True(t, requestReceived, "NATS request should be made")
	assert.Equal(t, http.StatusOK, w.Code)
}

func TestGateway_ContextPropagation_ClientDisconnect(t *testing.T) {
	mock := newMockNATSRequester()

	disconnectDetected := false
	mock.requestFunc = func(ctx context.Context, subject string, data []byte, timeout time.Duration) ([]byte, error) {
		// Simulate slow processing
		select {
		case <-ctx.Done():
			disconnectDetected = true
			return nil, ctx.Err()
		case <-time.After(200 * time.Millisecond):
			return []byte(`{"result":"ok"}`), nil
		}
	}

	comp := createTestGatewayWithMock(t, mock)
	require.NoError(t, comp.Initialize())
	require.NoError(t, comp.Start(context.Background()))
	defer comp.Stop(5 * time.Second)

	gqlRequest := map[string]interface{}{
		"query": `query { pathSearch(startEntity: "acme.ops.test.graph.entity.001", maxDepth: 10) { entities } }`,
	}
	body, err := json.Marshal(gqlRequest)
	require.NoError(t, err)

	req := httptest.NewRequest(http.MethodPost, "/graphql", bytes.NewReader(body))
	req.Header.Set("Content-Type", "application/json")

	// Simulate client disconnect by cancelling context
	ctx, cancel := context.WithCancel(req.Context())
	req = req.WithContext(ctx)

	// Cancel immediately to simulate disconnect
	cancel()

	w := httptest.NewRecorder()

	comp.handleGraphQL(w, req)

	// Verify that context cancellation was detected
	time.Sleep(50 * time.Millisecond) // Allow goroutine to process
	assert.True(t, disconnectDetected, "should detect client disconnect")
}

// ====================================================================================
// Integration with GraphQL Format Tests
// ====================================================================================

func TestGateway_GraphQLResponseFormat_Success(t *testing.T) {
	mock := newMockNATSRequester()

	// Return raw data from coordinator
	coordinatorResponse := []byte(`{"entities":[{"id":"acme.ops.test.graph.entity.001","triples":[]}]}`)
	mock.requestFunc = func(ctx context.Context, subject string, data []byte, timeout time.Duration) ([]byte, error) {
		return coordinatorResponse, nil
	}

	comp := createTestGatewayWithMock(t, mock)
	require.NoError(t, comp.Initialize())
	require.NoError(t, comp.Start(context.Background()))
	defer comp.Stop(5 * time.Second)

	gqlRequest := map[string]interface{}{
		"query": `query { pathSearch(startEntity: "acme.ops.test.graph.entity.001", maxDepth: 3) { entities } }`,
	}
	body, err := json.Marshal(gqlRequest)
	require.NoError(t, err)

	req := httptest.NewRequest(http.MethodPost, "/graphql", bytes.NewReader(body))
	req.Header.Set("Content-Type", "application/json")
	w := httptest.NewRecorder()

	comp.handleGraphQL(w, req)

	assert.Equal(t, http.StatusOK, w.Code)
	assert.Equal(t, "application/json", w.Header().Get("Content-Type"))

	// Verify response is wrapped in GraphQL format: {"data": {"pathSearch": {...}}}
	var response map[string]interface{}
	err = json.Unmarshal(w.Body.Bytes(), &response)
	require.NoError(t, err)

	data, ok := response["data"].(map[string]interface{})
	assert.True(t, ok, "response should have 'data' field")
	assert.NotNil(t, data)

	// Verify data contains pathSearch field with coordinator response
	pathSearch, ok := data["pathSearch"]
	assert.True(t, ok, "data should have 'pathSearch' field")
	assert.NotNil(t, pathSearch)

	// Verify pathSearch contains coordinator response
	pathSearchJSON, err := json.Marshal(pathSearch)
	require.NoError(t, err)
	assert.JSONEq(t, string(coordinatorResponse), string(pathSearchJSON), "pathSearch should match coordinator response")
}

func TestGateway_GraphQLResponseFormat_Error(t *testing.T) {
	mock := newMockNATSRequester()

	mock.requestFunc = func(ctx context.Context, subject string, data []byte, timeout time.Duration) ([]byte, error) {
		return nil, errors.New("query failed")
	}

	comp := createTestGatewayWithMock(t, mock)
	require.NoError(t, comp.Initialize())
	require.NoError(t, comp.Start(context.Background()))
	defer comp.Stop(5 * time.Second)

	gqlRequest := map[string]interface{}{
		"query": `query { entity(id: "acme.ops.test.graph.entity.001") { id } }`,
	}
	body, err := json.Marshal(gqlRequest)
	require.NoError(t, err)

	req := httptest.NewRequest(http.MethodPost, "/graphql", bytes.NewReader(body))
	req.Header.Set("Content-Type", "application/json")
	w := httptest.NewRecorder()

	comp.handleGraphQL(w, req)

	assert.Equal(t, http.StatusInternalServerError, w.Code)

	// Verify error response is in GraphQL format: {"errors": [...]}
	var response map[string]interface{}
	err = json.Unmarshal(w.Body.Bytes(), &response)
	require.NoError(t, err)

	errors, ok := response["errors"]
	assert.True(t, ok, "error response should have 'errors' field")
	assert.NotNil(t, errors)
}

func TestGateway_HTTPMethodValidation(t *testing.T) {
	comp := createTestGateway(t)
	require.NoError(t, comp.Initialize())
	require.NoError(t, comp.Start(context.Background()))
	defer comp.Stop(5 * time.Second)

	tests := []struct {
		name           string
		method         string
		expectedStatus int
	}{
		{
			name:           "POST allowed",
			method:         http.MethodPost,
			expectedStatus: http.StatusBadRequest, // Bad request due to invalid body, but method is accepted
		},
		{
			name:           "GET not allowed for mutations",
			method:         http.MethodGet,
			expectedStatus: http.StatusMethodNotAllowed,
		},
		{
			name:           "PUT not allowed",
			method:         http.MethodPut,
			expectedStatus: http.StatusMethodNotAllowed,
		},
		{
			name:           "DELETE not allowed",
			method:         http.MethodDelete,
			expectedStatus: http.StatusMethodNotAllowed,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			var bodyReader io.Reader
			if tt.method == http.MethodPost {
				bodyReader = bytes.NewReader([]byte(`{invalid}`)) // Invalid to trigger 400
			}

			req := httptest.NewRequest(tt.method, "/graphql", bodyReader)
			if tt.method == http.MethodPost {
				req.Header.Set("Content-Type", "application/json")
			}
			w := httptest.NewRecorder()

			comp.handleGraphQL(w, req)

			assert.Equal(t, tt.expectedStatus, w.Code)
		})
	}
}

// ====================================================================================
// Inline Argument Extraction Tests
// ====================================================================================

func TestExtractInlineArguments_StringValue(t *testing.T) {
	args := extractInlineArguments(`entity(id: "test")`)
	assert.Equal(t, map[string]interface{}{"id": "test"}, args)
}

func TestExtractInlineArguments_MultipleArgs(t *testing.T) {
	args := extractInlineArguments(`entitiesByPrefix(prefix: "", limit: 5, cursor: "next-page")`)
	assert.Equal(t, "", args["prefix"])
	assert.Equal(t, int64(5), args["limit"])
	assert.Equal(t, "next-page", args["cursor"])
}

func TestExtractInlineArguments_BooleanValue(t *testing.T) {
	args := extractInlineArguments(`search(includeEdges: true)`)
	assert.Equal(t, map[string]interface{}{"includeEdges": true}, args)
}

func TestExtractInlineArguments_NoArgs(t *testing.T) {
	args := extractInlineArguments(`{ entity { id } }`)
	assert.Empty(t, args)
}

func TestExtractInlineArguments_VariableRef(t *testing.T) {
	args := extractInlineArguments(`entity(id: $myId)`)
	assert.Empty(t, args, "variable references should be skipped")
}

func TestExtractInlineArguments_MixedArgsAndVarRefs(t *testing.T) {
	args := extractInlineArguments(`search(query: "drones", limit: $lim)`)
	assert.Equal(t, "drones", args["query"])
	_, hasLimit := args["limit"]
	assert.False(t, hasLimit, "variable ref $lim should be skipped")
}

func TestExtractInlineArguments_EscapedQuotes(t *testing.T) {
	args := extractInlineArguments(`entity(id: "test\"value")`)
	assert.Equal(t, `test"value`, args["id"])
}

func TestExtractInlineArguments_FloatValue(t *testing.T) {
	args := extractInlineArguments(`spatialSearch(north: 45.5)`)
	assert.Equal(t, 45.5, args["north"])
}

func TestExtractInlineArguments_BooleanFalse(t *testing.T) {
	args := extractInlineArguments(`search(includeEdges: false)`)
	assert.Equal(t, false, args["includeEdges"])
}

func TestExtractInlineArguments_EnumValue(t *testing.T) {
	args := extractInlineArguments(`relationships(entityId: "test", direction: OUTGOING)`)
	assert.Equal(t, "test", args["entityId"])
	assert.Equal(t, "OUTGOING", args["direction"])
}

func TestExtractInlineArguments_NullValue(t *testing.T) {
	args := extractInlineArguments(`entity(id: null)`)
	_, hasID := args["id"]
	assert.False(t, hasID, "null values should not appear in result")
}

func TestExtractInlineArguments_SkipsVariableDeclaration(t *testing.T) {
	// The first parens are variable declarations; field args are in the second parens
	args := extractInlineArguments(`query Q($id: String!) { entity(id: "inline-test") { id } }`)
	assert.Equal(t, "inline-test", args["id"])
}

func TestIsIntrospectionQuery_EntityWithSchemaInID(t *testing.T) {
	// Should NOT be treated as introspection
	assert.False(t, isIntrospectionQuery(`{ entity(id: "__schema_config") { id } }`))
}

func TestIsIntrospectionQuery_SchemaQuery(t *testing.T) {
	assert.True(t, isIntrospectionQuery(`{ __schema { types { name } } }`))
}

func TestIsIntrospectionQuery_TypeQuery(t *testing.T) {
	assert.True(t, isIntrospectionQuery(`{ __type(name: "Entity") { name } }`))
}

func TestIsIntrospectionQuery_WithOperationName(t *testing.T) {
	assert.True(t, isIntrospectionQuery(`query IntrospectionQuery { __schema { types { name } } }`))
}

func TestMergeVariables_ExplicitOverridesInline(t *testing.T) {
	inline := map[string]interface{}{"id": "a", "extra": "keep"}
	explicit := map[string]interface{}{"id": "b"}
	merged := mergeVariables(inline, explicit)
	assert.Equal(t, "b", merged["id"], "explicit should override inline")
	assert.Equal(t, "keep", merged["extra"], "non-overlapping inline args should be preserved")
}

func TestMergeVariables_NilExplicit(t *testing.T) {
	inline := map[string]interface{}{"id": "a"}
	merged := mergeVariables(inline, nil)
	assert.Equal(t, "a", merged["id"])
}

func TestMergeVariables_NilInline(t *testing.T) {
	explicit := map[string]interface{}{"id": "b"}
	merged := mergeVariables(nil, explicit)
	assert.Equal(t, "b", merged["id"])
}

// ====================================================================================
// PubAck Detection Tests
// ====================================================================================

func TestIsPubAckResponse_DetectsPubAck(t *testing.T) {
	assert.True(t, isPubAckResponse([]byte(`{"stream":"AGENT","seq":3}`)))
}

func TestIsPubAckResponse_DetectsPubAckWithDomain(t *testing.T) {
	assert.True(t, isPubAckResponse([]byte(`{"stream":"AGENT","seq":3,"domain":"hub"}`)))
}

func TestIsPubAckResponse_DetectsPubAckWithDuplicate(t *testing.T) {
	assert.True(t, isPubAckResponse([]byte(`{"stream":"AGENT","seq":3,"duplicate":true}`)))
}

func TestIsPubAckResponse_NormalResponse(t *testing.T) {
	assert.False(t, isPubAckResponse([]byte(`{"entities":[{"id":"test"}]}`)))
}

func TestIsPubAckResponse_MissingStream(t *testing.T) {
	assert.False(t, isPubAckResponse([]byte(`{"seq":3}`)))
}

func TestIsPubAckResponse_MissingSeq(t *testing.T) {
	assert.False(t, isPubAckResponse([]byte(`{"stream":"AGENT"}`)))
}

func TestIsPubAckResponse_ExtraFields(t *testing.T) {
	assert.False(t, isPubAckResponse([]byte(`{"stream":"AGENT","seq":3,"extra":"field"}`)))
}

func TestIsPubAckResponse_InvalidJSON(t *testing.T) {
	assert.False(t, isPubAckResponse([]byte(`not json`)))
}

func TestGateway_PubAckResponse_ReturnsError(t *testing.T) {
	mock := newMockNATSRequester()

	// Return a PubAck response
	mock.requestFunc = func(ctx context.Context, subject string, data []byte, timeout time.Duration) ([]byte, error) {
		return []byte(`{"stream":"AGENT","seq":3}`), nil
	}

	comp := createTestGatewayWithMock(t, mock)
	require.NoError(t, comp.Initialize())
	require.NoError(t, comp.Start(context.Background()))
	defer comp.Stop(5 * time.Second)

	gqlRequest := map[string]interface{}{
		"query": `query { entity(id: "test") { id } }`,
	}
	body, err := json.Marshal(gqlRequest)
	require.NoError(t, err)

	req := httptest.NewRequest(http.MethodPost, "/graphql", bytes.NewReader(body))
	req.Header.Set("Content-Type", "application/json")
	w := httptest.NewRecorder()

	comp.handleGraphQL(w, req)

	assert.Equal(t, http.StatusBadGateway, w.Code)

	var response map[string]interface{}
	err = json.Unmarshal(w.Body.Bytes(), &response)
	require.NoError(t, err)

	errList, ok := response["errors"].([]interface{})
	require.True(t, ok)
	require.Len(t, errList, 1)
	errMsg := errList[0].(map[string]interface{})["message"].(string)
	assert.Contains(t, errMsg, "stream acknowledgment")
}

// ====================================================================================
// Introspection Tests
// ====================================================================================

func TestGateway_Introspection_Schema(t *testing.T) {
	comp := createTestGateway(t)
	require.NoError(t, comp.Initialize())
	require.NoError(t, comp.Start(context.Background()))
	defer comp.Stop(5 * time.Second)

	gqlRequest := map[string]interface{}{
		"query": `{ __schema { types { name } } }`,
	}
	body, err := json.Marshal(gqlRequest)
	require.NoError(t, err)

	req := httptest.NewRequest(http.MethodPost, "/graphql", bytes.NewReader(body))
	req.Header.Set("Content-Type", "application/json")
	w := httptest.NewRecorder()

	comp.handleGraphQL(w, req)

	assert.Equal(t, http.StatusOK, w.Code)

	var response map[string]interface{}
	err = json.Unmarshal(w.Body.Bytes(), &response)
	require.NoError(t, err)

	data, ok := response["data"].(map[string]interface{})
	require.True(t, ok, "response should have data field")

	schema, ok := data["__schema"].(map[string]interface{})
	require.True(t, ok, "data should have __schema field")

	types, ok := schema["types"].([]interface{})
	require.True(t, ok, "schema should have types field")
	assert.NotEmpty(t, types, "types should not be empty")

	// Verify Query type is present
	found := false
	for _, typ := range types {
		typMap := typ.(map[string]interface{})
		if typMap["name"] == "Query" {
			found = true
			fields, ok := typMap["fields"].([]interface{})
			require.True(t, ok)
			assert.NotEmpty(t, fields, "Query type should have fields")
		}
	}
	assert.True(t, found, "should contain Query type")
}

func TestGateway_Introspection_DoesNotRouteToNATS(t *testing.T) {
	mock := newMockNATSRequester()

	natsCallMade := false
	mock.requestFunc = func(ctx context.Context, subject string, data []byte, timeout time.Duration) ([]byte, error) {
		natsCallMade = true
		return []byte(`{"result":"unexpected"}`), nil
	}

	comp := createTestGatewayWithMock(t, mock)
	require.NoError(t, comp.Initialize())
	require.NoError(t, comp.Start(context.Background()))
	defer comp.Stop(5 * time.Second)

	gqlRequest := map[string]interface{}{
		"query": `{ __schema { queryType { name } } }`,
	}
	body, err := json.Marshal(gqlRequest)
	require.NoError(t, err)

	req := httptest.NewRequest(http.MethodPost, "/graphql", bytes.NewReader(body))
	req.Header.Set("Content-Type", "application/json")
	w := httptest.NewRecorder()

	comp.handleGraphQL(w, req)

	assert.Equal(t, http.StatusOK, w.Code)
	assert.False(t, natsCallMade, "introspection should not make NATS request")
}

func TestGateway_Introspection_Type(t *testing.T) {
	comp := createTestGateway(t)
	require.NoError(t, comp.Initialize())
	require.NoError(t, comp.Start(context.Background()))
	defer comp.Stop(5 * time.Second)

	gqlRequest := map[string]interface{}{
		"query": `{ __type(name: "Entity") { name fields { name } } }`,
	}
	body, err := json.Marshal(gqlRequest)
	require.NoError(t, err)

	req := httptest.NewRequest(http.MethodPost, "/graphql", bytes.NewReader(body))
	req.Header.Set("Content-Type", "application/json")
	w := httptest.NewRecorder()

	comp.handleGraphQL(w, req)

	assert.Equal(t, http.StatusOK, w.Code)

	var response map[string]interface{}
	err = json.Unmarshal(w.Body.Bytes(), &response)
	require.NoError(t, err)

	data, ok := response["data"].(map[string]interface{})
	require.True(t, ok, "response should have data field")

	// Should be __type, not __schema
	typeResult, ok := data["__type"].(map[string]interface{})
	require.True(t, ok, "data should have __type field, not __schema")
	assert.Equal(t, "Entity", typeResult["name"])
}

// ====================================================================================
// Integration Tests: Inline Args Flow Through Gateway
// ====================================================================================

func TestGateway_InlineArgs_EntityQuery(t *testing.T) {
	mock := newMockNATSRequester()

	mock.requestFunc = func(ctx context.Context, subject string, data []byte, timeout time.Duration) ([]byte, error) {
		assert.Equal(t, "graph.query.entity", subject)

		var payload map[string]interface{}
		err := json.Unmarshal(data, &payload)
		require.NoError(t, err)

		assert.Equal(t, "acme.ops.test.graph.entity.001", payload["id"], "inline id should be extracted and sent in payload")

		return []byte(`{"id":"acme.ops.test.graph.entity.001","triples":[]}`), nil
	}

	comp := createTestGatewayWithMock(t, mock)
	require.NoError(t, comp.Initialize())
	require.NoError(t, comp.Start(context.Background()))
	defer comp.Stop(5 * time.Second)

	gqlRequest := map[string]interface{}{
		"query": `{ entity(id: "acme.ops.test.graph.entity.001") { id } }`,
	}
	body, err := json.Marshal(gqlRequest)
	require.NoError(t, err)

	req := httptest.NewRequest(http.MethodPost, "/graphql", bytes.NewReader(body))
	req.Header.Set("Content-Type", "application/json")
	w := httptest.NewRecorder()

	comp.handleGraphQL(w, req)

	assert.Equal(t, http.StatusOK, w.Code)
}

func TestGateway_InlineArgs_PrefixQuery(t *testing.T) {
	mock := newMockNATSRequester()

	mock.requestFunc = func(ctx context.Context, subject string, data []byte, timeout time.Duration) ([]byte, error) {
		assert.Equal(t, "graph.query.prefix", subject)

		var payload map[string]interface{}
		err := json.Unmarshal(data, &payload)
		require.NoError(t, err)

		assert.Equal(t, "", payload["prefix"], "inline empty prefix should be extracted")
		assert.Equal(t, float64(5), payload["limit"], "inline limit should be extracted")
		assert.Equal(t, "next-page", payload["cursor"], "inline cursor should be forwarded")

		return []byte(`{"entities":[{"id":"acme.ops.test.system.widget.001"},{"id":"acme.ops.test.system.widget.002"}],"next_cursor":"after-page"}`), nil
	}

	comp := createTestGatewayWithMock(t, mock)
	require.NoError(t, comp.Initialize())
	require.NoError(t, comp.Start(context.Background()))
	defer comp.Stop(5 * time.Second)

	gqlRequest := map[string]interface{}{
		"query": `{ entitiesByPrefix(prefix: "", limit: 5, cursor: "next-page") { entities { id } next_cursor } }`,
	}
	body, err := json.Marshal(gqlRequest)
	require.NoError(t, err)

	req := httptest.NewRequest(http.MethodPost, "/graphql", bytes.NewReader(body))
	req.Header.Set("Content-Type", "application/json")
	w := httptest.NewRecorder()

	comp.handleGraphQL(w, req)

	assert.Equal(t, http.StatusOK, w.Code)
	assert.JSONEq(t,
		`{"data":{"entitiesByPrefix":{"entities":[{"id":"acme.ops.test.system.widget.001"},{"id":"acme.ops.test.system.widget.002"}],"next_cursor":"after-page"}}}`,
		w.Body.String(),
	)
}

// TestGateway_PrefixQueryLeavesOmittedLimitToResultOwner proves the gateway
// does not predict a carrier-safe count. Graph-ingest owns the count default
// and exact encoded-page fitting against the active NATS limit.
func TestGateway_PrefixQueryLeavesOmittedLimitToResultOwner(t *testing.T) {
	mock := newMockNATSRequester()

	mock.requestFunc = func(_ context.Context, subject string, data []byte, _ time.Duration) ([]byte, error) {
		assert.Equal(t, "graph.query.prefix", subject)

		var payload map[string]interface{}
		require.NoError(t, json.Unmarshal(data, &payload))

		_, hasLimit := payload["limit"]
		assert.False(t, hasLimit, "gateway must not invent a carrier-size prediction")

		return []byte(`{"entities":[]}`), nil
	}

	comp := createTestGatewayWithMock(t, mock)
	require.NoError(t, comp.Initialize())
	require.NoError(t, comp.Start(context.Background()))
	defer comp.Stop(5 * time.Second)

	gqlRequest := map[string]interface{}{
		"query": `{ entitiesByPrefix(prefix: "test") { entities { id } next_cursor } }`,
	}
	body, err := json.Marshal(gqlRequest)
	require.NoError(t, err)

	req := httptest.NewRequest(http.MethodPost, "/graphql", bytes.NewReader(body))
	req.Header.Set("Content-Type", "application/json")
	w := httptest.NewRecorder()

	comp.handleGraphQL(w, req)
	assert.Equal(t, http.StatusOK, w.Code)
}

// TestGateway_PrefixQuery_ExplicitLimitOverridesDefault pins the
// inverse — when the caller sets `limit` explicitly, the gateway must
// NOT clobber it with the default. Up to graph-ingest's internal cap.
func TestGateway_PrefixQuery_ExplicitLimitOverridesDefault(t *testing.T) {
	mock := newMockNATSRequester()

	mock.requestFunc = func(_ context.Context, _ string, data []byte, _ time.Duration) ([]byte, error) {
		var payload map[string]interface{}
		require.NoError(t, json.Unmarshal(data, &payload))
		assert.Equal(t, float64(500), payload["limit"],
			"explicit caller limit must override the gateway default")
		return []byte(`{"entities":[]}`), nil
	}

	comp := createTestGatewayWithMock(t, mock)
	require.NoError(t, comp.Initialize())
	require.NoError(t, comp.Start(context.Background()))
	defer comp.Stop(5 * time.Second)

	gqlRequest := map[string]interface{}{
		"query": `{ entitiesByPrefix(prefix: "test", limit: 500) { entities { id } next_cursor } }`,
	}
	body, err := json.Marshal(gqlRequest)
	require.NoError(t, err)

	req := httptest.NewRequest(http.MethodPost, "/graphql", bytes.NewReader(body))
	req.Header.Set("Content-Type", "application/json")
	w := httptest.NewRecorder()

	comp.handleGraphQL(w, req)
	assert.Equal(t, http.StatusOK, w.Code)
}

func TestGateway_PrefixQueriesRejectInvalidPrefixBeforeNATS(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name    string
		subject string
		query   string
	}{
		{name: "entities by prefix", subject: "graph.query.prefix", query: `{ entitiesByPrefix(prefix: "acme.*") { entities { id } next_cursor } }`},
		{name: "hierarchy stats", subject: "graph.query.hierarchyStats", query: `{ entityIdHierarchy(prefix: "acme.*") { prefix } }`},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			validationErr := validateGatewayPrefixPayload(tt.subject, map[string]interface{}{"prefix": "acme.*"})
			require.Error(t, validationErr)
			var classified *semerrs.ClassifiedError
			require.ErrorAs(t, validationErr, &classified)
			assert.Equal(t, semtypes.ErrorCodeEntityIDPrefixInvalid, classified.Code)

			requestCalls := 0
			mock := newMockNATSRequester()
			mock.requestFunc = func(context.Context, string, []byte, time.Duration) ([]byte, error) {
				requestCalls++
				return nil, errors.New("unexpected NATS request")
			}

			comp := createTestGatewayWithMock(t, mock)
			body, err := json.Marshal(map[string]interface{}{"query": tt.query})
			require.NoError(t, err)
			req := httptest.NewRequest(http.MethodPost, "/graphql", bytes.NewReader(body))
			w := httptest.NewRecorder()

			comp.handleGraphQL(w, req)

			assert.Equal(t, http.StatusBadRequest, w.Code)
			assert.Zero(t, requestCalls, "invalid prefix must fail before NATS request")
			assert.Contains(t, w.Body.String(), "invalid entity ID contract input")
		})
	}
}

func TestGateway_InlineArgs_ExplicitVariablesOverrideInline(t *testing.T) {
	mock := newMockNATSRequester()

	mock.requestFunc = func(ctx context.Context, subject string, data []byte, timeout time.Duration) ([]byte, error) {
		var payload map[string]interface{}
		err := json.Unmarshal(data, &payload)
		require.NoError(t, err)

		// Explicit variable should override inline
		assert.Equal(t, "explicit.id", payload["id"], "explicit variable should override inline arg")

		return []byte(`{"id":"explicit.id"}`), nil
	}

	comp := createTestGatewayWithMock(t, mock)
	require.NoError(t, comp.Initialize())
	require.NoError(t, comp.Start(context.Background()))
	defer comp.Stop(5 * time.Second)

	gqlRequest := map[string]interface{}{
		"query":     `{ entity(id: "inline.id") { id } }`,
		"variables": map[string]interface{}{"id": "explicit.id"},
	}
	body, err := json.Marshal(gqlRequest)
	require.NoError(t, err)

	req := httptest.NewRequest(http.MethodPost, "/graphql", bytes.NewReader(body))
	req.Header.Set("Content-Type", "application/json")
	w := httptest.NewRecorder()

	comp.handleGraphQL(w, req)

	assert.Equal(t, http.StatusOK, w.Code)
}

func TestGateway_InlineArgs_RelationshipsQuery(t *testing.T) {
	mock := newMockNATSRequester()

	mock.requestFunc = func(ctx context.Context, subject string, data []byte, timeout time.Duration) ([]byte, error) {
		assert.Equal(t, "graph.query.relationships", subject)

		var payload map[string]interface{}
		err := json.Unmarshal(data, &payload)
		require.NoError(t, err)

		assert.Equal(t, "acme.ops.test.graph.entity.001", payload["entity_id"], "inline entityId should map to entity_id in payload")

		return []byte(`[{"from":"acme.ops.test.graph.entity.001","to":"acme.ops.test.graph.entity.002","predicate":"social.relationship.knows"}]`), nil
	}

	comp := createTestGatewayWithMock(t, mock)
	require.NoError(t, comp.Initialize())
	require.NoError(t, comp.Start(context.Background()))
	defer comp.Stop(5 * time.Second)

	gqlRequest := map[string]interface{}{
		"query": `{ relationships(entityId: "acme.ops.test.graph.entity.001") { from to predicate } }`,
	}
	body, err := json.Marshal(gqlRequest)
	require.NoError(t, err)

	req := httptest.NewRequest(http.MethodPost, "/graphql", bytes.NewReader(body))
	req.Header.Set("Content-Type", "application/json")
	w := httptest.NewRecorder()

	comp.handleGraphQL(w, req)

	assert.Equal(t, http.StatusOK, w.Code)
}

// ====================================================================================
// Helper Functions
// ====================================================================================

// createTestGateway creates a basic test gateway with mock NATS client
func createTestGateway(t *testing.T) *Component {
	t.Helper()

	mock := newMockNATSRequester()
	return createTestGatewayWithMock(t, mock)
}

// createTestGatewayWithMock creates a test gateway with provided mock client
func TestGateway_TransformPathSearchVars(t *testing.T) {
	comp := &Component{}

	tests := []struct {
		name     string
		vars     map[string]interface{}
		expected map[string]interface{}
	}{
		{
			name: "direction forwarded and lowercased",
			vars: map[string]interface{}{
				"startEntity": "a.b.c.d.e.f",
				"direction":   "OUTGOING",
			},
			expected: map[string]interface{}{
				"start_entity": "a.b.c.d.e.f",
				"direction":    "outgoing",
			},
		},
		{
			name: "predicates array forwarded",
			vars: map[string]interface{}{
				"startEntity": "a.b.c.d.e.f",
				"predicates":  []interface{}{"relationship.graph.connects", "relationship.graph.depends"},
			},
			expected: map[string]interface{}{
				"start_entity": "a.b.c.d.e.f",
				"predicates":   []interface{}{"relationship.graph.connects", "relationship.graph.depends"},
			},
		},
		{
			name: "timeout string forwarded",
			vars: map[string]interface{}{
				"startEntity": "a.b.c.d.e.f",
				"timeout":     "10s",
			},
			expected: map[string]interface{}{
				"start_entity": "a.b.c.d.e.f",
				"timeout":      "10s",
			},
		},
		{
			name: "maxPaths forwarded as max_paths",
			vars: map[string]interface{}{
				"startEntity": "a.b.c.d.e.f",
				"maxPaths":    float64(50),
			},
			expected: map[string]interface{}{
				"start_entity": "a.b.c.d.e.f",
				"max_paths":    float64(50),
			},
		},
		{
			name: "omitted params not in payload",
			vars: map[string]interface{}{
				"startEntity": "a.b.c.d.e.f",
			},
			expected: map[string]interface{}{
				"start_entity": "a.b.c.d.e.f",
			},
		},
		{
			name: "all params together",
			vars: map[string]interface{}{
				"startEntity": "a.b.c.d.e.f",
				"maxDepth":    float64(5),
				"maxNodes":    float64(100),
				"direction":   "Incoming",
				"predicates":  []interface{}{"relationship.graph.owns"},
				"timeout":     "30s",
				"maxPaths":    float64(10),
			},
			expected: map[string]interface{}{
				"start_entity": "a.b.c.d.e.f",
				"max_depth":    float64(5),
				"max_nodes":    float64(100),
				"direction":    "incoming",
				"predicates":   []interface{}{"relationship.graph.owns"},
				"timeout":      "30s",
				"max_paths":    float64(10),
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := comp.transformPathSearchVars(tt.vars)
			assert.Equal(t, tt.expected, result)
		})
	}
}

// ====================================================================================
// Trajectory Limit Tests
// ====================================================================================

func TestGateway_TrajectoryQueryForwardsCursorAndPreservesReferencePage(t *testing.T) {
	mock := newMockNATSRequester()

	var capturedPayload map[string]interface{}
	mock.requestFunc = func(ctx context.Context, subject string, data []byte, timeout time.Duration) ([]byte, error) {
		_ = json.Unmarshal(data, &capturedPayload)
		return []byte(`{"schema_version":"v1","loop_id":"loop-1","coverage":"observed","observed_totals":{"facts":1},"terminal_observed":false,"facts":[{"attempt_id":"attempt1","evidence_capture":"stored","evidence":{"storage_instance":"objectstore","key":"trajectory-evidence/v1/sha256/abc","content_type":"application/vnd.semstreams.agentic-trajectory-evidence.v1+json","size":42}}],"next_cursor":"next-page"}`), nil
	}

	comp := createTestGatewayWithMock(t, mock)
	require.NoError(t, comp.Initialize())
	require.NoError(t, comp.Start(context.Background()))
	defer comp.Stop(5 * time.Second)

	gqlRequest := map[string]interface{}{
		"query": `{ trajectory(loopId: "loop-1", limit: 10, cursor: "current-page") { loop_id coverage observed_totals terminal_observed facts { attempt_id evidence_capture evidence { storage_instance key content_type size } } next_cursor } }`,
	}
	body, err := json.Marshal(gqlRequest)
	require.NoError(t, err)

	req := httptest.NewRequest(http.MethodPost, "/graphql", bytes.NewReader(body))
	req.Header.Set("Content-Type", "application/json")
	w := httptest.NewRecorder()

	comp.handleGraphQL(w, req)

	assert.Equal(t, http.StatusOK, w.Code)
	assert.Equal(t, "loop-1", capturedPayload["loopId"])
	assert.Equal(t, float64(10), capturedPayload["limit"])
	assert.Equal(t, "current-page", capturedPayload["cursor"])
	assert.NotContains(t, capturedPayload, "hydrateEvidence")
	assert.Contains(t, w.Body.String(), `"coverage":"observed"`)
	assert.Contains(t, w.Body.String(), `"next_cursor":"next-page"`)
	assert.Contains(t, w.Body.String(), `"storage_instance":"objectstore"`)
	assert.NotContains(t, w.Body.String(), "evidence_body")
}

func TestGateway_TrajectoryQueryRejectsHydrateEvidence(t *testing.T) {
	mock := newMockNATSRequester()
	called := false
	mock.requestFunc = func(context.Context, string, []byte, time.Duration) ([]byte, error) {
		called = true
		return nil, nil
	}

	comp := createTestGatewayWithMock(t, mock)
	require.NoError(t, comp.Initialize())
	require.NoError(t, comp.Start(context.Background()))
	defer comp.Stop(5 * time.Second)

	body, err := json.Marshal(map[string]interface{}{
		"query": `{ trajectory(loopId: "loop-1", hydrateEvidence: true) { facts { attempt_id } } }`,
	})
	require.NoError(t, err)
	req := httptest.NewRequest(http.MethodPost, "/graphql", bytes.NewReader(body))
	req.Header.Set("Content-Type", "application/json")
	w := httptest.NewRecorder()

	comp.handleGraphQL(w, req)

	assert.Equal(t, http.StatusBadRequest, w.Code)
	assert.False(t, called)
}

// ====================================================================================
// Unknown Query Fast-Fail Tests
// ====================================================================================

func TestGateway_UnknownQuery_ReturnsBadRequest(t *testing.T) {
	mock := newMockNATSRequester()

	natsWasCalled := false
	mock.requestFunc = func(ctx context.Context, subject string, data []byte, timeout time.Duration) ([]byte, error) {
		natsWasCalled = true
		return nil, errors.New("no responders available")
	}

	comp := createTestGatewayWithMock(t, mock)
	require.NoError(t, comp.Initialize())
	require.NoError(t, comp.Start(context.Background()))
	defer comp.Stop(5 * time.Second)

	gqlRequest := map[string]interface{}{
		"query": `query { unknownOperation { data } }`,
	}
	body, err := json.Marshal(gqlRequest)
	require.NoError(t, err)

	req := httptest.NewRequest(http.MethodPost, "/graphql", bytes.NewReader(body))
	req.Header.Set("Content-Type", "application/json")
	w := httptest.NewRecorder()

	comp.handleGraphQL(w, req)

	// Should return 400 immediately, NOT dispatch to NATS
	assert.Equal(t, http.StatusBadRequest, w.Code)
	assert.False(t, natsWasCalled, "should not dispatch unknown queries to NATS")

	var response map[string]interface{}
	err = json.Unmarshal(w.Body.Bytes(), &response)
	require.NoError(t, err)

	errs, ok := response["errors"]
	assert.True(t, ok, "response should have 'errors' field")
	assert.NotNil(t, errs)
}

func TestGateway_TransformPredicateVarsWithValue(t *testing.T) {
	comp := &Component{}

	tests := []struct {
		name     string
		vars     map[string]interface{}
		expected map[string]interface{}
	}{
		{
			name: "predicate with value forwarded",
			vars: map[string]interface{}{
				"predicate": "robotics.battery.level",
				"value":     "15",
				"limit":     float64(10),
			},
			expected: map[string]interface{}{
				"predicate": "robotics.battery.level",
				"value":     "15",
				"limit":     float64(10),
			},
		},
		{
			name: "predicate without value",
			vars: map[string]interface{}{
				"predicate": "robotics.type.drone",
			},
			expected: map[string]interface{}{
				"predicate": "robotics.type.drone",
			},
		},
		{
			name: "predicate with value and no limit",
			vars: map[string]interface{}{
				"predicate": "robotics.battery.level",
				"value":     "critical",
			},
			expected: map[string]interface{}{
				"predicate": "robotics.battery.level",
				"value":     "critical",
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := comp.transformVariablesToNATSPayload(tt.vars, "graph.index.query.predicate")
			assert.Equal(t, tt.expected, result)
		})
	}
}

// ====================================================================================
// writeGraphQLSuccessWithExtensions tests
// ====================================================================================

func TestWriteGraphQLSuccessWithExtensions_IncludesExtensions(t *testing.T) {
	comp := createTestGateway(t)

	w := httptest.NewRecorder()
	extensions := map[string]interface{}{
		"classification": map[string]interface{}{
			"tier":       1,
			"confidence": 0.92,
			"intent":     "entity_lookup",
		},
	}

	comp.writeGraphQLSuccessWithExtensions(w, "graph.query.globalSearch", []byte(`{"results":[]}`), extensions)

	assert.Equal(t, http.StatusOK, w.Code)
	assert.Equal(t, "application/json", w.Header().Get("Content-Type"))

	var body map[string]interface{}
	require.NoError(t, json.Unmarshal(w.Body.Bytes(), &body))

	// extensions field must be present
	ext, ok := body["extensions"]
	require.True(t, ok, "response must contain 'extensions' field")
	require.NotNil(t, ext)

	extMap, ok := ext.(map[string]interface{})
	require.True(t, ok, "'extensions' must be an object")

	classification, ok := extMap["classification"]
	require.True(t, ok, "'extensions.classification' must be present")

	classMap, ok := classification.(map[string]interface{})
	require.True(t, ok, "'extensions.classification' must be an object")

	assert.Equal(t, float64(1), classMap["tier"])
	assert.InDelta(t, 0.92, classMap["confidence"], 0.001)
	assert.Equal(t, "entity_lookup", classMap["intent"])

	// data field must also be present
	_, ok = body["data"]
	assert.True(t, ok, "response must contain 'data' field")
}

func TestWriteGraphQLSuccessWithExtensions_OmitsWhenNil(t *testing.T) {
	comp := createTestGateway(t)

	w := httptest.NewRecorder()
	comp.writeGraphQLSuccessWithExtensions(w, "graph.query.globalSearch", []byte(`{"results":[]}`), nil)

	assert.Equal(t, http.StatusOK, w.Code)

	var body map[string]interface{}
	require.NoError(t, json.Unmarshal(w.Body.Bytes(), &body))

	_, hasExtensions := body["extensions"]
	assert.False(t, hasExtensions, "nil extensions must not produce an 'extensions' field")
}

func TestWriteGraphQLSuccessWithExtensions_OmitsWhenEmpty(t *testing.T) {
	comp := createTestGateway(t)

	w := httptest.NewRecorder()
	comp.writeGraphQLSuccessWithExtensions(w, "graph.query.globalSearch", []byte(`{"results":[]}`), map[string]interface{}{})

	assert.Equal(t, http.StatusOK, w.Code)

	var body map[string]interface{}
	require.NoError(t, json.Unmarshal(w.Body.Bytes(), &body))

	_, hasExtensions := body["extensions"]
	assert.False(t, hasExtensions, "empty extensions map must not produce an 'extensions' field")
}

func TestWriteGraphQLSuccess_DelegatesToWithExtensions(t *testing.T) {
	comp := createTestGateway(t)

	// Call the original helper (no extensions).
	wOld := httptest.NewRecorder()
	comp.writeGraphQLSuccess(wOld, "graph.query.entity", []byte(`{"id":"x"}`))

	// Call the new helper with nil extensions — must produce identical output.
	wNew := httptest.NewRecorder()
	comp.writeGraphQLSuccessWithExtensions(wNew, "graph.query.entity", []byte(`{"id":"x"}`), nil)

	assert.Equal(t, wOld.Code, wNew.Code, "status codes must match")
	assert.Equal(t, wOld.Header().Get("Content-Type"), wNew.Header().Get("Content-Type"), "content-type must match")

	var oldBody, newBody map[string]interface{}
	require.NoError(t, json.Unmarshal(wOld.Body.Bytes(), &oldBody))
	require.NoError(t, json.Unmarshal(wNew.Body.Bytes(), &newBody))
	assert.Equal(t, oldBody, newBody, "response bodies must be identical for nil extensions")
}

func createTestGatewayWithMock(t *testing.T, mock *mockNATSRequester) *Component {
	t.Helper()

	config := DefaultConfig()
	outputs := make([]component.Port, 0, len(config.Ports.Outputs))
	for _, definition := range config.Ports.Outputs {
		port, err := definition.Resolve(component.DirectionOutput)
		require.NoError(t, err)
		outputs = append(outputs, port)
	}
	families, err := queryFamiliesFromPorts(outputs)
	require.NoError(t, err)

	// Create component with injected mock
	// Note: Builder must implement a way to inject mock for testing
	// Following the pattern from graph-query tests
	comp := &Component{
		name:          "graph-gateway",
		config:        config,
		outputs:       outputs,
		queries:       families,
		natsRequester: mock, // Builder will add this field for NATS request/reply
		logger:        createTestLogger(),
	}

	comp.lastActivity.Store(time.Now())

	return comp
}

// createTestLogger creates a logger for testing
func createTestLogger() *slog.Logger {
	return slog.Default()
}

// ====================================================================================
// GlobalSearch Schema Enrichment Tests
// ====================================================================================

// TestTransformGlobalSearchVars_IncludeFlags verifies that the three new boolean
// flags are forwarded to the backend payload under snake_case keys.
func TestTransformGlobalSearchVars_IncludeFlags(t *testing.T) {
	comp := &Component{}

	tests := []struct {
		name     string
		vars     map[string]interface{}
		expected map[string]interface{}
	}{
		{
			name: "includeSummaries maps to include_summaries",
			vars: map[string]interface{}{
				"query":            "find drones near Houston",
				"includeSummaries": true,
			},
			expected: map[string]interface{}{
				"query":             "find drones near Houston",
				"include_summaries": true,
			},
		},
		{
			name: "includeRelationships maps to include_relationships",
			vars: map[string]interface{}{
				"query":                "network topology",
				"includeRelationships": false,
			},
			expected: map[string]interface{}{
				"query":                 "network topology",
				"include_relationships": false,
			},
		},
		{
			name: "includeSources maps to include_sources",
			vars: map[string]interface{}{
				"query":          "supply chain risk",
				"includeSources": true,
			},
			expected: map[string]interface{}{
				"query":           "supply chain risk",
				"include_sources": true,
			},
		},
		{
			name: "all three flags together with existing args",
			vars: map[string]interface{}{
				"query":                "multi-hop community search",
				"level":                float64(2),
				"maxCommunities":       float64(10),
				"includeSummaries":     true,
				"includeRelationships": true,
				"includeSources":       false,
			},
			expected: map[string]interface{}{
				"query":                 "multi-hop community search",
				"level":                 float64(2),
				"max_communities":       float64(10),
				"include_summaries":     true,
				"include_relationships": true,
				"include_sources":       false,
			},
		},
		{
			name: "omitted flags not present in payload",
			vars: map[string]interface{}{
				"query": "minimal global search",
			},
			expected: map[string]interface{}{
				"query": "minimal global search",
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := comp.transformGlobalSearchVars(tt.vars)
			assert.Equal(t, tt.expected, result)
		})
	}
}

// TestBuildIntrospectionSchema_GlobalSearchResult verifies that GlobalSearchResult
// is present in the schema with all expected fields.
func TestBuildIntrospectionSchema_GlobalSearchResult(t *testing.T) {
	schema := buildIntrospectionSchema()

	types, ok := schema["types"].([]map[string]interface{})
	require.True(t, ok, "schema must have a types slice")

	var globalSearchResult map[string]interface{}
	for _, td := range types {
		if td["name"] == "GlobalSearchResult" {
			globalSearchResult = td
			break
		}
	}
	require.NotNil(t, globalSearchResult, "GlobalSearchResult type must exist in schema")
	assert.Equal(t, "OBJECT", globalSearchResult["kind"])

	fields, ok := globalSearchResult["fields"].([]map[string]interface{})
	require.True(t, ok, "GlobalSearchResult must have a fields slice")

	fieldNames := make([]string, 0, len(fields))
	for _, f := range fields {
		fieldNames = append(fieldNames, f["name"].(string))
	}

	expectedFields := []string{"entities", "community_summaries", "relationships", "sources", "count", "duration_ms", "answer", "answer_model", "degraded", "degraded_reason"}
	for _, expected := range expectedFields {
		assert.Contains(t, fieldNames, expected, "GlobalSearchResult should contain field %q", expected)
	}
}

// TestBuildIntrospectionSchema_LocalSearchResult verifies that LocalSearchResult
// is present in the schema with all expected fields.
func TestBuildIntrospectionSchema_LocalSearchResult(t *testing.T) {
	schema := buildIntrospectionSchema()

	types, ok := schema["types"].([]map[string]interface{})
	require.True(t, ok, "schema must have a types slice")

	var localSearchResult map[string]interface{}
	for _, td := range types {
		if td["name"] == "LocalSearchResult" {
			localSearchResult = td
			break
		}
	}
	require.NotNil(t, localSearchResult, "LocalSearchResult type must exist in schema")
	assert.Equal(t, "OBJECT", localSearchResult["kind"])

	fields, ok := localSearchResult["fields"].([]map[string]interface{})
	require.True(t, ok, "LocalSearchResult must have a fields slice")

	fieldNames := make([]string, 0, len(fields))
	for _, f := range fields {
		fieldNames = append(fieldNames, f["name"].(string))
	}

	expectedFields := []string{"entities", "communityId", "count", "durationMs", "degraded", "degraded_reason"}
	for _, expected := range expectedFields {
		assert.Contains(t, fieldNames, expected, "LocalSearchResult should contain field %q", expected)
	}
}

// TestBuildIntrospectionSchema_GlobalSearchArgs verifies that the globalSearch
// query field exposes all 6 expected arguments in the schema.
func TestBuildIntrospectionSchema_GlobalSearchArgs(t *testing.T) {
	schema := buildIntrospectionSchema()

	types, ok := schema["types"].([]map[string]interface{})
	require.True(t, ok, "schema must have a types slice")

	// Find the Query type.
	var queryType map[string]interface{}
	for _, td := range types {
		if td["name"] == "Query" {
			queryType = td
			break
		}
	}
	require.NotNil(t, queryType, "Query type must exist in schema")

	fields, ok := queryType["fields"].([]map[string]interface{})
	require.True(t, ok, "Query type must have a fields slice")

	// Find the globalSearch field.
	var globalSearchField map[string]interface{}
	for _, f := range fields {
		if f["name"] == "globalSearch" {
			globalSearchField = f
			break
		}
	}
	require.NotNil(t, globalSearchField, "globalSearch field must exist on Query type")

	args, ok := globalSearchField["args"].([]map[string]interface{})
	require.True(t, ok, "globalSearch must have args slice")

	argNames := make([]string, 0, len(args))
	for _, a := range args {
		argNames = append(argNames, a["name"].(string))
	}

	expectedArgs := []string{"query", "level", "maxCommunities", "summarizeThreshold", "includeSummaries", "includeRelationships", "includeSources"}
	assert.Len(t, argNames, len(expectedArgs), "globalSearch should have exactly %d args", len(expectedArgs))
	for _, expected := range expectedArgs {
		assert.Contains(t, argNames, expected, "globalSearch should have arg %q", expected)
	}
}

// TestGateway_MapGraphQLToNATSSubject_NestedSelectionRouting locks in the
// gh#206 fix: composite resolvers whose result type carries field names
// that ALSO match generic single-resolver substring checks must route to
// the composite, not get hijacked by the substring collision in the
// selection set.
//
// Before the gh#206 fix, the routing function ran the generic
// `relationships` substring check BEFORE the composite search checks.
// A `globalSearch` query with a nested `relationships { from to }`
// selection therefore routed to `graph.query.relationships`, which
// then bailed with `empty entity_id` because there was no
// `relationships(entityId: ...)` arg in scope. semconnect's demo UI
// surfaced it; the fix reorders the checks so composites win.
//
// Same shape bug also affects `searchGraph` and `localSearch` (both
// return `GlobalSearchResult` which carries `relationships`), so all
// three are covered. The inverse — bare `relationships(entityId)` queries
// must still route to their dedicated subject after the reorder — is locked
// by the regression-safe case.
func TestGateway_MapGraphQLToNATSSubject_NestedSelectionRouting(t *testing.T) {
	comp := createTestGateway(t)

	tests := []struct {
		name            string
		query           string
		expectedSubject string
	}{
		// gh#206 reproducer — globalSearch with nested relationships
		// selection. Pre-fix routed to graph.query.relationships; post-fix
		// must route to graph.query.globalSearch.
		{
			name: "gh#206 -- globalSearch with nested relationships",
			query: `query GlobalSearch($query: String!) {
				globalSearch(query: $query) {
					entities { id }
					relationships { from to predicate }
					count
					duration_ms
				}
			}`,
			expectedSubject: "graph.query.globalSearch",
		},
		// searchGraph returns GlobalSearchResult (same as globalSearch),
		// so the same nested-relationships hijack applies. Lock here.
		{
			name: "gh#206 -- searchGraph with nested relationships",
			query: `query SearchGraph($query: String!) {
				searchGraph(query: $query) {
					entities { id }
					relationships { from to predicate }
					count
				}
			}`,
			expectedSubject: "graph.query.searchGraph",
		},
		// localSearch is the third GraphRAG composite. Same shape.
		{
			name: "gh#206 -- localSearch with nested relationships",
			query: `query LocalSearch($query: String!, $entity: String!) {
				localSearch(query: $query, anchor_entity: $entity) {
					entities { id }
					relationships { from to predicate }
					count
				}
			}`,
			expectedSubject: "graph.query.localSearch",
		},
		// Inverse — a bare relationships(entityId) query must still
		// route to graph.query.relationships after the reorder. The fix
		// is about composite-precedence, not removing the relationships
		// route entirely.
		{
			name: "regression-safe -- bare relationships(entityId) routes correctly",
			query: `query Relationships($id: String!) {
				relationships(entityId: $id, direction: "out") {
					from to predicate
				}
			}`,
			expectedSubject: "graph.query.relationships",
		},
		// Defensive: GlobalSearchResult also carries `sources` —
		// neither has a generic substring check today, but a future
		// developer who adds one would hit the same class of bug. This
		// case documents the discipline: any new substring check for a
		// name that appears in a composite's result type must be
		// positioned AFTER the composites.
		{
			name: "defensive -- globalSearch with nested sources",
			query: `query GlobalSearch($query: String!) {
				globalSearch(query: $query) {
					entities { id }
					sources { id }
					count
				}
			}`,
			expectedSubject: "graph.query.globalSearch",
		},
		// Argument-name collision class (gh#206 review I2): a
		// globalSearch call with `includeRelationships: true` arg
		// lowercases to a string containing the `relationships`
		// substring. The pre-fix routing would have hijacked this
		// even without nested result-field selections. Lock against
		// future regression.
		{
			name: "gh#206 class -- globalSearch with includeRelationships arg",
			query: `query {
				globalSearch(query: "x", includeRelationships: true) {
					entities { id }
				}
			}`,
			expectedSubject: "graph.query.globalSearch",
		},
		// pathSearch + predicates arg — accidental safety in the
		// pre-fix code because `pathsearch` was checked in the "most
		// specific" tier above the `predicates` substring check. Post-
		// fix (review I1) pathSearch lives in the composite block;
		// this case locks the structural placement so the next
		// reshuffle doesn't reintroduce the collision.
		{
			name: "gh#206 class -- pathSearch with predicates arg",
			query: `query {
				pathSearch(startEntity: "x", predicates: ["a", "b"]) {
					entities { id }
					edges { from to }
				}
			}`,
			expectedSubject: "graph.query.pathSearch",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			subject := comp.mapGraphQLQueryToNATSSubject(tt.query)
			assert.Equal(t, tt.expectedSubject, subject)
		})
	}
}
