// Code generated by Reviewer Agent. DO NOT EDIT.
// Attack tests — permanent CI fixtures.

package graphquery

import (
	"context"
	"encoding/json"
	"errors"
	"runtime"
	"strings"
	"testing"
	"time"

	"github.com/c360studio/semstreams/internal/semantictest"
	"github.com/c360studio/semstreams/natsclient"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// ====================================================================================
// Attack Vector: Nil/Zero Values
// ====================================================================================

func TestAttack_NilConfig(t *testing.T) {
	mockClient := newMockNATSClient()

	comp := &Component{
		config:     Config{Ports: nil}, // nil ports
		natsClient: mockClient,
	}

	// Should not panic, should return error
	err := comp.Initialize()
	assert.Error(t, err, "nil config should fail validation")
}

func TestAttack_NilContext(t *testing.T) {
	comp := createTestComponent(t)
	require.NoError(t, comp.Initialize())

	// Nil context should return an error, not panic
	// This validates proper context validation before use
	err := comp.Start(nil)
	require.Error(t, err, "nil context should return error")
	assert.Contains(t, err.Error(), "context cannot be nil", "error should indicate nil context")
}

func TestAttack_ZeroTimeout(t *testing.T) {
	config := DefaultConfig()
	config.QueryTimeout = 0 // Zero timeout
	config.ApplyDefaults()  // Should set to 5s

	assert.Equal(t, 5*time.Second, config.QueryTimeout, "zero timeout should apply default")
}

func TestAttack_ZeroMaxDepth(t *testing.T) {
	mockClient := newMockNATSClient()

	mockClient.requestFunc = func(ctx context.Context, subject string, data []byte, timeout time.Duration) ([]byte, error) {
		switch subject {
		case "graph.ingest.query.entity":
			return []byte(`{"entity":{"id":"test.fixture.graph.query.entity.001","triples":[]},"kvRevision":1}`), nil
		case "graph.index.query.outgoing":
			return []byte(`{"data":{"relationships":[]},"timestamp":"2026-01-09T00:00:00Z"}`), nil
		default:
			return nil, errors.New("unexpected subject")
		}
	}

	comp := createTestComponentWithMockClient(t, mockClient)
	operationCtx, cancelOperation := context.WithTimeout(t.Context(), 5*time.Second)
	defer cancelOperation()
	owner := newGraphQueryTestOwner(comp)
	startCtx := owner.startContext(operationCtx)
	defer owner.finish(operationCtx, startCtx, false, t)
	comp.config.MaxDepth = 10
	require.NoError(t, comp.Initialize())
	require.NoError(t, comp.Start(startCtx))

	ctx := context.Background()
	// Request with max_depth: 0 should apply component default
	queryData := []byte(`{"start_entity":"test.fixture.graph.query.entity.001","max_depth":0}`)

	response, err := comp.handlePathSearch(ctx, queryData)

	assert.NoError(t, err)
	assert.NotNil(t, response)
}

// ====================================================================================
// Attack Vector: Invalid JSON
// ====================================================================================

func TestAttack_MalformedJSON(t *testing.T) {
	mockClient := newMockNATSClient()

	comp := createTestComponentWithMockClient(t, mockClient)
	operationCtx, cancelOperation := context.WithTimeout(t.Context(), 5*time.Second)
	defer cancelOperation()
	owner := newGraphQueryTestOwner(comp)
	startCtx := owner.startContext(operationCtx)
	defer owner.finish(operationCtx, startCtx, false, t)
	require.NoError(t, comp.Initialize())
	require.NoError(t, comp.Start(startCtx))

	ctx := context.Background()

	tests := []struct {
		name    string
		handler func(context.Context, []byte) ([]byte, error)
		data    []byte
	}{
		{
			name:    "entity query - malformed",
			handler: comp.handleQueryEntity,
			data:    []byte(`{invalid json`),
		},
		{
			name:    "relationships query - malformed",
			handler: comp.handleQueryRelationships,
			data:    []byte(`{"entity_id":}`),
		},
		{
			name:    "path search - malformed",
			handler: comp.handlePathSearch,
			data:    []byte(`{"start_entity"}`),
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			response, err := tt.handler(ctx, tt.data)
			assert.Error(t, err, "malformed JSON should error")
			assert.Nil(t, response)
		})
	}
}

// ====================================================================================
// Attack Vector: Missing Required Fields
// ====================================================================================

func TestAttack_MissingEntityID(t *testing.T) {
	mockClient := newMockNATSClient()

	comp := createTestComponentWithMockClient(t, mockClient)
	operationCtx, cancelOperation := context.WithTimeout(t.Context(), 5*time.Second)
	defer cancelOperation()
	owner := newGraphQueryTestOwner(comp)
	startCtx := owner.startContext(operationCtx)
	defer owner.finish(operationCtx, startCtx, false, t)
	require.NoError(t, comp.Initialize())
	require.NoError(t, comp.Start(startCtx))

	ctx := context.Background()

	// Missing "id" field
	queryData := []byte(`{"name":"something"}`)
	response, err := comp.handleQueryEntity(ctx, queryData)

	assert.Error(t, err)
	assert.Nil(t, response)
	assert.Contains(t, err.Error(), "empty id")
}

func TestAttack_MissingStartEntity(t *testing.T) {
	mockClient := newMockNATSClient()

	comp := createTestComponentWithMockClient(t, mockClient)
	operationCtx, cancelOperation := context.WithTimeout(t.Context(), 5*time.Second)
	defer cancelOperation()
	owner := newGraphQueryTestOwner(comp)
	startCtx := owner.startContext(operationCtx)
	defer owner.finish(operationCtx, startCtx, false, t)
	require.NoError(t, comp.Initialize())
	require.NoError(t, comp.Start(startCtx))

	ctx := context.Background()

	// Missing "start_entity" field
	queryData := []byte(`{"max_depth":5}`)
	response, err := comp.handlePathSearch(ctx, queryData)

	assert.Error(t, err)
	assert.Nil(t, response)
	assert.Contains(t, err.Error(), "invalid request")
}

// ====================================================================================
// Attack Vector: Goroutine Leaks
// ====================================================================================

func TestAttack_NoGoroutineLeakOnStartStop(t *testing.T) {
	before := runtime.NumGoroutine()

	mockClient := newMockNATSClient()

	// Each fresh instance finishes before the next iteration is admitted.
	for i := 0; i < 10; i++ {
		func() {
			comp := createTestComponentWithMockClient(t, mockClient)
			operationCtx, cancelOperation := context.WithTimeout(t.Context(), 5*time.Second)
			defer cancelOperation()
			owner := newGraphQueryTestOwner(comp)
			startCtx := owner.startContext(operationCtx)
			defer owner.finish(operationCtx, startCtx, false, t)
			require.NoError(t, comp.Initialize())
			require.NoError(t, comp.Start(startCtx))
			require.NoError(t, owner.stop(operationCtx, startCtx, false))
		}()
		if t.Failed() {
			break
		}
	}

	after := runtime.NumGoroutine()

	// Allow small variance (testcontainers, background tasks)
	assert.LessOrEqual(t, after, before+5, "goroutine leak detected: %d → %d", before, after)
}

func TestAttack_NoGoroutineLeakOnContextCancel(t *testing.T) {
	before := runtime.NumGoroutine()

	mockClient := newMockNATSClient()

	comp := createTestComponentWithMockClient(t, mockClient)
	operationCtx, cancelOperation := context.WithTimeout(t.Context(), 5*time.Second)
	defer cancelOperation()
	owner := newGraphQueryTestOwner(comp)
	abortParent, cancelAbort := context.WithCancel(operationCtx)
	defer cancelAbort()
	startCtx := owner.startContext(abortParent)
	defer owner.finish(operationCtx, startCtx, true, t)
	require.NoError(t, comp.Initialize())
	require.NoError(t, comp.Start(startCtx))
	runtimeDone := comp.runtimeDone
	require.NotNil(t, runtimeDone)

	// Cancellation is the test input; terminal cleanup remains separately bounded.
	cancelAbort()
	select {
	case <-runtimeDone:
	case <-operationCtx.Done():
		t.Fatalf("runtime did not observe accepted Start cancellation: %v", operationCtx.Err())
	}
	require.NoError(t, owner.stop(operationCtx, startCtx, true))

	after := runtime.NumGoroutine()

	assert.LessOrEqual(t, after, before+5, "goroutine leak detected: %d → %d", before, after)
}

// ====================================================================================
// Attack Vector: Concurrent Access
// ====================================================================================

func TestAttack_ConcurrentHealthChecks(t *testing.T) {
	comp := createTestComponent(t)
	operationCtx, cancelOperation := context.WithTimeout(t.Context(), 5*time.Second)
	defer cancelOperation()
	owner := newGraphQueryTestOwner(comp)
	startCtx := owner.startContext(operationCtx)
	defer owner.finish(operationCtx, startCtx, false, t)
	require.NoError(t, comp.Initialize())
	require.NoError(t, comp.Start(startCtx))

	// Concurrent health checks
	const n = 100
	errCh := make(chan error, n)

	for i := 0; i < n; i++ {
		go func() {
			defer func() {
				if r := recover(); r != nil {
					errCh <- errors.New("panic during health check")
				} else {
					errCh <- nil
				}
			}()
			comp.Health()
		}()
	}

	// Observe failure within the operation budget, then still join every worker.
	timedOut := false
	for i := 0; i < n; i++ {
		var err error
		select {
		case err = <-errCh:
		case <-operationCtx.Done():
			if !timedOut {
				t.Errorf("health worker results exceeded operation budget: completed=%d/%d: %v", i, n, operationCtx.Err())
				timedOut = true
			}
			err = <-errCh
		}
		assert.NoError(t, err, "concurrent health checks should not panic")
	}
}

func TestAttack_ConcurrentMetricsAccess(t *testing.T) {
	comp := createTestComponent(t)
	operationCtx, cancelOperation := context.WithTimeout(t.Context(), 5*time.Second)
	defer cancelOperation()
	owner := newGraphQueryTestOwner(comp)
	startCtx := owner.startContext(operationCtx)
	defer owner.finish(operationCtx, startCtx, false, t)
	require.NoError(t, comp.Initialize())
	require.NoError(t, comp.Start(startCtx))

	// Concurrent metrics access
	const n = 100
	errCh := make(chan error, n)

	for i := 0; i < n; i++ {
		go func() {
			defer func() {
				if r := recover(); r != nil {
					errCh <- errors.New("panic during metrics access")
				} else {
					errCh <- nil
				}
			}()
			comp.DataFlow()
		}()
	}

	// Observe failure within the operation budget, then still join every worker.
	timedOut := false
	for i := 0; i < n; i++ {
		var err error
		select {
		case err = <-errCh:
		case <-operationCtx.Done():
			if !timedOut {
				t.Errorf("metrics worker results exceeded operation budget: completed=%d/%d: %v", i, n, operationCtx.Err())
				timedOut = true
			}
			err = <-errCh
		}
		assert.NoError(t, err, "concurrent metrics access should not panic")
	}
}

// ====================================================================================
// Attack Vector: Large/Malicious Inputs
// ====================================================================================

func TestAttack_VeryLongEntityID(t *testing.T) {
	mockClient := newMockNATSClient()

	mockClient.requestFunc = func(ctx context.Context, subject string, data []byte, timeout time.Duration) ([]byte, error) {
		// Simulate backend rejecting oversized request
		if len(data) > 10000 {
			return nil, errors.New("request too large")
		}
		return []byte(`{}`), nil
	}

	comp := createTestComponentWithMockClient(t, mockClient)
	operationCtx, cancelOperation := context.WithTimeout(t.Context(), 5*time.Second)
	defer cancelOperation()
	owner := newGraphQueryTestOwner(comp)
	startCtx := owner.startContext(operationCtx)
	defer owner.finish(operationCtx, startCtx, false, t)
	require.NoError(t, comp.Initialize())
	require.NoError(t, comp.Start(startCtx))

	ctx := context.Background()

	// 1MB entity ID
	massiveID := strings.Repeat("a", 1_000_000)
	queryData, _ := json.Marshal(map[string]string{"id": massiveID})

	// Should handle without panic
	response, err := comp.handleQueryEntity(ctx, queryData)

	// Either error or success, but no panic
	_ = response
	_ = err
}

func TestAttack_DeeplyNestedJSON(t *testing.T) {
	mockClient := newMockNATSClient()

	comp := createTestComponentWithMockClient(t, mockClient)
	operationCtx, cancelOperation := context.WithTimeout(t.Context(), 5*time.Second)
	defer cancelOperation()
	owner := newGraphQueryTestOwner(comp)
	startCtx := owner.startContext(operationCtx)
	defer owner.finish(operationCtx, startCtx, false, t)
	require.NoError(t, comp.Initialize())
	require.NoError(t, comp.Start(startCtx))

	ctx := context.Background()

	// Deeply nested JSON (potential DoS via stack overflow)
	nested := strings.Repeat(`{"a":`, 10000) + `"value"` + strings.Repeat(`}`, 10000)

	// Should handle without panic
	response, err := comp.handleQueryEntity(ctx, []byte(nested))

	// Either error or success, but no panic
	_ = response
	_ = err
}

// ====================================================================================
// Attack Vector: Path Search Edge Cases
// ====================================================================================

func TestAttack_PathSearchExcessiveMaxDepth(t *testing.T) {
	mockClient := newMockNATSClient()
	nextID := semantictest.EntityID(t, "test", "fixture", "graph", "query", "entity", "next")

	callCount := 0
	mockClient.requestFunc = func(ctx context.Context, subject string, data []byte, timeout time.Duration) ([]byte, error) {
		callCount++
		switch subject {
		case "graph.ingest.query.entity":
			return []byte(`{"entity":{"id":"test.fixture.graph.query.entity.001","triples":[]},"kvRevision":1}`), nil
		case "graph.index.query.outgoing":
			// Always return next node (infinite graph) in QueryResponse envelope format
			return []byte(`{"data":{"relationships":[{"to_entity_id":"` + nextID + `","predicate":"test.fixture.p"}]},"timestamp":"2026-01-09T00:00:00Z"}`), nil
		default:
			return nil, errors.New("unexpected subject")
		}
	}

	comp := createTestComponentWithMockClient(t, mockClient)
	operationCtx, cancelOperation := context.WithTimeout(t.Context(), 5*time.Second)
	defer cancelOperation()
	owner := newGraphQueryTestOwner(comp)
	startCtx := owner.startContext(operationCtx)
	defer owner.finish(operationCtx, startCtx, false, t)
	comp.config.MaxDepth = 3 // Component limit
	require.NoError(t, comp.Initialize())
	require.NoError(t, comp.Start(startCtx))

	ctx := context.Background()

	// Request with excessive max_depth (should be clamped to config.MaxDepth)
	queryData := []byte(`{"start_entity":"test.fixture.graph.query.entity.001","max_depth":999999}`)

	response, err := comp.handlePathSearch(ctx, queryData)

	assert.NoError(t, err)
	assert.NotNil(t, response)

	// Should respect component MaxDepth limit, not request value
	assert.Less(t, callCount, 50, "should not traverse excessively deep")
}

func TestAttack_PathSearchEmptyStartEntity(t *testing.T) {
	mockClient := newMockNATSClient()

	comp := createTestComponentWithMockClient(t, mockClient)
	operationCtx, cancelOperation := context.WithTimeout(t.Context(), 5*time.Second)
	defer cancelOperation()
	owner := newGraphQueryTestOwner(comp)
	startCtx := owner.startContext(operationCtx)
	defer owner.finish(operationCtx, startCtx, false, t)
	require.NoError(t, comp.Initialize())
	require.NoError(t, comp.Start(startCtx))

	ctx := context.Background()

	// Empty start_entity
	queryData := []byte(`{"start_entity":"","max_depth":5}`)

	response, err := comp.handlePathSearch(ctx, queryData)

	assert.Error(t, err)
	assert.Nil(t, response)
	assert.Contains(t, err.Error(), "invalid request")
}

// ====================================================================================
// Attack Vector: NATS Client Disconnection
// ====================================================================================

func TestAttack_NATSClientDisconnected(t *testing.T) {
	mockClient := newMockNATSClient()
	mockClient.status = natsclient.StatusDisconnected
	mockClient.connected = false

	comp := createTestComponentWithMockClient(t, mockClient)

	// Initialize should succeed
	require.NoError(t, comp.Initialize())

	ctx := context.Background()

	// Start should fail due to disconnected client
	err := comp.Start(ctx)
	assert.Error(t, err, "Start should fail with disconnected NATS client")
}

func TestAttack_HealthCheckWithDisconnectedNATS(t *testing.T) {
	mockClient := newMockNATSClient()

	comp := createTestComponentWithMockClient(t, mockClient)
	operationCtx, cancelOperation := context.WithTimeout(t.Context(), 5*time.Second)
	defer cancelOperation()
	owner := newGraphQueryTestOwner(comp)
	startCtx := owner.startContext(operationCtx)
	defer owner.finish(operationCtx, startCtx, false, t)
	require.NoError(t, comp.Initialize())
	require.NoError(t, comp.Start(startCtx))

	// Simulate disconnection
	mockClient.status = natsclient.StatusDisconnected

	health := comp.Health()

	// Should report unhealthy when NATS disconnected
	assert.False(t, health.Healthy, "component should be unhealthy with disconnected NATS")

	require.NoError(t, owner.stop(operationCtx, startCtx, false))
}

// ====================================================================================
// Attack Vector: Request Validation Edge Cases
// ====================================================================================

func TestAttack_EmptyRequestBody(t *testing.T) {
	mockClient := newMockNATSClient()

	comp := createTestComponentWithMockClient(t, mockClient)
	operationCtx, cancelOperation := context.WithTimeout(t.Context(), 5*time.Second)
	defer cancelOperation()
	owner := newGraphQueryTestOwner(comp)
	startCtx := owner.startContext(operationCtx)
	defer owner.finish(operationCtx, startCtx, false, t)
	require.NoError(t, comp.Initialize())
	require.NoError(t, comp.Start(startCtx))

	ctx := context.Background()

	tests := []struct {
		name    string
		handler func(context.Context, []byte) ([]byte, error)
		data    []byte
	}{
		{
			name:    "entity query - empty",
			handler: comp.handleQueryEntity,
			data:    []byte{},
		},
		{
			name:    "relationships query - empty",
			handler: comp.handleQueryRelationships,
			data:    []byte{},
		},
		{
			name:    "path search - empty",
			handler: comp.handlePathSearch,
			data:    []byte{},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			response, err := tt.handler(ctx, tt.data)
			assert.Error(t, err, "empty request should error")
			assert.Nil(t, response)
		})
	}
}
