package clustering

import (
	"github.com/c360studio/semstreams/metric"
	"github.com/prometheus/client_golang/prometheus"
)

// EnhancementMetrics provides Prometheus metrics for the content-addressed LLM
// community-summary worker (ADR-087).
//
// There is deliberately NO queue-depth gauge. Content-addressing makes backlog
// benign: a steady graph re-triggers the same memberships, every trigger is a
// microsecond cache hit that skips the LLM, and only a NEW distinct membership
// costs a call. The old Inc/DecQueueDepth gauge bracketed already-dequeued work
// and was a phantom (#617); it is removed. The store's accumulation is observed
// instead by the summaries-size gauge (add-3).
type EnhancementMetrics struct {
	// Timing
	enhancementLatency prometheus.Histogram // Per-request LLM latency

	// Counters
	summaryCacheHits prometheus.Counter // Triggers served from an llm-enhanced record (no LLM call)
	summaryGenerated prometheus.Counter // Misses that did LLM work and wrote an llm-enhanced record
	summaryFailed    prometheus.Counter // Enhancements that failed and wrote an llm-failed record

	// Gauges
	summariesSize prometheus.Gauge // Number of stored summary records (bounded-GC trigger)
}

// NewEnhancementMetrics creates a new EnhancementMetrics instance using MetricsRegistry
func NewEnhancementMetrics(component string, registry *metric.MetricsRegistry) *EnhancementMetrics {
	if registry == nil {
		return nil
	}

	// LLM enhancement latency - buckets tuned for LLM inference (typically 1-60s)
	enhancementLatency := prometheus.NewHistogram(prometheus.HistogramOpts{
		Name:        "semstreams_llm_enhancement_latency_seconds",
		Help:        "Latency of LLM community enhancement requests in seconds",
		ConstLabels: prometheus.Labels{"component": component},
		Buckets:     []float64{0.5, 1.0, 2.0, 5.0, 10.0, 30.0, 60.0},
	})
	registry.RegisterHistogram("clustering", "llm_enhancement_latency_seconds", enhancementLatency)

	summaryCacheHits := prometheus.NewCounter(prometheus.CounterOpts{
		Name:        "semstreams_community_summary_cache_hits_total",
		Help:        "Community-summary triggers served from a stored llm-enhanced record (no LLM call)",
		ConstLabels: prometheus.Labels{"component": component},
	})
	registry.RegisterCounter("clustering", "community_summary_cache_hits_total", summaryCacheHits)

	summaryGenerated := prometheus.NewCounter(prometheus.CounterOpts{
		Name:        "semstreams_community_summary_generated_total",
		Help:        "Community summaries generated by an LLM call (cache misses that did work)",
		ConstLabels: prometheus.Labels{"component": component},
	})
	registry.RegisterCounter("clustering", "community_summary_generated_total", summaryGenerated)

	summaryFailed := prometheus.NewCounter(prometheus.CounterOpts{
		Name:        "semstreams_community_summary_failed_total",
		Help:        "Community-summary enhancements that failed and wrote an llm-failed record",
		ConstLabels: prometheus.Labels{"component": component},
	})
	registry.RegisterCounter("clustering", "community_summary_failed_total", summaryFailed)

	summariesSize := prometheus.NewGauge(prometheus.GaugeOpts{
		Name:        "semstreams_community_summaries_size",
		Help:        "Current number of stored community summary records in COMMUNITY_SUMMARIES",
		ConstLabels: prometheus.Labels{"component": component},
	})
	registry.RegisterGauge("clustering", "community_summaries_size", summariesSize)

	return &EnhancementMetrics{
		enhancementLatency: enhancementLatency,
		summaryCacheHits:   summaryCacheHits,
		summaryGenerated:   summaryGenerated,
		summaryFailed:      summaryFailed,
		summariesSize:      summariesSize,
	}
}

// RecordCacheHit records a trigger served from a stored llm-enhanced record
// (no LLM call performed).
func (m *EnhancementMetrics) RecordCacheHit() {
	if m == nil {
		return
	}
	m.summaryCacheHits.Inc()
}

// RecordGenerated records a summary that was generated by an LLM call (a cache
// miss that did work) with its latency.
func (m *EnhancementMetrics) RecordGenerated(latencySeconds float64) {
	if m == nil {
		return
	}
	m.summaryGenerated.Inc()
	m.enhancementLatency.Observe(latencySeconds)
}

// RecordFailed records a failed enhancement (an llm-failed record was written)
// with its latency.
func (m *EnhancementMetrics) RecordFailed(latencySeconds float64) {
	if m == nil {
		return
	}
	m.summaryFailed.Inc()
	m.enhancementLatency.Observe(latencySeconds)
}

// SetSummariesSize sets the current number of stored summary records.
func (m *EnhancementMetrics) SetSummariesSize(n int) {
	if m == nil {
		return
	}
	m.summariesSize.Set(float64(n))
}
