package contract

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"testing"

	"github.com/c360studio/semstreams/component"
	"github.com/c360studio/semstreams/composition"
	"github.com/google/go-cmp/cmp"
	"github.com/xeipuuv/gojsonschema"
)

// nonComponentSchemas lists schema files that are not component configurations.
// These are generated by the OpenAPI generator but have different structures.
var nonComponentSchemas = map[string]bool{
	"workflow-definition": true, // Workflow JSON definition schema (ADR-020)
}

// TestCommittedSchemasMatchCode validates that committed schemas match generated schemas
// This ensures no schema drift between committed artifacts and source code
func TestCommittedSchemasMatchCode(t *testing.T) {
	// Get repository root
	repoRoot, err := findRepoRoot()
	if err != nil {
		t.Fatalf("Failed to find repository root: %v", err)
	}

	schemasDir := filepath.Join(repoRoot, "schemas")

	// Load committed schemas
	committedSchemas, err := loadCommittedSchemas(schemasDir)
	if err != nil {
		t.Fatalf("Failed to load committed schemas: %v", err)
	}

	if len(committedSchemas) == 0 {
		t.Fatal("No committed schemas found - expected at least one schema file")
	}

	// Initialize component registry
	registry := component.NewRegistry()
	if err := registerPublishedComposition(registry); err != nil {
		t.Fatalf("Failed to register components: %v", err)
	}

	// Generate schemas from code
	factories := registry.ListFactories()
	if len(factories) == 0 {
		t.Fatal("No component factories registered")
	}
	catalogEntries := make(map[string]composition.CatalogEntry)
	for _, entry := range composition.Catalog(registry) {
		catalogEntries[entry.ID] = entry
	}

	// Compare each committed schema with generated schema
	for name := range committedSchemas {
		t.Run(name, func(t *testing.T) {
			// Skip non-component schemas
			if nonComponentSchemas[name] {
				t.Skip("Non-component schema")
			}

			committedSchema := committedSchemas[name]

			// Check if component is registered
			registration, exists := factories[name]
			if !exists {
				t.Fatalf("Component %s has committed schema but is not registered in code", name)
			}

			// Generate schema from code
			generatedSchema := extractSchemaFromRegistration(name, registration, catalogEntries[name])

			// Compare schemas (deep equal)
			if diff := cmp.Diff(committedSchema, generatedSchema); diff != "" {
				t.Errorf("Schema mismatch for %s (-committed +generated):\n%s", name, diff)
				t.Errorf("\nThis indicates schema drift. Run 'task schema:generate' to update committed schemas.")
			}
		})
	}

	// Check for components registered but missing committed schemas
	for name := range factories {
		if _, exists := committedSchemas[name]; !exists {
			t.Errorf("Component %s is registered but has no committed schema file", name)
			t.Errorf("Run 'task schema:generate' to generate missing schema")
		}
	}
}

// TestCommittedSchemasValidStructure validates committed schema files have correct structure
func TestCommittedSchemasValidStructure(t *testing.T) {
	repoRoot, err := findRepoRoot()
	if err != nil {
		t.Fatalf("Failed to find repository root: %v", err)
	}

	schemasDir := filepath.Join(repoRoot, "schemas")

	committedSchemas, err := loadCommittedSchemas(schemasDir)
	if err != nil {
		t.Fatalf("Failed to load committed schemas: %v", err)
	}

	for name, schema := range committedSchemas {
		t.Run(name, func(t *testing.T) {
			// Skip non-component schemas
			if nonComponentSchemas[name] {
				t.Skip("Non-component schema")
			}

			// Validate required JSON Schema fields
			if schema["$schema"] != "http://json-schema.org/draft-07/schema#" {
				t.Errorf("Invalid or missing $schema field")
			}

			id, ok := schema["$id"].(string)
			if !ok {
				t.Errorf("Missing or invalid $id field")
			} else if id != name+".v1.json" {
				t.Errorf("Invalid $id: expected %s.v1.json, got %s", name, id)
			}

			if schema["type"] != "object" {
				t.Errorf("Schema type should be 'object', got: %v", schema["type"])
			}

			// Validate component metadata exists
			metadata, ok := schema["x-component-metadata"].(map[string]interface{})
			if !ok {
				t.Errorf("Missing or invalid x-component-metadata")
			} else {
				// Check required metadata fields
				requiredFields := []string{"name", "type", "protocol", "domain", "version"}
				for _, field := range requiredFields {
					if _, exists := metadata[field]; !exists {
						t.Errorf("Missing required metadata field: %s", field)
					}
				}

				// Validate name matches
				if metaName, ok := metadata["name"].(string); ok && metaName != name {
					t.Errorf("Metadata name %s doesn't match component name %s", metaName, name)
				}
			}

			// Validate properties exist
			if _, ok := schema["properties"]; !ok {
				t.Errorf("Missing properties field")
			}

			// Validate required field exists (can be empty array)
			if _, ok := schema["required"]; !ok {
				t.Errorf("Missing required field")
			}
		})
	}
}

func TestCommittedSchemaJetStreamOutputMaxAckPendingZeroSemantics(t *testing.T) {
	repoRoot, err := findRepoRoot()
	if err != nil {
		t.Fatal(err)
	}
	schemaPath := filepath.Join(repoRoot, "schemas", "graph-ingest.v1.json")
	tests := []struct {
		name    string
		value   any
		include bool
		valid   bool
	}{
		{name: "omitted", valid: true},
		{name: "explicit zero", value: 0, include: true, valid: true},
		{name: "positive", value: 7, include: true, valid: false},
		{name: "unlimited", value: -1, include: true, valid: false},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			config := map[string]any{
				"kind": "jetstream", "subjects": []string{"events.>"},
			}
			if tt.include {
				config["max_ack_pending"] = tt.value
			}
			document := map[string]any{"ports": map[string]any{
				"outputs": []any{map[string]any{"name": "events", "config": config}},
			}}
			result, validateErr := gojsonschema.Validate(
				gojsonschema.NewReferenceLoader("file://"+schemaPath),
				gojsonschema.NewGoLoader(document),
			)
			if validateErr != nil {
				t.Fatal(validateErr)
			}
			if result.Valid() != tt.valid {
				t.Fatalf("valid = %v, want %v; errors: %#v", result.Valid(), tt.valid, result.Errors())
			}
		})
	}
}

// TestNoOrphanedSchemaFiles ensures no schema files exist without corresponding components
func TestNoOrphanedSchemaFiles(t *testing.T) {
	repoRoot, err := findRepoRoot()
	if err != nil {
		t.Fatalf("Failed to find repository root: %v", err)
	}

	schemasDir := filepath.Join(repoRoot, "schemas")

	// Get all schema files
	schemaFiles, err := filepath.Glob(filepath.Join(schemasDir, "*.v1.json"))
	if err != nil {
		t.Fatalf("Failed to glob schema files: %v", err)
	}

	// Initialize component registry
	registry := component.NewRegistry()
	if err := registerPublishedComposition(registry); err != nil {
		t.Fatalf("Failed to register components: %v", err)
	}

	factories := registry.ListFactories()

	// Check each schema file has corresponding component
	for _, schemaPath := range schemaFiles {
		filename := filepath.Base(schemaPath)
		// Remove .v1.json suffix to get component name
		name := filename[:len(filename)-len(".v1.json")]

		// Skip non-component schemas
		if nonComponentSchemas[name] {
			continue
		}

		if _, exists := factories[name]; !exists {
			t.Errorf("Orphaned schema file: %s (no corresponding component registered)", filename)
			t.Errorf("Remove this file or register the component")
		}
	}
}

// Helper functions

func findRepoRoot() (string, error) {
	// Check environment variable first
	if envRoot := os.Getenv("SEMSTREAMS_ROOT"); envRoot != "" {
		schemasPath := filepath.Join(envRoot, "schemas")
		if info, err := os.Stat(schemasPath); err == nil && info.IsDir() {
			return envRoot, nil
		}
		return "", &PathResolutionError{
			Message: "SEMSTREAMS_ROOT is set but schemas/ directory not found",
			Path:    schemasPath,
			Solutions: []string{
				"Verify SEMSTREAMS_ROOT points to semstreams repository root",
				"Run 'task schema:generate' to create schemas directory",
				"Unset SEMSTREAMS_ROOT to use automatic detection",
			},
		}
	}

	// Start from current working directory
	cwd, err := os.Getwd()
	if err != nil {
		return "", err
	}

	// Walk up until we find schemas/ directory or reach root
	dir := cwd
	for {
		schemasPath := filepath.Join(dir, "schemas")
		if info, err := os.Stat(schemasPath); err == nil && info.IsDir() {
			return dir, nil
		}

		parent := filepath.Dir(dir)
		if parent == dir {
			// Reached root without finding schemas/
			break
		}
		dir = parent
	}

	// If not found by walking up, assume we're in test/contract and go up two levels
	assumedRoot, _ := filepath.Abs(filepath.Join(cwd, "..", ".."))
	schemasPath := filepath.Join(assumedRoot, "schemas")

	if info, err := os.Stat(schemasPath); err == nil && info.IsDir() {
		return assumedRoot, nil
	}

	return "", &PathResolutionError{
		Message: "Could not find semstreams repository root",
		Path:    cwd,
		Solutions: []string{
			"Run tests from within semstreams repository",
			"Set SEMSTREAMS_ROOT environment variable",
			"Ensure schemas/ directory exists (run 'task schema:generate')",
		},
		Docs: "docs/CONTRACT_TESTING.md",
	}
}

// PathResolutionError provides clear error messages for path resolution failures
type PathResolutionError struct {
	Message   string
	Path      string
	Solutions []string
	Docs      string
}

func (e *PathResolutionError) Error() string {
	msg := e.Message + "\n\n"
	msg += "Current path: " + e.Path + "\n\n"
	msg += "Solutions:\n"
	for i, solution := range e.Solutions {
		msg += "  " + string(rune(i+1)) + ". " + solution + "\n"
	}
	if e.Docs != "" {
		msg += "\nFor more info, see: " + e.Docs + "\n"
	}
	return msg
}

func loadCommittedSchemas(schemasDir string) (map[string]map[string]interface{}, error) {
	// Check if schemas directory exists
	if info, err := os.Stat(schemasDir); err != nil || !info.IsDir() {
		return nil, &PathResolutionError{
			Message: "Schemas directory not found",
			Path:    schemasDir,
			Solutions: []string{
				"Run 'task schema:generate' to create schemas",
				"Verify repository structure is correct",
				"Set SEMSTREAMS_ROOT if running from unusual location",
			},
			Docs: "docs/SCHEMA_GENERATION.md",
		}
	}

	schemas := make(map[string]map[string]interface{})

	schemaFiles, err := filepath.Glob(filepath.Join(schemasDir, "*.v1.json"))
	if err != nil {
		return nil, &PathResolutionError{
			Message: "Failed to search for schema files",
			Path:    schemasDir,
			Solutions: []string{
				"Verify directory permissions",
				"Check that schemas directory is readable",
			},
		}
	}

	if len(schemaFiles) == 0 {
		return nil, &PathResolutionError{
			Message: "No schema files found in schemas directory",
			Path:    schemasDir,
			Solutions: []string{
				"Run 'task schema:generate' to generate schemas",
				"Ensure components are registered in componentregistry/register.go",
			},
			Docs: "docs/SCHEMA_GENERATION.md",
		}
	}

	for _, schemaPath := range schemaFiles {
		data, err := os.ReadFile(schemaPath)
		if err != nil {
			return nil, &PathResolutionError{
				Message: "Failed to read schema file: " + filepath.Base(schemaPath),
				Path:    schemaPath,
				Solutions: []string{
					"Check file permissions",
					"Regenerate schemas with 'task schema:generate'",
				},
			}
		}

		var schema map[string]interface{}
		if err := json.Unmarshal(data, &schema); err != nil {
			return nil, &PathResolutionError{
				Message: "Invalid JSON in schema file: " + filepath.Base(schemaPath),
				Path:    schemaPath,
				Solutions: []string{
					"Regenerate schemas with 'task schema:generate'",
					"Do not manually edit schema files",
				},
				Docs: "docs/SCHEMA_GENERATION.md",
			}
		}

		// Extract component name from filename (remove .v1.json)
		filename := filepath.Base(schemaPath)
		name := filename[:len(filename)-len(".v1.json")]

		schemas[name] = schema
	}

	return schemas, nil
}

func extractSchemaFromRegistration(name string, reg *component.Registration, entry composition.CatalogEntry) map[string]interface{} {
	schema := make(map[string]interface{})

	schema["$schema"] = "http://json-schema.org/draft-07/schema#"
	schema["$id"] = name + ".v1.json"
	schema["type"] = "object"
	schema["title"] = name + " Configuration"
	schema["description"] = reg.Description

	// Convert properties
	properties := make(map[string]interface{})
	for propName, propSchema := range reg.Schema.Properties {
		prop := make(map[string]interface{})
		prop["type"] = mapTypeToJSONSchema(propSchema.Type)
		prop["description"] = propSchema.Description

		if propSchema.Default != nil {
			// Normalize types since JSON unmarshal produces different types.
			//
			// EVERY integer width has to be listed. A default declared with an
			// explicitly typed constant (int64, because the config field it fills is
			// int64) would otherwise fall through to the default arm, stay int64, and
			// fail comparison against the float64 a JSON decode produces — reporting
			// "schema drift, run task schema:generate" for a schema that is not
			// drifted and that regenerating cannot change.
			switch v := propSchema.Default.(type) {
			case int:
				prop["default"] = float64(v)
			case int32:
				prop["default"] = float64(v)
			case int64:
				prop["default"] = float64(v)
			case float32:
				prop["default"] = float64(v)
			case []string:
				// Convert []string to []any for JSON comparison compatibility
				anySlice := make([]any, len(v))
				for i, s := range v {
					anySlice[i] = s
				}
				prop["default"] = anySlice
			default:
				prop["default"] = propSchema.Default
			}
		}
		if propSchema.Minimum != nil {
			// Convert int to float64 for JSON comparison compatibility
			prop["minimum"] = float64(*propSchema.Minimum)
		}
		if propSchema.Maximum != nil {
			// Convert int to float64 for JSON comparison compatibility
			prop["maximum"] = float64(*propSchema.Maximum)
		}
		if propSchema.MinLength != nil {
			prop["minLength"] = float64(*propSchema.MinLength)
		}
		if propSchema.MaxLength != nil {
			prop["maxLength"] = float64(*propSchema.MaxLength)
		}
		if propSchema.Pattern != "" {
			prop["pattern"] = propSchema.Pattern
		}
		if len(propSchema.Enum) > 0 {
			// Convert []string to []any for JSON comparison compatibility
			enumAny := make([]any, len(propSchema.Enum))
			for i, e := range propSchema.Enum {
				enumAny[i] = e
			}
			prop["enum"] = enumAny
		}
		if propSchema.Category != "" {
			prop["category"] = propSchema.Category
		}
		if propSchema.AdditionalProperties != nil {
			prop["additionalProperties"] = *propSchema.AdditionalProperties
		}
		// Handle array types - add items schema
		if propSchema.Type == "array" {
			if propSchema.Items != nil {
				prop["items"] = convertPropertySchemaToMap(propSchema.Items)
			} else {
				prop["items"] = map[string]interface{}{
					"type": "string",
				}
			}
		}

		// Handle nested object types - add properties
		if propSchema.Type == "object" && len(propSchema.Properties) > 0 {
			prop["properties"] = convertPropertiesToMap(propSchema.Properties)
			if len(propSchema.Required) > 0 {
				reqAny := make([]any, len(propSchema.Required))
				for i, r := range propSchema.Required {
					reqAny[i] = r
				}
				prop["required"] = reqAny
			}
		}
		if propSchema.Type == "ports" {
			prop = convertPortConfigToMap(propSchema)
		}

		properties[propName] = prop
	}
	schema["properties"] = properties

	// Required fields
	required := make([]interface{}, len(reg.Schema.Required))
	for i, r := range reg.Schema.Required {
		required[i] = r
	}
	schema["required"] = required

	// Component metadata, including the default ports the generator exports
	// (ADR-100 P1). The ports round-trip through JSON so the comparison sees
	// the same wire shape the committed file holds.
	metadata := map[string]interface{}{
		"name":     name,
		"type":     reg.Type,
		"protocol": reg.Protocol,
		"domain":   reg.Domain,
		"version":  reg.Version,
	}
	if entry.DefaultPorts != nil {
		portsJSON, err := json.Marshal(entry.DefaultPorts)
		if err != nil {
			panic(fmt.Sprintf("marshal default ports for %s: %v", name, err))
		}
		var ports interface{}
		if err := json.Unmarshal(portsJSON, &ports); err != nil {
			panic(fmt.Sprintf("decode default ports for %s: %v", name, err))
		}
		metadata["default_ports"] = ports
	}
	if entry.PortsRequireConfig {
		metadata["ports_require_config"] = true
	}
	if entry.PortsError != "" {
		metadata["ports_error"] = entry.PortsError
	}
	schema["x-component-metadata"] = metadata

	return schema
}

func convertPortConfigToMap(src component.PropertySchema) map[string]interface{} {
	result := map[string]interface{}{
		"type":                 "object",
		"additionalProperties": false,
		"properties": map[string]interface{}{
			"inputs":  portLaneToMap(src.PortFields, component.DirectionInput),
			"outputs": portLaneToMap(src.PortFields, component.DirectionOutput),
		},
	}
	if src.Description != "" {
		result["description"] = src.Description
	}
	if src.Category != "" {
		result["category"] = src.Category
	}
	return result
}

func portLaneToMap(fields map[string]component.PortFieldInfo, direction component.Direction) map[string]interface{} {
	return map[string]interface{}{
		"type": "array",
		"items": map[string]interface{}{
			"type":                 "object",
			"properties":           portEnvelopeToMap(fields, direction),
			"required":             []interface{}{"name", "config"},
			"additionalProperties": false,
		},
	}
}

func portEnvelopeToMap(
	fields map[string]component.PortFieldInfo,
	direction component.Direction,
) map[string]interface{} {
	result := make(map[string]interface{}, len(fields))
	for name, field := range fields {
		if name != "config" {
			result[name] = portFieldInfoToMap(field, direction)
			continue
		}
		variantNames := make([]string, 0, len(field.Variants))
		for kind := range field.Variants {
			variantNames = append(variantNames, kind)
		}
		sort.Strings(variantNames)
		variants := make([]interface{}, 0, len(variantNames))
		for _, kind := range variantNames {
			variant := field.Variants[kind]
			if portFieldAllowsDirection(variant, direction) {
				variants = append(variants, portFieldInfoToMap(variant, direction))
			}
		}
		result[name] = map[string]interface{}{"type": "object", "oneOf": variants}
	}
	return result
}

func portFieldInfoToMap(field component.PortFieldInfo, direction component.Direction) map[string]interface{} {
	result := map[string]interface{}{"type": mapTypeToJSONSchema(field.Type)}
	if len(field.Enum) > 0 {
		values := make([]interface{}, len(field.Enum))
		for index, value := range field.Enum {
			values[index] = value
		}
		result["enum"] = values
	}
	if field.Minimum != nil {
		result["minimum"] = float64(*field.Minimum)
	}
	if field.AdditionalProperties != nil {
		result["additionalProperties"] = *field.AdditionalProperties
	}
	if field.Items != nil {
		result["items"] = portFieldInfoToMap(*field.Items, direction)
	}
	if len(field.Properties) > 0 {
		properties := make(map[string]interface{}, len(field.Properties))
		for name, property := range field.Properties {
			converted, include := portFieldForDirectionToMap(property, direction)
			if include {
				properties[name] = converted
			}
		}
		result["properties"] = properties
		required := make([]interface{}, 0, len(field.Required)+len(field.RequiredByDirection[direction]))
		for _, name := range append(append([]string(nil), field.Required...), field.RequiredByDirection[direction]...) {
			if _, ok := properties[name]; ok {
				required = append(required, name)
			}
		}
		if len(required) > 0 {
			result["required"] = required
		}
	}
	return result
}

func portFieldForDirectionToMap(
	field component.PortFieldInfo,
	direction component.Direction,
) (map[string]interface{}, bool) {
	if portFieldAllowsDirection(field, direction) {
		return portFieldInfoToMap(field, direction), true
	}
	if field.ZeroIsOmitted() {
		return map[string]interface{}{"type": mapTypeToJSONSchema(field.Type), "const": float64(0)}, true
	}
	return nil, false
}

func portFieldAllowsDirection(field component.PortFieldInfo, direction component.Direction) bool {
	if len(field.Directions) == 0 {
		return true
	}
	for _, allowed := range field.Directions {
		if allowed == direction {
			return true
		}
	}
	return false
}

// mapTypeToJSONSchema must stay in sync with cmd/openapi-generator/main.go's
// function of the same name. Both map component propType strings to JSON
// Schema types. int → "integer" (precision signal for validators); float →
// "number". Duplication is intentional: test/contract is a leaf package and
// can't import cmd/*.
func mapTypeToJSONSchema(goType string) string {
	switch goType {
	case "string":
		return "string"
	case "int", "int64":
		return "integer"
	case "float", "float64":
		return "number"
	case "bool":
		return "boolean"
	case "array":
		return "array"
	case "object":
		return "object"
	default:
		return "string" // Default to string for unknown types
	}
}

// convertPropertySchemaToMap converts a PropertySchema pointer to a map for JSON comparison
func convertPropertySchemaToMap(src *component.PropertySchema) map[string]interface{} {
	if src == nil {
		return nil
	}
	result := make(map[string]interface{})
	result["type"] = mapTypeToJSONSchema(src.Type)

	if src.Description != "" {
		result["description"] = src.Description
	}
	if src.Default != nil {
		switch v := src.Default.(type) {
		case int:
			result["default"] = float64(v)
		default:
			result["default"] = v
		}
	}
	if src.Minimum != nil {
		result["minimum"] = float64(*src.Minimum)
	}
	if src.Maximum != nil {
		result["maximum"] = float64(*src.Maximum)
	}
	if src.MinLength != nil {
		result["minLength"] = float64(*src.MinLength)
	}
	if src.MaxLength != nil {
		result["maxLength"] = float64(*src.MaxLength)
	}
	if src.Pattern != "" {
		result["pattern"] = src.Pattern
	}
	if len(src.Enum) > 0 {
		enumAny := make([]any, len(src.Enum))
		for i, e := range src.Enum {
			enumAny[i] = e
		}
		result["enum"] = enumAny
	}
	if src.Category != "" {
		result["category"] = src.Category
	}
	if src.AdditionalProperties != nil {
		result["additionalProperties"] = *src.AdditionalProperties
	}
	if len(src.Properties) > 0 {
		result["properties"] = convertPropertiesToMap(src.Properties)
	}
	if len(src.Required) > 0 {
		reqAny := make([]any, len(src.Required))
		for i, r := range src.Required {
			reqAny[i] = r
		}
		result["required"] = reqAny
	}
	if src.Items != nil {
		result["items"] = convertPropertySchemaToMap(src.Items)
	}
	return result
}

// convertPropertiesToMap converts a PropertySchema map to interface map for JSON comparison
func convertPropertiesToMap(props map[string]component.PropertySchema) map[string]interface{} {
	result := make(map[string]interface{})
	for name, prop := range props {
		propMap := make(map[string]interface{})
		propMap["type"] = mapTypeToJSONSchema(prop.Type)

		if prop.Description != "" {
			propMap["description"] = prop.Description
		}
		if prop.Default != nil {
			switch v := prop.Default.(type) {
			case int:
				propMap["default"] = float64(v)
			default:
				propMap["default"] = v
			}
		}
		if prop.Minimum != nil {
			propMap["minimum"] = float64(*prop.Minimum)
		}
		if prop.Maximum != nil {
			propMap["maximum"] = float64(*prop.Maximum)
		}
		if prop.MinLength != nil {
			propMap["minLength"] = float64(*prop.MinLength)
		}
		if prop.MaxLength != nil {
			propMap["maxLength"] = float64(*prop.MaxLength)
		}
		if prop.Pattern != "" {
			propMap["pattern"] = prop.Pattern
		}
		if len(prop.Enum) > 0 {
			enumAny := make([]any, len(prop.Enum))
			for i, e := range prop.Enum {
				enumAny[i] = e
			}
			propMap["enum"] = enumAny
		}
		if prop.Category != "" {
			propMap["category"] = prop.Category
		}
		if prop.AdditionalProperties != nil {
			propMap["additionalProperties"] = *prop.AdditionalProperties
		}
		if len(prop.Properties) > 0 {
			propMap["properties"] = convertPropertiesToMap(prop.Properties)
		}
		if len(prop.Required) > 0 {
			reqAny := make([]any, len(prop.Required))
			for i, r := range prop.Required {
				reqAny[i] = r
			}
			propMap["required"] = reqAny
		}
		if prop.Items != nil {
			propMap["items"] = convertPropertySchemaToMap(prop.Items)
		}

		result[name] = propMap
	}
	return result
}
